Map<String, String> bengali = {
  'Dairy Animal and Climate Change': 'গবাদি পশু এবং জলবায়ু পরিবর্তন',
  'NDRI Climate Services': 'এনডিআরআই জলবায়ু সেবা',
  'An effort by ICAR-National Dairy Research Institute, Karnal to promote climate resilient Murrah buffalo rearing practices':
      'জলবায়ু সহনশীল গবাদি পশু পালন প্রথা প্রচারের জন্য ভারতীয় কৃষি গবেষণা পরিষদ -রাষ্ট্রীয় ডেরি অনুসন্ধান সংস্থান, কর্নাল এর একটি প্রচেষ্টা',
  'Climate Resilient Dairy Farming practices':
      'জলবায়ু সহনশীল ডেইরি চাষ পদ্ধতি',
  'Climate services by ICAR-National Dairy Research Institute (NDRI), Karnal':
      'ভারতীয় কৃষি গবেষণা পরিষদ -রাষ্ট্রীয় ডেরি অনুসন্ধান সংস্থান, কর্নাল দ্বারা জলবায়ু সেবা',
  'Murrah Buffalo': 'মুররাহ মহিষ',
  'Cattle': 'গবাদি পশু',
  'Dairy Animal': 'ডেইরি প্রাণী',
  'Home': 'প্রথম পাতা',
  'Enter Your Name:': 'আপনার নাম লিখুন:',
  'Phone Number': 'ফোন নম্বর',
  'Enter Your Phone number': 'আপনার ফোন নম্বর লিখুন',
  'Enter Your District': 'আপনার জেলা লিখুন',
  'FeedBack/Message': 'প্রতিক্রিয়া/বার্তা',
  'Write your Feedback here': 'এখানে আপনার প্রতিক্রিয়া লিখুন',
  'Feedback': 'প্রতিক্রিয়া',
  'Dashboard': 'ড্যাশবোর্ড',
  'Daily forecast': 'দৈনিক পূর্বাভাস',
  'Climate Advisory': 'জলবায়ু পরামর্শ',
  'Past advisories': 'পুরাতন পরামর্শ',
  'No advisories available': 'কোন পরামর্শ পাওয়া যায়নি',
  'No advisories available for this period.': 'এই সময়কালের জন্য কোন পরামর্শ পাওয়া যায়নি',
  'Location': 'স্থান',
  'Language': 'ভাষা',
  'Distt': 'জেলা ',
  'Weekly Weather Forecast': 'সাপ্তাহিক আবহাওয়া পূর্বাভাস',
  'Period': 'সময়কাল',
  'Tmax': 'সর্বাধিক তাপমাত্রা',
  'Tmin': 'সর্বনিম্ন তাপমাত্রা',
  'Rainfall(mm)': 'বৃষ্টিপাত (মিমি)',
  'RH(%)': 'আদ্রতা  (%)',
  'Wind Speed(kmph)': 'বায়ুর গতি (কিমি/ঘণ্টা) ',
  'Wind Direction (Degree)': 'বায়ুর দিক (ডিগ্রি)',
  'Cloud cover(octa)': 'মেঘাচ্ছন্নতা (অক্টা)',
  'THI': 'তাপমাত্রা-আদ্রতা সূচক',
  'Climate services for the period of ':
      'পর্যন্ত সময়ের জন্য জলবায়ু সেবা থেকে ',
  'Major crops': 'প্রধান ফসল',
  'Climate Services For Murrah Buffalo': 'মুররাহ মহিষের জন্য জলবায়ু সেবা',
  'Date': 'তারিখ',
  'WEATHER SUMMARY': 'আবহাওয়ার সারাংশ',
  'Weather Summary/Warning:': 'আবহাওয়ার সারাংশ/সতর্কতা:',
  'Climate Advisory for Dairy Animal': 'ডেইরি প্রাণীর জন্য জলবায়ু পরামর্শ',
  'ADVISORY SERVICES FOR DAIRY ANIMALS':
      'ডেইরি প্রাণীর জন্য পরামর্শমূলক পরিষেবা',
  'ADVISORY SERVICES FOR MAJOR CROPS': 'প্রধান শস্যের জন্য পরামর্শমূলক পরিষেবা',
  'Impact of climate change on dairy animal':
      'ডেইরি প্রাণীর উপর জলবায়ু পরিবর্তনের প্রভাব',
  'Climate services': 'জলবায়ু পরিষেবা',
  'Climate Services': 'জলবায়ু পরিষেবা',
  'Feedback/Raise Your Question': 'প্রতিক্রিয়া/প্রশ্ন করুন',
  'Name': 'নাম',
  'District': 'জেলা',
  'Mobile Number': 'মোবাইল নম্বর',
  'Type feedback/Question': 'প্রতিক্রিয়া/প্রশ্ন লিখুন',
  'Submit': 'জমা দিন',
  'About Murrah Buffalo': 'মুররাহ মহিষ সম্পর্কে',
  'Feeding Management': 'খাদ্য ব্যবস্থাপনা',
  'Fodder Management': 'পশুখাদ্য ফসল ব্যবস্থাপনা',
  'Health Care Management': 'স্বাস্থ্য ব্যবস্থাপনা',
  'Management Practices': 'পরিচালন প্রক্রিয়া',
  'Thermal Stress Management': 'তাপীয় প্রভাব ব্যবস্থাপনা',
  'Weather Forecast': 'আবহাওয়ার পূর্বাভাস',
  'Temperature Maximum': 'সর্বাধিক তাপমাত্রা',
  'Temperature Minimum': 'ন্যুনতম তাপমাত্রা',
  'Temperature Humidity Index': 'তাপমাত্রা আদ্রতা সূচক',
  'About NDRI, Karnal':
      'রাষ্ট্রীয় ডেরি অনুসন্ধান সংস্থান (এনডিআরআই), কার্নালের সম্পর্কে',
      'NDRI, Karnal': 'রাষ্ট্রীয় ডেরি অনুসন্ধান সংস্থান (এনডিআরআই), কার্নালের',
  'About App': 'অ্যাপ সম্পর্কে',
  'Climate Resilient Practices': 'জলবায়ু সহনশীল প্রথা',
  'Climate Resillient Murrah Buffalo Rearing practices':
      'জলবায়ু সহনশীল মুররাহ মহিষ পালন প্রক্রিয়া',
  'Climate Resillient Cattle Rearing practices':
      'জলবায়ু সহনশীল গবাদি পশু পালন প্রক্রিয়া',
  'Sign out': 'সাইন আউট',
  'Select Language': 'ভাষা নির্বাচন করুন',
  'Select State': 'রাজ্য নির্বাচন করুন',
  'Select District': 'জেলা নির্বাচন করুন',
  'Please Select One': 'দয়া করে একটি নির্বাচন করুন',
  'English': 'ইংরেজি',
  'Hindi': 'হিন্দি',
  'Punjabi': 'পাঞ্জাবি',
  'Bengali': 'বাংলা',
  'As per IMD forecast, the temperature is likely to be comfortable and based on the calculated temperature humidity index, the environment for dairy animals will be comfortable to moderately stressful.':'আইএমডির পূর্বাভাস অনুযায়ী, তাপমাত্রা আরামদায়ক থাকার সম্ভাবনা রয়েছে এবং গণনা করা তাপমাত্রা-আদ্রতা সূচকের ভিত্তিতে, গবাদি পশুর জন্য পরিবেশ আরামদায়ক থেকে মাঝারি মাত্রায় চাপযুক্ত থাকবে।',
  'The weather is likely to remain dry in the coming days in the district area. Maximum temperature is likely to be 38°C-43°C, minimum temperature is likely to be 24°C-26°C and temperature humidity index is likely to be 68.22 to 87.47.':'জেলার এলাকায় আগামী কয়েক দিনে আবহাওয়া শুষ্ক থাকার সম্ভাবনা রয়েছে। সর্বোচ্চ তাপমাত্রা প্রায় ৩৮°C-৪৩°C এবং সর্বনিম্ন তাপমাত্রা প্রায় ২৪°C-২৬°C হতে পারে, তাপমাত্রা-আদ্রতা সূচক ৬৮.২২ থেকে ৮৭.৪৭ থাকার সম্ভাবনা রয়েছে।',
  'Due to changing weather and rising temperature during the day, animals should be kept in sheds with fans during the scorching heat of the day. Clean the shed and surrounding area to avoid infestation of house flies and others. To keep the animal healthy, give 50 grams of iodised salt and 50 to 100 grams of mineral mixture daily along with adequate concentrates and green fodder. Provide adequate clean, fresh and cool drinking water to keep the animals hydrated. Ensure bathing of buffaloes at least twice a day to reduce heat load on animals. Look for signs of mastitis in lactating animals and treat it immediately. Pregnant animals (more than 6 months) should be given extra feed.':'পরিবর্তিত আবহাওয়া ও দিনের বেলা তাপমাত্রা বাড়ার ফলে, তীব্র গরমের সময় পশুদের ফ্যানযুক্ত শেডে রাখতে হবে। মশা-মাছি ইত্যাদির উপদ্রব এড়াতে শেড ও আশেপাশের এলাকা পরিষ্কার রাখুন। পশুদের সুস্থ রাখতে প্রতিদিন ৫০ গ্রাম আয়োডাইজড লবণ এবং ৫০ থেকে ১০০ গ্রাম খনিজ মিশ্রণ পর্যাপ্ত কনসেনট্রেট ও সবুজ চারের সঙ্গে দিন। পশুদের জলবাহিত রাখতে পর্যাপ্ত পরিষ্কার, ঠান্ডা ও তাজা পানীয় জল সরবরাহ করুন। পশুদের উপর তাপের চাপ কমাতে মহিষকে দিনে অন্তত দুবার গোসল করান। দুধ দেওয়া পশুদের মধ্যে মাষ্টাইটিসের লক্ষণ দেখলে সাথে সাথে চিকিৎসা করুন। গর্ভবতী (৬ মাসের বেশি) পশুদের অতিরিক্ত খাদ্য দিন।',
  'Type your District': 'আপনার জেলা টাইপ করুন',
  'Type your State': 'আপনার রাজ্য টাইপ করুন',
  'Necessity of feeding Management in Summer and Winter':
      'গ্রীষ্ম এবং শীতকালে খাদ্য ব্যবস্থাপনার প্রয়োজনীয়তা',
      'Necess of feeding Management in Summer and Winter':
      'গ্রীষ্ম এবং শীতকালে খাদ্য ব্যবস্থাপনার প্রয়োজনীয়তা',
  'In Winters': 'শীতকালে',
  'In Summers': 'গ্রীষ্মকালে',
  'Necessity': 'প্রয়োজনীয়তা',
  'Climate Smart Practices': 'জলবায়ু স্মার্ট পদ্ধতি',
  'Temperature and humidity during April to middle of September are the cause of heat stress of the livestock. This heat stress results from the animal’s inability to dissipate sufficient heat to maintain its body temperature.':
      'এপ্রিল থেকে সেপ্টেম্বরের মাঝামাঝি সময়ের মধ্যে তাপমাত্রা এবং আর্দ্রতা পশুদের তাপীয় প্রভাবের কারণ হয়ে দাঁড়ায়। এই তাপীয় প্রভাব পশুর শরীরের তাপমাত্রা বিকিরণের অক্ষমতার ফলস্বরূপ ঘটে।',
  'High ambient temperature, relative humidity and radiant energy compromise the ability of animals to dissipate heat.':
      'উচ্চ তাপমাত্রা এবং আপেক্ষিক আর্দ্রতা পশুর তাপ নির্গমন করার ক্ষমতাকে কমিয়ে দেয়।',
  'Therefore, it increases in body temperature and reduces in productive performance particularly in milk production. This decrease can be either transitory or long term depending on the length and severity of heat stress.':
      'এর ফলে শরীরের তাপমাত্রা বৃদ্ধি পায় এবং উৎপাদনক্ষমতা বিশেষ করে দুধ উৎপাদন কমে যায়। এই হ্রাস স্থায়ী হতে পারে অথবা সাময়িক হতে পারে, যা তাপীয় প্রভাবের দৈর্ঘ্য এবং তীব্রতার উপর নির্ভর করে।',
  'The decrease in milk production may ranges from 10 to 25%. Therefore, it is utmost necessary to manage feeding practices during summer to alleviate heat stress of the dairy animals.':
      'দুধ উৎপাদনের হ্রাস ১০% থেকে ২৫% পর্যন্ত হতে পারে। সুতরাং, গ্রীষ্মকালে গবাদী পশুদের তাপীয় প্রভাব কমাতে খাদ্য ব্যবস্থাপনা সঠিক করা অত্যন্ত গুরুত্বপূর্ণ।',
  'During winter season many animals often refuse to eat, become feverish and pneumonitic which in turn affects the milk production, health and reproduction of the animal. Severe cold surroundings result in increased energy loss, which has to be compensated by giving extra calorie-rich feed and special care.':
      'শীতকালে অনেক পশু সাধারণত খেতে চায়না, জ্বরেএবং নিউমোনিয়ায় আক্রান্ত হয়ে পড়ে, যা পশুর দুধ উৎপাদন, স্বাস্থ্য এবং প্রজননে প্রভাব ফেলে। তীব্র শীতল পরিবেশের ফলে অতিরিক্ত শক্তি হ্রাস পায়, যা অতিরিক্ত ক্যালোরি-সমৃদ্ধ খাবার এবং বিশেষ যত্ন দিয়ে পূরণ করতে হয়।',
  'Feeding Management During Summer': 'গ্রীষ্মকালে খাদ্য ব্যবস্থাপনা',
  'Provision of or fresh tap water or at least normal drinking water to the livestock as per requirement throughout day and night':
      'পশুদের জন্য দিনে এবং রাতে প্রয়োজনমতো পরিষ্কার অথবা স্বাভাবিক জলের ব্যবস্থা করুন।',
  'Prefer to feed the animal during night time or early morning':
      'পশুদের সন্ধে বা বিকেল বেলা অথবা ভোরবেলা খাওয়ানো বাঞ্ছনীয়।',
  'Prefer grazing during early morning and late evening':
      'ভোরবেলা এবং সন্ধ্যায় চারণের জন্য পরামর্শ দেওয়া হয়।',
  'Ration especially energy density of the ration must be increased by decreasing straw and increasing concentrate mixture':
      'রেশনের শক্তি ঘনত্ব বাড়ানোর জন্য খড় কমিয়ে এবং কনসেন্ট্রেট মিশ্রণ বাড়ানোর চেষ্টা করুন।',
  'Provide diet with low fiber and high soluble carbohydrate':
      'কম ফাইবার এবং উচ্চ দ্রবণীয় কার্বোহাইড্রেট সম্বলিত আহার প্রদান করুন।',
  'Provide potassium rich mineral mixture':
      'পটাসিয়াম সমৃদ্ধ খনিজ মিশ্রণ প্রদান করুন।',
  'Feeding Management During Winter': 'শীতকালে খাদ্য ব্যবস্থাপনা ',
  'Nutrition, especially balanced rations, fortified and supplemented with protein ingredients like whole cotton seed or cakes, becomes important':
      'পুষ্টি, বিশেষ করে সুষম রেশন, প্রোটিন উপাদান যেমন তুলা বীজ বা কেকের সাথে পরিপূরক ও সম্পূরক হিসেবে গুরুত্বপূর্ণ।',
  'Rations containing about 17 per cent fibre in the animal feed are also helpful to increase fat percentage in milk. Concentrate mixture should comprise grains (40 percent), oil cakes (32 per cent), brans (25 per cent), mineral mixture (2 per cent) and common salt (1 per cent)':
      'পশুর খাদ্যে প্রায় ১৭% ফাইবার সম্বলিত রেশন দুধে মাখনের পরিমাণ বাড়াতে সহায়ক। কনসেন্ট্রেট মিশ্রনে,  গম (৪০%), তেলের খৈল  (৩২%), ভূষা (২৫%), খনিজ মিশ্রণ (২%) এবং সাধারণ লবণ (১%) অন্তর্ভুক্ত করা উচিত।',
  'Milch animals should be fed with a mixture of oil cakes and jiggery to maintain the body temperature':
      'দুধ দেয় এমন গরু এবং মহিষদের শরীরের তাপমাত্রা নিয়ন্ত্রণে রাখতে তেল কেক এবং গুড়ের মিশ্রণ খাওয়ানো উচিত।',
  'Essential salts / mineral mixture in appropriate quantities must be mixed with feed and given to the animals':
      'উপযুক্ত পরিমাণে প্রয়োজনীয় লবণ ও খনিজ মিশ্রণ খাবারের সাথে মিশিয়ে পশুদের দেওয়া উচিত।',
  'Apart from this the extra energy-rich grains at approximately 0.8 per cent of body weight should be fed to counter the stress of cold for maintaining normal milk production and other activities':
      'অতিরিক্ত শক্তি-সমৃদ্ধ দানা প্রায় ০.৮% শরীরের ওজন হিসাবে খাওয়ানো উচিত, যা ঠান্ডার চাপ মোকাবেলা করতে এবং স্বাভাবিক দুধ উৎপাদন ও অন্যান্য কার্যক্রম বজায় রাখতে সহায়ক।',
  'To prevent bloat in animals, mix berseem with dry fodder like wheat straw. Never feed rice straw alone.':
      'পশুদের পেট ফাঁপা প্রতিরোধ করতে, বারসীমের সাথে শুকনো খড় মিশিয়ে দিন। শুধুমাত্র ধানের খড় কখনই খাওয়াবেন না।',
  'Water, possibly lukewarm, should be clean and available four times a day at their drinking time':
      'জল, সম্ভবত উষ্ণ, পরিষ্কার এবং দিনে চারবার দিতে হবে।',
  'The quantity of green fodder must be kept in limited quantities in the animal feed, as it increases the chances of occurrence of diarrhea.Most of the time green fodder are to be mixed with straw to prevent diarrhea. Addition of straw will be useful in chewing activity which is essential for increasing body temperature.':
      'সবুজ ঘাসের পরিমাণ সীমিত রাখতে হবে, কারণ এটি ডায়রিয়া হওয়ার সম্ভাবনা বাড়ায়। সবুজ ঘাস খড়ের সাথে মিশিয়ে ডায়রিয়া প্রতিরোধ করা উচিত। খড়ের সংযোজন চিবানোর কার্যক্রমে সহায়ক যা শরীরের তাপমাত্রা বাড়ানোর জন্য গুরুত্বপূর্ণ।',
  'If there is an adequate quantity of green fodder still available after feeding the animals, this must be dried in the sun and stored for periods of shortage':
      'যদি পশুদের খাওয়ানোর পরে যথেষ্ট পরিমাণে সবুজ ঘাস অবশিষ্ট থাকে, তবে এটি রোদে শুকিয়ে সংরক্ষণ করা উচিত।',
  'Climate Smart Feeding Practices': 'জলবায়ু স্মার্ট খাদ্য ব্যবস্থাপনা ',
  'Providing balanced ration with concentrate mixture having buffer (Sodium bi-carbonate or cation based mineral supplement) for high producing buffalo during heat stress period.':
      'তাপীয় প্রভাবের সময় উচ্চ উৎপাদনশীল গবাদী পশুর জন্য বাফার (সোডিয়াম বাই-কার্বোনেট বা ক্যাটিয়ন ভিত্তিক খনিজ সম্পূরক) সহ সুষম রেশন প্রদান করুন।',
  'Mineral mixture supplementation with feed @ 50-100 gm per milch buffalo perday depending upon body weight and production performance.':
      'গবাদী পশুদের দৈনিক ৫০-১০০ গ্রাম খনিজ মিশ্রণ সম্পূরক হিসেবে প্রদান করা উচিত, যা শরীরের ওজন এবং উৎপাদন পারফরম্যান্সের উপর নির্ভর করে।',
  'Supplementation of dietary soluble carbohydrate may compensate the heat stress related reduction in milch buffalo without affecting chewing activity.':
      'খাদ্যতালিকায় দ্রবণীয় কার্বোহাইড্রেটের পরিপূরক চর্বণ কার্যকলাপকে প্রভাবিত না করে দুগ্ধ মহিষের তাপের চাপ সম্পর্কিত হ্রাসকে ক্ষতিপূরণ দিতে পারে।',
  'Supplementation of ‘Prill Fat’ (saturated fat) of 50-75 gm per lactating Murrah buffalo per day during heat stress may compensate reduced milk production.':
      'তাপীয় প্রভাবের সময় দুধারু গবাদী পশুদের জন্য প্রতিদিন ৫০-৭৫ গ্রাম ‘প্রিল ফ্যাট’ (সঞ্চিত ফ্যাট) প্রদান করেও কমে যাওয়া দুধ উৎপাদনের প্রতিকার করা যেতে পারে।',
  'Vitamin A, C, E and Zinc supplementation showed positive effects towards ameliorating environmental heat stress':
      'ভিটামিন এ, সি, ই এবং জিঙ্কের সম্পূরক পরিবেশগত তাপীয় প্রভাব কমাতে ইতিবাচক ভূমিকা পালন করে । ',
  'Disclaimer': 'দাবিত্যাগ',
  'How to save animal from Thermal stress?':
      'তাপীয় চাপ থেকে প্রাণীকে কীভাবে বাঁচানো যায়?',
  'Sign Out': 'সাইন আউট',
}
  ..addAll({
    'Andaman and Nicobar Islands': 'অন্ডমান এবং নিকোবর দ্বীপপুঞ্জ',
    'Andhra Pradesh': 'আন্ধ্র প্রদেশ',
    'Arunachal Pradesh': 'অরুণাচল প্রদেশ',
    'Assam': 'অসম',
    'Bihar': 'বিহার',
    'Chandigarh': 'চণ্ডীগড়',
    'Chhattisgarh': 'ছত্তিসগড়',
    'Dadra and Nagar Haveli and Daman and Diu':
        'দাদরা ও নগর হাভেলি এবং দমন ও দিউ',
    'Delhi': 'দিল্লি',
    'Goa': 'গোয়া',
    'Gujarat': 'গুজরাট',
    'Haryana': 'হরিয়ানা',
    'Himachal Pradesh': 'হিমাচল প্রদেশ',
    'Jammu and Kashmir': 'জম্মু ও কাশ্মীর',
    'Jharkhand': 'ঝাড়খণ্ড',
    'Karnataka': 'কর্ণাটক',
    'Kerala': 'কেরল',
    'Ladakh': 'লাদাখ',
    'Lakshadweep': 'লক্ষদ্বীপ',
    'Madhya Pradesh': 'মধ্য প্রদেশ',
    'Maharashtra': 'মহারাষ্ট্র',
    'Manipur': 'মণিপুর',
    'Meghalaya': 'মেঘালয়',
    'Mizoram': 'মিজোরাম',
    'Nagaland': 'নাগাল্যান্ড',
    'Odisha': 'ওড়িশা',
    'Puducherry': 'পুদুচেরি',
    'Punjab': 'পাঞ্জাব',
    'Rajasthan': 'রাজস্থান',
    'Sikkim': 'সিকিম',
    'Tamil Nadu': 'তামিলনাড়ু',
    'Telangana': 'তেলেঙ্গানা',
    'Tripura': 'ত্রিপুরা',
    'Uttar Pradesh': 'উত্তর প্রদেশ',
    'Uttarakhand': 'উত্তরাখণ্ড',
    'West Bengal': 'পশ্চিমবঙ্গ',
  })
  ..addAll({
    'Nicobar': 'নিকোবর',
    'North and Middle Andaman': 'উত্তর এবং মধ্য আন্দামান',
    'South Andaman': 'দক্ষিণ আন্দামান',
    'Anantapur': 'আনন্তপুর',
    'Chittoor': 'চিত্তুর',
    'East Godavari': 'পূর্ব গোদাবরী',
    'Guntur': 'গুন্তুর',
    'Krishna': 'কৃষ্ণা',
    'Kurnool': 'কুরনুল',
    'Prakasam': 'প্রকাশম',
    'Sri Potti Sriramulu Nellore': 'শ্রী পোত্তি শ্রীরামুলু নেল্লোর',
    'Srikakulam': 'শ্রীকাকুলাম',
    'Visakhapatnam': 'বিশাখাপত্তনম',
    'Vizianagaram': 'ভিজিয়ানগরাম',
    'West Godavari': 'পশ্চিম গোদাবরী',
    'YSR Kadapa': 'ওয়াইএসআর কডাপা',
    'Anjaw': 'অঞ্জাও',
    'Changlang': 'চাংলাং',
    'Dibang Valley': 'দিবাং উপত্যকা',
    'East Kameng': 'পূর্ব কামেং',
    'East Siang': 'পূর্ব সিয়াং',
    'Kamle': 'কামলে',
    'Kra Daadi': 'ক্রা ডাদি',
    'Kurung Kumey': 'কুরুং কুমে',
    'Lepa Rada': 'লেপা রাডা',
    'Lohit': 'লোহিত',
    'Longding': 'লংডিং',
    'Lower Dibang Valley': 'নিম্ন দিবাং উপত্যকা',
    'Lower Siang': 'নিম্ন সিয়াং',
    'Lower Subansiri': 'নিম্ন সুবানসিরি',
    'Namsai': 'নামসাই',
    'Pakke Kessang': 'পাক্কে কেসাং',
    'Papum Pare': 'পাপুম পাড়ে',
    'Shi Yomi': 'শি যোমি',
    'Siang': 'সিয়াং',
    'Tawang': 'তাওয়াং',
    'Tirap': 'তিরাপ',
    'Upper Siang': 'উচ্চ সিয়াং',
    'Upper Subansiri': 'উচ্চ সুবানসিরি',
    'West Kameng': 'পশ্চিম কামেং',
    'West Siang': 'পশ্চিম সিয়াং',
    'Baksa': 'বাকসা',
    'Barpeta': 'বারপেটা',
    'Biswanath': 'বিস্বনাথ',
    'Bongaigaon': 'বঙ্গাইগাঁও',
    'Cachar': 'কাছার',
    'Charaideo': 'চরাইদেও',
    'Chirang': 'চিরাং',
    'Darrang': 'দরং',
    'Dhemaji': 'ধেমাজি',
    'Dhubri': 'ধুবরি',
    'Dibrugarh': 'ডিব্রুগড়',
    'Dima Hasao': 'ডিমা হাসাও',
    'Goalpara': 'গোয়ালপাড়া',
    'Golaghat': 'গোলাঘাট',
    'Hailakandi': 'হাইলাকান্দি',
    'Hojai': 'হোজাই',
    'Jorhat': 'যোরহাট',
    'Kamrup Metropolitan': 'কামরূপ মেট্রোপলিটন',
    'Kamrup': 'কামরূপ',
    'Karbi Anglong': 'কার্বি আংলং',
    'Karimganj': 'করিমগঞ্জ',
    'Kokrajhar': 'কোকরাঝাড়',
    'Lakhimpur': 'লখিমপুর',
    'Majuli': 'মাজুলী',
    'Morigaon': 'মরিগাঁও',
    'Nagaon': 'নগাঁও',
    'Nalbari': 'নলবাড়ি',
    'Sivasagar': 'শিবসাগর',
    'Sonitpur': 'সোনিতপুর',
    'South Salmara-Mankachar': 'দক্ষিণ সালমারা-মানকাচার',
    'Tinsukia': 'তিনসুকিয়া',
    'Udalguri': 'উদালগুড়ি',
    'West Karbi Anglong': 'পশ্চিম কার্বি আংলং',
    'Araria': 'আরারিয়া',
    'Arwal': 'অরওয়াল',
    'Aurangabad': 'ঔরঙ্গাবাদ',
    'Banka': 'বাঁকা',
    'Begusarai': 'বেগুসরাই',
    'Bhagalpur': 'ভাগলপুর',
    'Bhojpur': 'ভোজপুর',
    'Buxar': 'বক্সার',
    'Darbhanga': 'দরভাঙ্গা',
    'East Champaran': 'পূর্ব চম্পারণ',
    'Gaya': 'গয়া',
    'Gopalganj': 'গোপালগঞ্জ',
    'Jamui': 'জমুই',
    'Jehanabad': 'জাহানাবাদ',
    'Kaimur': 'কাইমুর',
    'Katihar': 'কটিহার',
    'Khagaria': 'খাগরিয়া',
    'Kishanganj': 'কিশনগঞ্জ',
    'Lakhisarai': 'লখিসরাই',
    'Madhepura': 'মধেপুরা',
    'Madhubani': 'মধুবনী',
    'Munger': 'মুঙ্গের',
    'Muzaffarpur': 'মুজাফফরপুর',
    'Nalanda': 'নালন্দা',
    'Nawada': 'নওয়াদা',
    'Patna': 'পাটনা',
    'Purnia': 'পুরনিয়া',
    'Rohtas': 'রোহতাস',
    'Saharsa': 'সাহারসা',
    'Samastipur': 'সমস্তিপুর',
    'Saran': 'সারন',
    'Sheikhpura': 'শেখপুরা',
    'Sheohar': 'শেওহার',
    'Sitamarhi': 'সীতামারহি',
    'Siwan': 'সিওয়ান',
    'Supaul': 'সুপৌল',
    'Vaishali': 'বৈশালী',
    'West Champaran': 'পশ্চিম চম্পারণ',
    'Chandigarh': 'চন্ডীগড়',
    'Balod': 'বালোদ',
    'Baloda Bazar': 'বলোদা বাজার',
    'Balrampur': 'বলরামপুর',
    'Bastar': 'বাস্তার',
    'Bemetara': 'বেমেতারা',
    'Bijapur': 'বিজাপুর',
    'Bilaspur': 'বিলাসপুর',
    'Dantewada': 'দান্তেওয়াদা',
    'Dhamtari': 'ধামতারি',
    'Durg': 'দুর্গ',
    'Gariaband': 'গড়িয়াবান্দ',
    'Janjgir-Champa': 'জাঞ্জগীর-চাম্পা',
    'Jashpur': 'জাশপুর',
    'Kabirdham': 'কবিরধাম',
    'Kanker': 'কাঙ্কের',
    'Kondagaon': 'কন্ডাগাঁও',
    'Korba': 'কোরবা',
    'Korea': 'কোরিয়া',
    'Mahasamund': 'মহাসমুন্দ',
    'Mungeli': 'মুঙ্গেলি',
    'Narayanpur': 'নারায়ণপুর',
    'Raigarh': 'রায়গড়',
    'Raipur': 'রায়পুর',
    'Rajnandgaon': 'রাজনন্দগাঁও',
    'Sukma': 'সুকমা',
    'Surajpur': 'সুরাজপুর',
    'Surguja': 'সুরগুজা',
    'Dadra and Nagar Haveli': 'দাদরা এবং নগর হাভেলি',
    'Daman': 'দমন',
    'Diu': 'দিউ',
    'Central Delhi': 'মধ্য দিল্লি',
    'East Delhi': 'পূর্ব দিল্লি',
    'New Delhi': 'নতুন দিল্লি',
    'North Delhi': 'উত্তর দিল্লি',
    'North East Delhi': 'উত্তর পূর্ব দিল্লি',
    'North West Delhi': 'উত্তর পশ্চিম দিল্লি',
    'Shahdara': 'শাহদারা',
    'South Delhi': 'দক্ষিণ দিল্লি',
    'South East Delhi': 'দক্ষিণ পূর্ব দিল্লি',
    'South West Delhi': 'দক্ষিণ পশ্চিম দিল্লি',
    'West Delhi': 'পশ্চিম দিল্লি',
    'North Goa': 'উত্তর গোয়া',
    'South Goa': 'দক্ষিণ গোয়া',
    'Ahmedabad': 'আহমেদাবাদ',
    'Amreli': 'আমরেলি',
    'Anand': 'আনন্দ',
    'Aravalli': 'আরাভালি',
    'Banaskantha': 'বানাসকাঁঠা',
    'Bharuch': 'ভারুচ',
    'Bhavnagar': 'ভাবনগর',
    'Botad': 'বোটাদ',
    'Chhota Udepur': 'ছোটা উদয়পুর',
    'Dahod': 'দাহোদ',
    'Dang': 'ডাং',
    'Devbhoomi Dwarka': 'দেবভূমি দ্বারকা',
    'Gandhinagar': 'গান্ধীনগর',
    'Gir Somnath': 'গীর সোমনাথ',
    'Jamnagar': 'জামনগর',
    'Junagadh': 'জুনাগড়',
    'Kheda': 'খেড়া',
    'Kutch': 'কচ্ছ',
    'Mahisagar': 'মহিসাগর',
    'Mehsana': 'মেহসানা',
    'Morbi': 'মোরবি',
    'Narmada': 'নর্মদা',
    'Navsari': 'নবসারি',
    'Panchmahal': 'পঞ্চমহল',
    'Patan': 'পাটান',
    'Porbandar': 'পোরবন্দর',
    'Rajkot': 'রাজকোট',
    'Sabarkantha': 'সাবারকাঁঠা',
    'Surat': 'সুরাট',
    'Surendranagar': 'সুরেন্দ্রনগর',
    'Tapi': 'তাপি',
    'Vadodara': 'বড়োদরা',
    'Valsad': 'ভলসাদ',
    'Ambala': 'অম্বালা',
    'Bhiwani': 'ভিওয়ানি',
    'Charkhi Dadri': 'চারখি দাদরি',
    'Faridabad': 'ফরিদাবাদ',
    'Fatehabad': 'ফতেহাবাদ',
    'Gurugram': 'গুরুগ্রাম',
    'Hisar': 'হিসার',
    'Jhajjar': 'ঝাঝর',
    'Jind': 'জিন্দ',
    'Kaithal': 'কৈথল',
    'Karnal': 'কর্ণাল',
    'Kurukshetra': 'কুরুক্ষেত্র',
    'Mahendragarh': 'মহেন্দ্রগড়',
    'Nuh': 'নুহ',
    'Palwal': 'পলওয়াল',
    'Panchkula': 'পঞ্চকুলা',
    'Panipat': 'পানিপথ',
    'Rewari': 'রেওয়ারি',
    'Rohtak': 'রোহতক',
    'Sirsa': 'সিরসা',
    'Sonipat': 'সোনিপত',
    'Yamunanagar': 'যমুনানগর',
    'Bilaspur (Himachal Pradesh)': 'বিলাসপুর',
    'Chamba': 'চাম্বা',
    'Hamirpur': 'হামিরপুর',
    'Kangra': 'কাংগ্রা',
    'Kinnaur': 'কিন্নৌর',
    'Kullu': 'কুল্লু',
    'Lahaul and Spiti': 'লাহৌল এবং স্পীতি',
    'Mandi': 'মাণ্ডি',
    'Shimla': 'শিমলা',
    'Sirmaur': 'সিরমৌর',
    'Solan': 'সোলান',
    'Una': 'উনা',
    'Anantnag': 'অনন্তনাগ',
    'Bandipora': 'বান্দিপোরা',
    'Baramulla': 'বারামুল্লা',
    'Budgam': 'বুদগাম',
    'Doda': 'ডোডা',
    'Ganderbal': 'গান্দেরবল',
    'Jammu': 'জম্মু',
    'Kathua': 'কাঠুয়া',
    'Kishtwar': 'কিশতওয়ার',
    'Kulgam': 'কুলগাম',
    'Kupwara': 'কুপওয়ারা',
    'Poonch': 'পুঞ্চ',
    'Pulwama': 'পুলওয়ামা',
    'Rajouri': 'রাজৌরি',
    'Ramban': 'রামবান',
    'Reasi': 'রেয়াসি',
    'Samba': 'সাম্বা',
    'Shopian': 'শোপিয়ান',
    'Srinagar': 'শ্রীনগর',
    'Udhampur': 'উধমপুর',
    'Bokaro': 'বোকারো',
    'Chatra': 'চাত্রা',
    'Deoghar': 'দেওঘর',
    'Dhanbad': 'ধনবাদ',
    'Dumka': 'দুমকা',
    'East Singhbhum': 'পূর্ব সিংভূম',
    'Garhwa': 'গড়হওয়া',
    'Giridih': 'গিরিডি',
    'Godda': 'গোড্ডা',
    'Gumla': 'গুমলা',
    'Hazaribagh': 'হাজারিবাগ',
    'Jamtara': 'জামতার',
    'Khunti': 'খুন্তি',
    'Koderma': 'কোডের্মা',
    'Latehar': 'লাতেহার',
    'Lohardaga': 'লোহারদাগা',
    'Pakur': 'পাকুর',
    'Palamu': 'পালামু',
    'Ramgarh': 'রামগড়',
    'Ranchi': 'রাঁচি',
    'Sahebganj': 'সাহেবগঞ্জ',
    'Seraikela Kharsawan': 'সেরাইকেলা খার্সাওয়ান',
    'Simdega': 'সিমডেগা',
    'West Singhbhum': 'পশ্চিম সিংভূম',
    'Bagalkot': 'বাগালকোট',
    'Ballari': 'বল্লারি',
    'Belagavi': 'বেলাগাভি',
    'Bengaluru Rural': 'বেঙ্গালুরু গ্রাম',
    'Bengaluru Urban': 'বেঙ্গালুরু শহর',
    'Bidar': 'বীদার',
    'Chamarajanagar': 'চামারাজনগর',
    'Chikballapur': 'চিকবল্লাপুর',
    'Chikkamagaluru': 'চিকমাগালুরু',
    'Chitradurga': 'চিত্তদুর্গ',
    'Dakshina Kannada': 'দক্ষিণ কন্নড়',
    'Davanagere': 'দবনগিরি',
    'Dharwad': 'ধারওয়াড়',
    'Gadag': 'গদগ',
    'Hassan': 'হাসান',
    'Haveri': 'হাভেরি',
    'Kalaburagi': 'কালাবুরাগি',
    'Kodagu': 'কোডাগু',
    'Kolar': 'কোলার',
    'Koppal': 'কোপ্পাল',
    'Mandya': 'মান্ড্যা',
    'Mysuru': 'মাইসুরু',
    'Raichur': 'রায়চুর',
    'Ramanagara': 'রামনগর',
    'Shivamogga': 'শিবমোগা',
    'Tumakuru': 'তুমাকুরু',
    'Udupi': 'উডুপি',
    'Uttara Kannada': 'উত্তরা কন্নড়',
    'Vijayapura': 'বিজয়পুরা',
    'Yadgir': 'যাদগির',
    'Alappuzha': 'আলাপ্পুঝা',
    'Ernakulam': 'এরনাকুলাম',
    'Idukki': 'ইডুক্কি',
    'Kannur': 'কান্নুর',
    'Kasaragod': 'কাসারগোড',
    'Kollam': 'কল্লাম',
    'Kottayam': 'কোত্তায়ম',
    'Kozhikode': 'কোঝিকোড',
    'Malappuram': 'মালাপ্পুরম',
    'Palakkad': 'পালক্কাড',
    'Pathanamthitta': 'পথনামথিট্টা',
    'Thiruvananthapuram': 'তিরুবনন্তপুরম',
    'Thrissur': 'ত্রিশূর',
    'Wayanad': 'ওয়ানাড',
    'Kargil': 'কারগিল',
    'Leh': 'লে',
    'Lakshadweep': 'লাক্ষাদ্বীপ',
    'Agar Malwa': 'আগর মালওয়া',
    'Alirajpur': 'আলিরাজপুর',
    'Anuppur': 'অনুপপুর',
    'Ashoknagar': 'অশোকনগর',
    'Balaghat': 'বালাঘাট',
    'Barwani': 'বড়ওয়ানি',
    'Betul': 'বেতুল',
    'Bhind': 'ভিন্দ',
    'Bhopal': 'ভোপাল',
    'Burhanpur': 'বুরহানপুর',
    'Chhatarpur': 'ছাতরপুর',
    'Chhindwara': 'ছিন্দওয়ার',
    'Damoh': 'দমোহ',
    'Datia': 'দাতিয়া',
    'Dewas': 'দেওয়াস',
    'Dhar': 'ধর',
    'Dindori': 'ডিন্ডোরি',
    'Guna': 'গুনা',
    'Gwalior': 'গ্বালিয়র',
    'Harda': 'হারদা',
    'Hoshangabad': 'হোসাঙ্গাবাদ',
    'Indore': 'ইন্দোর',
    'Jabalpur': 'জবলপুর',
    'Jhabua': 'ঝাবুয়া',
    'Katni': 'কাটনি',
    'Khandwa': 'খাণ্ডোয়া',
    'Khargone': 'খারগোন',
    'Mandla': 'মান্ডলা',
    'Mandsaur': 'মানসোর',
    'Morena': 'মোরেনা',
    'Narsinghpur': 'নরসিংহপুর',
    'Neemuch': 'নিমুচ',
    'Panna': 'পান্না',
    'Raisen': 'রায়সেন',
    'Rajgarh': 'রাজগড়',
    'Ratlam': 'রতলম',
    'Rewa': 'রেওয়া',
    'Sagar': 'সাগর',
    'Satna': 'সতনা',
    'Sehore': 'সেহোরে',
    'Seoni': 'সেওনি',
    'Shahdol': 'শাহদোল',
    'Shajapur': 'শাজাপুর',
    'Sheopur': 'শেওপুর',
    'Shivpuri': 'শিবপুরী',
    'Sidhi': 'সিধি',
    'Singrauli': 'সিংরাউলি',
    'Tikamgarh': 'টিকমগড়',
    'Ujjain': 'উজ্জয়িনী',
    'Umaria': 'উমারিয়া',
    'Vidisha': 'বিদিশা',
    'Ahmednagar': 'আহমেদনগর',
    'Akola': 'আকোলা',
    'Amravati': 'আমরাবতী',
    'Beed': 'বীড',
    'Bhandara': 'ভান্ডারা',
    'Buldhana': 'বুলঢানা',
    'Chandrapur': 'চন্দ্রপুর',
    'Dhule': 'ধুলে',
    'Gadchiroli': 'গডচিরোলি',
    'Gondia': 'গোঁদিয়া',
    'Hingoli': 'হিংগোলি',
    'Jalgaon': 'জলগাঁও',
    'Jalna': 'জলনা',
    'Kolhapur': 'কোলহাপুর',
    'Latur': 'লাতুর',
    'Mumbai City': 'মুম্বাই শহর',
    'Mumbai Suburban': 'মুম্বাই উপনগর',
    'Nagpur': 'নাগপুর',
    'Nanded': 'নান্দেদ',
    'Nandurbar': 'নান্দুরবার',
    'Nashik': 'নাসিক',
    'Osmanabad': 'ওসমানাবাদ',
    'Palghar': 'পালঘর',
    'Parbhani': 'পরভানি',
    'Pune': 'পুনে',
    'Raigad': 'রায়গড়',
    'Ratnagiri': 'রত্নগিরি',
    'Sangli': 'সাংলি',
    'Satara': 'সাতারা',
    'Sindhudurg': 'সিন্ধুদুর্গ',
    'Solapur': 'সোলাপুর',
    'Thane': 'থানে',
    'Wardha': 'ওয়ার্ধা',
    'Washim': 'ওয়াশিম',
    'Yavatmal': 'ইয়াভতমাল',
    'Bishnupur': 'বিশনুপুর',
    'Chandel': 'চান্ডেল',
    'Churachandpur': 'চুরাচাঁদপুর',
    'Imphal East': 'ইম্ফল পূর্ব',
    'Imphal West': 'ইম্ফল পশ্চিম',
    'Jiribam': 'জিরিবাম',
    'Kakching': 'কাকচিং',
    'Kamjong': 'কামজং',
    'Kangpokpi': 'কাংপোকপি',
    'Noney': 'নোনে',
    'Pherzawl': 'ফেরজল',
    'Senapati': 'সেনাপতি',
    'Tamenglong': 'তামেংলং',
    'Tengnoupal': 'তেংনৌপাল',
    'Thoubal': 'থৌবাল',
    'Ukhrul': 'উখরুল',
    'East Garo Hills': 'পূর্ব গারো পাহাড়',
    'East Jaintia Hills': 'পূর্ব জৈন্তিয়া পাহাড়',
    'East Khasi Hills': 'পূর্ব খাসি পাহাড়',
    'North Garo Hills': 'উত্তর গারো পাহাড়',
    'Ri Bhoi': 'রি ভোই',
    'South Garo Hills': 'দক্ষিণ গারো পাহাড়',
    'South West Garo Hills': 'দক্ষিণ পশ্চিম গারো পাহাড়',
    'South West Khasi Hills': 'দক্ষিণ পশ্চিম খাসি পাহাড়',
    'West Garo Hills': 'পশ্চিম গারো পাহাড়',
    'West Jaintia Hills': 'পশ্চিম জৈন্তিয়া পাহাড়',
    'West Khasi Hills': 'পশ্চিম খাসি পাহাড়',
    'Aizawl': 'আইজল',
    'Lunglei': 'লুংলেই',
    'Champhai': 'চামফাই',
    'Serchhip': 'সেরছিপ',
    'Kolasib': 'কোলাসিব',
    'Lawngtlai': 'লংট্লাই',
    'Mamit': 'মামিত',
    'Saiha': 'সাইহা',
    'Hnahthial': 'হনাথিয়াল',
    'Saitual': 'সাইতুয়াল',
    'Khawzawl': 'খাওজল',
    'Chumoukedima': 'চুমৌকেদিমা',
    'Dimapur': 'দিমাপুর',
    'Kiphire': 'কিফিরে',
    'Kohima': 'কোহিমা',
    'Longleng': 'লংলেং',
    'Mokokchung': 'মোককচুং',
    'Mon': 'মন',
    'Noklak': 'নকলাক',
    'Peren': 'পেরেন',
    'Phek': 'ফেক',
    'Tuensang': 'তুয়েনসাং',
    'Wokha': 'ওখা',
    'Zunheboto': 'জুনহেবোটো',
    'Angul': 'অঙ্গুল',
    'Balangir': 'বালাঙ্গির',
    'Balasore': 'বালাসোর',
    'Bargarh': 'বারগড়',
    'Bhadrak': 'ভদ্রক',
    'Boudh': 'বৌধ',
    'Cuttack': 'কটক',
    'Deogarh': 'দেওগড়',
    'Dhenkanal': 'ধেনকানাল',
    'Gajapati': 'গজপতি',
    'Ganjam': 'গঞ্জাম',
    'Jagatsinghpur': 'জগতসিংহপুর',
    'Jajpur': 'জাজপুর',
    'Jharsuguda': 'ঝারসুগুডা',
    'Kalahandi': 'কালাহান্ডি',
    'Kandhamal': 'কান্ধামাল',
    'Kendrapara': 'কেন্দ্রাপাড়া',
    'Kendujhar': 'কেন্দ্রুজার',
    'Khordha': 'খুর্দা',
    'Koraput': 'কোরাপুট',
    'Malkangiri': 'মলকানগিরি',
    'Mayurbhanj': 'ময়ূরভঞ্জ',
    'Nabarangpur': 'নবরঙ্গপুর',
    'Nayagarh': 'নয়াগড়',
    'Nuapada': 'নুয়াপাড়া',
    'Puri': 'পুরী',
    'Rayagada': 'রায়গাদা',
    'Sambalpur': 'সাম্বলপুর',
    'Subarnapur': 'সুবর্ণপুর',
    'Sundergarh': 'সুন্দরগড়',
    'Puducherry': 'পুদুচেরি',
    'Karaikal': 'কারাইকাল',
    'Mahe': 'মাহে',
    'Yanam': 'ইয়ানাম',
    'Amritsar': 'অমৃতসর',
    'Barnala': 'বর্ণালা',
    'Bathinda': 'বাঠিন্ডা',
    'Faridkot': 'ফরিদকোট',
    'Fatehgarh Sahib': 'ফতেহগড় সাহিব',
    'Fazilka': 'ফাজিলকা',
    'Ferozepur': 'ফিরোজপুর',
    'Gurdaspur': 'গুরদাসপুর',
    'Hoshiarpur': 'হোশিয়ারপুর',
    'Jalandhar': 'জলন্ধর',
    'Kapurthala': 'কাপুরথলা',
    'Ludhiana': 'লুধিয়ানা',
    'Malerkotla': 'মালেরকোটলা',
    'Mansa': 'মানসা',
    'Moga': 'মোগা',
    'Mohali': 'মোহালি',
    'Muktsar': 'মুক্তসর',
    'Pathankot': 'পাঠানকোট',
    'Patiala': 'পাটিয়ালা',
    'Rupnagar': 'রূপনগর',
    'Sangrur': 'সংগরুর',
    'Shaheed Bhagat Singh Nagar': 'শহীদ ভগৎ সিং নগর',
    'Tarn Taran': 'তার্ন তারান',
    'Ajmer': 'আজমের',
    'Alwar': 'আলওয়ার',
    'Banswara': 'বনসওয়ারা',
    'Baran': 'বারান',
    'Barmer': 'বারমের',
    'Bharatpur': 'ভরতপুর',
    'Bhilwara': 'ভিলওয়ারা',
    'Bikaner': 'বিকানের',
    'Bundi': 'বুন্দি',
    'Chittorgarh': 'চিত্তৌরগড়',
    'Churu': 'চুরু',
    'Dausa': 'দৌসা',
    'Dholpur': 'ধলপুর',
    'Dungarpur': 'ডুংগারপুর',
    'Hanumangarh': 'হনুমানগড়',
    'Jaipur': 'জয়পুর',
    'Jaisalmer': 'জয়সলমের',
    'Jalore': 'জালোর',
    'Jhalawar': 'ঝালাওয়ার',
    'Jhunjhunu': 'ঝুঞ্জুনু',
    'Jodhpur': 'জোধপুর',
    'Karauli': 'কারাউলি',
    'Kota': 'কোটা',
    'Nagaur': 'নাগৌর',
    'Pali': 'পালি',
    'Pratapgarh': 'প্রতাপগড়',
    'Rajsamand': 'রাজসমন্দ',
    'Sawai Madhopur': 'সাওয়াই মাধোপুর',
    'Sikar': 'সিকার',
    'Sirohi': 'সিরোহি',
    'Sri Ganganagar': 'শ্রী গঙ্গানগর',
    'Tonk': 'টঙ্ক',
    'Udaipur': 'উদয়পুর',
    'East Sikkim': 'পূর্ব সিকিম',
    'North Sikkim': 'উত্তর সিকিম',
    'South Sikkim': 'দক্ষিণ সিকিম',
    'West Sikkim': 'পশ্চিম সিকিম',
    'Ariyalur': 'আরিয়ালুর',
    'Chengalpattu': 'চেঙ্গালপট্টু',
    'Chennai': 'চেন্নাই',
    'Coimbatore': 'কোয়েম্বাটুর',
    'Cuddalore': 'কুড্ডালোর',
    'Dharmapuri': 'ধর্মপুরি',
    'Dindigul': 'ডিন্ডিগুল',
    'Erode': 'এরোড',
    'Kallakurichi': 'কল্লাকুরিচি',
    'Kancheepuram': 'কাঞ্চিপুরম',
    'Kanyakumari': 'কন্যাকুমারী',
    'Karur': 'করুর',
    'Krishnagiri': 'কৃষ্ণগিরি',
    'Madurai': 'মাদুরাই',
    'Mayiladuthurai': 'মায়িলাদুতুরাই',
    'Nagapattinam': 'নাগাপত্তিনম',
    'Namakkal': 'নামাক্কল',
    'Nilgiris': 'নীলগিরি',
    'Perambalur': 'পেরাম্বলুর',
    'Pudukkottai': 'পুদুক্কোটাই',
    'Ramanathapuram': 'রমনাথপুরম',
    'Ranipet': 'রানিপেট',
    'Salem': 'সেলেম',
    'Sivaganga': 'শিবগঙ্গা',
    'Tenkasi': 'তেনকাসি',
    'Thanjavur': 'তাঞ্জাভুর',
    'Theni': 'থেনি',
    'Thoothukudi': 'থুতুকুডি',
    'Tiruchirappalli': 'তিরুচিরাপল্লি',
    'Tirunelveli': 'তিরুনেলভেলি',
    'Tiruvallur': 'তিরুভাল্লুর',
    'Tiruvannamalai': 'তিরুভান্নামালাই',
    'Tiruvarur': 'তিরুভারুর',
    'Vellore': 'ভেলোর',
    'Viluppuram': 'ভিলুপুরম',
    'Virudhunagar': 'বিরুধুনগর',
    'Adilabad': 'আদিলাবাদ',
    'Bhadradri Kothagudem': 'ভদ্রাদ্রি কোটাগুদেম',
    'Hanamkonda': 'হনমকোন্ডা',
    'Hyderabad': 'হায়দ্রাবাদ',
    'Jagtial': 'জগতিয়াল',
    'Jangaon': 'জাঙ্গাঁও',
    'Jayashankar Bhupalpally': 'জয়শংকর ভূপালপল্লী',
    'Jogulamba Gadwal': 'জোগুলাম্বা গাদওয়াল',
    'Kamareddy': 'কামারেড্ডি',
    'Karimnagar': 'করিমনগর',
    'Khammam': 'খাম্মাম',
    'Kumuram Bheem Asifabad': 'কুমারাম ভীম আসিফাবাদ',
    'Mahabubabad': 'মহবুবাবাদ',
    'Mahabubnagar': 'মহবুবনগর',
    'Mancherial': 'মানচেরিয়াল',
    'Medak': 'মেদক',
    'Medchal-Malkajgiri': 'মেদচাল-মাল্কাজগিরি',
    'Mulugu': 'মুলুগু',
    'Nagarkurnool': 'নাগরকুরনুল',
    'Nalgonda': 'নালগোন্ডা',
    'Narayanpet': 'নারায়ণপেট',
    'Nirmal': 'নির্মল',
    'Nizamabad': 'নিজামাবাদ',
    'Peddapalli': 'পেডাপল্লী',
    'Rajanna Sircilla': 'রাজান্না সির্সিলা',
    'Ranga Reddy': 'রঙ্গা রেড্ডি',
    'Sangareddy': 'সাঙ্গা রেড্ডি',
    'Siddipet': 'সিদ্ধিপেট',
    'Suryapet': 'সুর্যপেট',
    'Vikarabad': 'ভিকারাবাদ',
    'Wanaparthy': 'বনাপারথি',
    'Warangal Urban': 'ওয়ারাঙ্গাল আরবান',
    'Warangal Rural': 'ওয়ারাঙ্গাল রুরাল',
    'Yadadri Bhuvanagiri': 'যাদাদ্রি ভূবনগিরি',
    'Dhalai': 'ধলাই',
    'Gomati': 'গোমতী',
    'Khowai': 'খোওয়াই',
    'North Tripura': 'উত্তর ত্রিপুরা',
    'Sepahijala': 'সেপাহিজালা',
    'South Tripura': 'দক্ষিণ ত্রিপুরা',
    'Unakoti': 'উনাকোটি',
    'West Tripura': 'পশ্চিম ত্রিপুরা',
    'Agra': 'আগ্রা',
    'Aligarh': 'আলীগড়',
    'Ambedkar Nagar': 'অম্বেদকর নগর',
    'Amethi': 'আমেঠি',
    'Amroha': 'আমরোহা',
    'Auraiya': 'অরাইয়া',
    'Ayodhya': 'অযোধ্যা',
    'Azamgarh': 'আজমগড়',
    'Badaun': 'বাদাউন',
    'Baghpat': 'বাগপত',
    'Bahraich': 'বাহরাইচ',
    'Ballia': 'বালিয়া',
    'Banda': 'বান্দা',
    'Barabanki': 'বারাবানকি',
    'Bareilly': 'বেরেলি',
    'Basti': 'বস্তি',
    'Bhadohi': 'ভাদোহি',
    'Bijnor': 'বিজনৌর',
    'Budaun': 'বাদাউন',
    'Bulandshahr': 'বুলন্দশহর',
    'Chandauli': 'চন্দৌলি',
    'Chitrakoot': 'চিতরকূট',
    'Deoria': 'দেওরিয়া',
    'Etah': 'এটা',
    'Etawah': 'ইটাওয়া',
    'Farrukhabad': 'ফরুকাবাদ',
    'Fatehpur': 'ফতেপুর',
    'Firozabad': 'ফিরোজাবাদ',
    'Gautam Buddha Nagar': 'গৌতম বুদ্ধ নগর',
    'Ghaziabad': 'গাজিয়াবাদ',
    'Ghazipur': 'গাজীপুর',
    'Gonda': 'গোন্ডা',
    'Gorakhpur': 'গোরক্ষপুর',
    'Hapur': 'হাপুর',
    'Hardoi': 'হারদোই',
    'Hathras': 'হাথরাস',
    'Jalaun': 'জালাউন',
    'Jaunpur': 'জৌনপুর',
    'Jhansi': 'ঝাঁসি',
    'Kannauj': 'কন্নৌজ',
    'Kanpur Dehat': 'কানপুর দেহাত',
    'Kanpur Nagar': 'কানপুর নগর',
    'Kasganj': 'কাসগঞ্জ',
    'Kaushambi': 'কৌশাম্বী',
    'Kushinagar': 'কুশীনগর',
    'Kheri': 'খেরি',
    'Lalitpur': 'ললিতপুর',
    'Lucknow': 'লখনউ',
    'Maharajganj': 'মহারাজগঞ্জ',
    'Mahoba': 'মহোবা',
    'Mainpuri': 'মেনপুরী',
    'Mathura': 'মথুরা',
    'Mau': 'মাউ',
    'Meerut': 'মীরাট',
    'Mirzapur': 'মির্জাপুর',
    'Moradabad': 'মোরাদাবাদ',
    'Muzaffarnagar': 'মুজাফফরনগর',
    'Pilibhit': 'পিলিভিত',
    'Prayagraj': 'প্রয়াগরাজ',
    'Rae Bareli': 'রায়বেরেলী',
    'Rampur': 'রামপুর',
    'Saharanpur': 'সাহারানপুর',
    'Sambhal': 'সাম্ভাল',
    'Sant Kabir Nagar': 'সন্ত কাবীর নগর',
    'Shahjahanpur': 'শাহজাহানপুর',
    'Shamli': 'শামলি',
    'Shrawasti': 'শ্রাবস্তী',
    'Siddharthnagar': 'সিদ্ধার্থনগর',
    'Sitapur': 'সীতাপুর',
    'Sonbhadra': 'সোনভদ্র',
    'Sultanpur': 'সুলতানপুর',
    'Unnao': 'উন্নাও',
    'Varanasi': 'বারাণসী',
    'Almora': 'আলমোড়া',
    'Bageshwar': 'বাগেশ্বর',
    'Chamoli': 'চামোলি',
    'Champawat': 'চম্পাবত',
    'Dehradun': 'দেহরাদুন',
    'Haridwar': 'হরিদ্বার',
    'Nainital': 'নৈনিতাল',
    'Pauri Garhwal': 'পৌরি গড়ওয়াল',
    'Pithoragarh': 'পিথোরাগড়',
    'Rudraprayag': 'রুদ্রপ্রয়াগ',
    'Tehri Garhwal': 'টেহরি গড়ওয়াল',
    'Udham Singh Nagar': 'উধম সিং নগর',
    'Uttarkashi': 'উত্তরকাশী',
    'Alipurduar': 'আলিপুরদুয়ার',
    'Bankura': 'বাঁকুড়া',
    'Birbhum': 'বীরভূম',
    'Cooch Behar': 'কুচবিহার',
    'Darjeeling': 'দার্জিলিং',
    'East Bardhaman': 'পূর্ব বর্ধমান',
    'East Medinipur': 'পূর্ব মেদিনীপুর',
    'Hooghly': 'হুগলি',
    'Howrah': 'হাওড়া',
    'Jalpaiguri': 'জলপাইগুড়ি',
    'Jhargram': 'ঝাড়গ্রাম',
    'Kalimpong': 'কালিম্পং',
    'Kolkata': 'কলকাতা',
    'Malda': 'মালদা',
    'Murshidabad': 'মুর্শিদাবাদ',
    'Nadia': 'নদীয়া',
    'North 24 Parganas': 'উত্তর ২৪ পরগনা',
    'Dakshin Dinajpur': 'দক্ষিণ দিনাজপুর',
    'Purba Bardhaman': 'পূর্ব বর্ধমান',
    'Purba Medinipur': 'পূর্ব মেদিনীপুর',
    'Purulia': 'পুরুলিয়া',
    'South 24 Parganas': 'দক্ষিণ ২৪ পরগণা',
    'Uttar Dinajpur': 'উত্তর দিনাজপুর',
    'West Bardhaman': 'পশ্চিম বর্ধমান',
  })
  ..addAll({
    'Sorghum': 'জোয়ার',
    "SORGHUM": 'জোয়ার',
    "Seed Rate and Sowing Method": "বীজের হার এবং বপন পদ্ধতি",
    "The crop is sown in rows of 30cm (single cut) to 45 cm (multi cut) apart with a plant to plant spacing of 15 cm. For sorghum 50-60 kg/ha seed is sufficient,sown at a depth of 2-5 cm.":
        "এই ফসলটি ৩০ সেমি (একবার কাটা যায় এমন প্রজাতি) থেকে ৪৫ সেমি (অনেকবার কাটা যায় এমন প্রজাতি) দূরত্বে সারি করে এবং ১৫ সেমি ব্যবধান রেখে বোনা হয়। জোয়ার বপনের জন্য ৫০-৬০ কেজি প্রতি হেক্টর বীজ যথেষ্ট, যা ২-৫ সেমি গভীরতায় বোনা হয়।",
    "Sowing Time": "বপনের সময়",
    "Summer:20 March to 10 April": "গ্রীষ্ম: ২০ মার্চ থেকে ১০ ",
    "Kharif:25 June to 10 July": "খারিফ: ২৫ জুন থেকে ১০ জুলাই",
    "Single cut: HC 136, HC171, HC260, HC308":
        "একবার কাটা যায়: HC 136, HC171, HC260, HC308",
    "Multicut: Sweet sudan grass 59-3; Dual purpose: HJ 513":
        "অনেকবার কাটা যায়: সুইট সুদান ঘাস 59-3; উভয় ধরণের: HJ 513",
    "FYM application @ 10 (rainfed) to 25 t/ha (irrigated) before sowing.Crop is fertilized with 80-40-0 (single cut), 120-60-0 (double cut) and 210-60-60 (multi cut)kg/ha of NPK, respectively.":
        "গোবর সার প্রয়োগ করুন,  ১০ (বৃষ্টিপাতভিত্তিক) থেকে ২৫ টন/হেক্টর (সেচ যুক্ত জমিতে) বীজ বুনার আগে। ফসলটিকে ৮০-৪০-০ (একবার কাটা যায়), ১২০-৬০-০ (দুবার কাটা যায়) এবং ২১০-৬০-৬০ (অনেকবার কাটা যায়) কেজি প্রতি হেক্টর নাইট্রোজেন-ফসফরাস -পটাশ  সার প্রয়োগ করুন।",
    "One hand weeding 15-20 DAS is necessary. For chemical weed control apply atrazine @ 500g/ha between 7-15 days after sowing using 625 L of water.":
        "১৫-২০ দিন পর একবার হাতে আগাছা সরানো প্রয়োজন। রাসায়নিক আগাছা নিয়ন্ত্রণের জন্য, বীজ বপনের ৭-১৫ দিন পর ৫০০ গ্রাম প্রতি হেক্টর অ্যাট্রাজিন প্রয়োগ করুন ৬২৫ লিটার জলে।",
    "Downy mildew: seed treatment with Agrosan GN or Ceresan @ 4 g/ kg seed and spray of Dithane Z 78 (0.2%) to reduce secondary infection;":
        "ডাউনী মিলডিউ: বীজের সাথে Agrosan GN বা Ceresan @ ৪ গ্রাম/কেজি বীজ এবং সেকেন্ডারি সংক্রমণ কমানোর জন্য Dithane Z ৭৮ (০.২%) স্প্রে করুন",
    "Anthracnose: Seed treatment with Agrosan GN @ 3 g/kg seed followed by spray of Zineb (0.2%) at 10 days interval starting from 35 DAS.":
        "অ্যানথ্রাকনোজ: Agrosan GN @ ৩ গ্রাম/কেজি বীজ দিয়ে বীজের পরিচর্যা এবং বীজ বপনের ৩৫ দিন পর থেকে ১০ দিনের ব্যবধানে Zineb (০.২%) স্প্রে করুন।",
    "Sorghum shoot fly - Application of Carbaryl 10 G or Phorate 10 G @ 5.0 kg/ha is effective in borer management. Early sowing (1st week of June) may avoid shoot fly attack.":
        "কাণ্ড ছিদ্রকারী পোকার ব্যবস্থাপনার জন্য Carbaryl ১০ G বা Phorate ১০ G @ ৫.০ কেজি/হেক্টর প্রয়োগ কার্যকর। আগাছার আক্রমণ এড়াতে আগাম বপন (জুনের প্রথম সপ্তাহ); ",
    "Stem borer- Foliar spray of Carbaryl 50 WP in 500 litre water per hectare after 20 days of sowing and repeat spray 10 days after spray is effective in borer management.":
        "শোষক পোকা - বীজ বুনার ২০ দিন পর ৫০০ লিটার জলে Carbaryl ৫০ WP এর পাতা স্প্রে এবং স্প্রে করার ১০ দিন পর পুনরায় স্প্রে করুন।",
    "Harvesting": "কাটা",
    "Single cut varieties are harvested at 50-100% flowering stage. In multi cut varieties,the first cut is taken 55 DAS and the subsequent at 40 days interval. In multi cut varieties, first cut should be taken 8-10 cm above ground level so as to facilitate profuse tillering.":
        "একবার কাটা যায় এমন প্রজাতিগুলি ৫০-১০০% ফুল ফোটা অবস্থায় কাটা হয়। অনেকবার কাটা যায় প্রজাতিগুলিতে, প্রথম কাটা ৫৫ দিন পর এ নেওয়া হয় এবং পরবর্তী কাটিং প্রতি ৪০ দিন পর। অনেকবার কাটা যায় এমন প্রজাতিগুলিতে, প্রথম কাট ৮-১০ সেমি মাটির উপরে নেওয়া উচিত যাতে অধিক টিলারিং সহজ হয়।",
    "Hydrocyanic acid (HCN) or Dhurin":
        "হাইড্রোসায়ানিক অ্যাসিড (এইচসিএন) বা ধুরিন",
    "The crop at early stages contains HCN. Harvesting should not be done prior to 45 days from sowing. Silage or hay making removes the toxin. In summer, an irrigation before harvest may be effective. For hay making, pre-flowering is ideal stage for harvest. Do not turn hungry livestock out on lush regrowth of sorghum; do not graze until the regrowth is 18 to 24 inches tall.":
        "প্রথমিক পর্যায়ে ফসলটিতে HCN থাকে। বীজ বপনের ৪৫ দিনের আগে কাটা উচিত নয়। সাইলেজ বা ঘাস শুকনো করলে রাসায়নিকটির প্রতিক্রিয়া থাকে না। ঘাস বানানোর জন্য, প্রাক-ফুলন স্তর আদর্শ সময়। তাজা পুনঃবর্ধনের উপর ক্ষুধার্ত পশুদের ছেড়ে দেবেন না; পুনঃবর্ধনের উচ্চতা ১৮-২৪ ইঞ্চি না হওয়া পর্যন্ত চরানো উচিত নয়।",
    "Maize": "ভুট্টা",
    "MAIZE": 'ভুট্টা',
    "Seed Rate and Sowing Time": "বীজের হার এবং বপনের সময়",
    "40-50 kg seed/ha at 5 cm depth with 60 cm row to row spacing and 10 cm spacing between crops":
        "৫ সেমি গভীরতায় ৬০ সেমি সারি থেকে সারি দূরত্ব এবং ১০ সেমি ফসলের মধ্যে ব্যবধান রেখে ৪০-৫০ কেজি বীজ প্রতি হেক্টরের জন্য ব্যবহার করুণ।",
    "Varieties": "প্রজাতি",
    "African Tall, APFM-8, Pratap Makka, Chari 6,Ganga-4, J-1006.":
        "African Tall, APFM-8, Pratap Makka, Chari 6, Ganga-4, J-1006।",
    "Manures and Fertilizers": "জৈব সার ও সার",
    "15-30 kg Nitrogen (N), 40-60 kg Phosphorus (P), 40 kg Potassium (K) and 20 kg Zinc sulphate before planting and 60-90 kg N when the crop is 50-60 cm tall. 15 tons of FYM/hac applied a month before planting.":
        "১৫-৩০ কেজি নাইট্রোজেন (N): ৪০-৬০ কেজি ফসফরাস (P): ৪০ কেজি পটাসিয়াম (K) এবং ২০ কেজি জিঙ্ক সালফেট লাগানোর আগে এবং ফসল ৫০-৬০ সেমি লম্বা হলে ৬০-৯০ কেজি নাইট্রোজেন এবং ১ মাস আগে ১৫ টন জৈব সার হেক্টর প্রতি প্রয়োগ করুন।",
    "Irrigation": "জলসেচ",
    "1 or 2 irrigations at critical stages. Flowering and grain-filling stages are most critical; Irrigation every 15-20 days in the rainy season and every 10-12 days in the summer":
        "গুরুত্বপূর্ণ স্তরগুলিতে ১ বা ২ বার সেচ প্রয়োজন। ফুল ও দানা পূর্ণ হওয়ার সময় সবচেয়ে গুরুত্বপূর্ণ; বর্ষা কালে প্রতি ১৫-২০ দিন এবং গ্রীষ্মকালে প্রতি ১০-১২ দিন সেচ প্রয়োজন।",
    "For fodder purpose, the milk to early dough stage is preferred for higher yield and protein content. For silage, late dough stage is preferred.":
        "ঘাসের উদ্দেশ্যে, ভুট্টা খুব নরম থেকে হালকা শক্ত পর্যন্ত কাটা প্রয়োজন, উচ্চ ফলন এবং ভালো প্রোটিনের জন্য। সাইলেজের জন্য, ভুট্টা শক্ত হওয়া পর্যন্ত কাটা যেতে পারে।",
    "Oats": "জই",
    'OATS': 'জই',
    "75 kg/ha seed for small seeded varieties, while for bold seeded varieties 100 kg/ha. It can be planted with kera or pora method depending upon the moisture availability. It is always better to sow the crop with seed cum fertilizer drill by maintaining row to row distance of 25 cm. The optimum sowing time is mid-October to mid-November.":
        "ছোট বীজযুক্ত প্রজাতির জন্য ৭৫ কেজি প্রতি হেক্টর বীজ, এবং বড় বীজযুক্ত প্রজাতির জন্য ১০০ কেজি প্রতি হেক্টর। এটি কেরা বা পোরা পদ্ধতিতে লাগানো যেতে পারে আর্দ্রতার উপর নির্ভর করে। বীজ-সার ড্রিল ব্যবহার করে ২৫ সেমি সারি থেকে সারি দূরত্ব বজায় রেখে ফসল বপন করা সর্বদা ভালো। আদর্শ বপনের সময় হচ্ছে মধ্য-অক্টোবর থেকে মধ্য-নভেম্বর।",
    "Varieties Recommended for Haryana": "হরিয়ানা জন্য প্রস্তাবিত প্রজাতি",
    "Haryana Javi (HFO-114), OS-6, OS-7,Haryana Javi 8":
        "হরিয়ানা জাভি (HFO-114), OS-6, OS-7, হরিয়ানা জাভি 8",
    "Fertilizer Requirement": "সারের প্রয়োজনীয়তা",
    "40 kg N/ha at sowing and 40 kg N/ha at first irrigation. For multicut varieties 40 kg N/ha should also be applied after each cut.":
        "বপনের সময় ৪০ কেজি নাইট্রোজেন প্রতি হেক্টর এবং প্রথম সেচে ৪০ কেজি নাইট্রোজেন প্রতি হেক্টর। অনেকবার কাটা যায় এমন প্রজাতিগুলির জন্য, প্রতিটি কাটের পরে ৪০ কেজি নাইট্রোজেন প্রতি হেক্টর প্রয়োগ করা উচিত।",
    "Irrigation should be applied at one month interval. Irrigation is essential after each cutting in order to promote the regeneration of the plants.":
        "সেচ এক মাস পর পর প্রয়োগ করা উচিত। প্রতিটি কাটার পরে সেচ প্রয়োজন, যাতে পুনরায় বৃদ্ধি তরন্বিত হয়।",
    "Weed Management": "আগাছা ব্যবস্থাপনা",
    "Weed management": "আগাছা ব্যবস্থাপনা",
    "application of a broadleaf herbicide, such as 2,4-D sodium salt @ 1 kg/ha spray in 500 liter water at 35 DAS.":
        "বীজ বপনের ৩৫ দিন পরে ৫০০ লিটার জলে ২,৪-D সোডিয়াম সল্ট @ ১ কেজি/ হেক্টর স্প্রে করুন। ",
    "Disease and pest management": "রোগ ও পোকামাকড় ব্যবস্থাপনা",
    "Covered smut: Seed treatment with Emissan @ 2.5g/kg seed":
        "কভার্ড স্মাট: এমিসসান @ ২.৫ গ্রাম/কেজি বীজ দিয়ে বীজের চিকিৎসা; ",
    "Loose smut: Seed treatment with Vitavex or bavistin @ 2g/kg seed.":
        "লুজ স্মাট: ভিটাভেক্স বা ব্যাভিস্টিন @ ২ গ্রাম/কেজি বীজ দিয়ে বীজের পরিচর্যা করুন",
    "Aphid: Spray of plain water @ 400 l/ha, Application of malathion or endosulfan @ 0.05% in the patches of aphid colony.":
        "এফিড:  জল @ ৪০০ লিটার/ হেক্টর স্প্রে, ম্যালাথিওন বা এন্ডোসালফান  @ ০.০৫% প্রয়োগ করুন এফিড কলোনির প্যাচে।",
    "Berseem": "বারসীম",
    "BARSEEM": "বারসীম",
    "End of September to end of October by broadcasting. Seed rate of 20 - 25 kg/ha is recommended. Mix 1 kg of Japani sarson/Chinese cabbage or 25 kg of oat seed for harvesting higher quantity of fodder at first cut.":
        "সেপ্টেম্বরের শেষ থেকে অক্টোবরের শেষ পর্যন্ত ব্রডকাস্টিং দ্বারা। ২০-২৫ কেজি/ হেক্টর বীজের হার ব্যাবহার করুন । প্রথম কাটে বেশি ফসলের জন্য ১ কেজি জাপানি সরষে বা চাইনিজ বাঁধাকপি বা ২৫ কেজি জই বীজ মেশান।",
    "Mescavi, Hisar Berseem 1 and Hisar Berseem 2":
        "মেস্কাভি, হিসার বারসীম 1 এবং হিসার বারসীম 2",
    "Fertilizer Management": "সারের ব্যবস্থাপনা",
    "20 kg N + 70 kg P2O5 /ha before sowing of crop.":
        "বপনের আগে ২০ কেজি নাইট্রোজেন + ৭০ কেজি ফসফরাস প্রতি হেক্টর ব্যবহার করুন।",
    "Irrigation management": "সেচ ব্যবস্থাপনা",
    "The first irrigation applied after 3-5 DAS in light soils (heavy soils, 8-10 days). Later on irrigate at 15-20 days interval.":
        "প্রথম সেচ বীজ বপনের ৩-৫ দিন পরে হালকা মাটিতে (ভারী মাটিতে ৮-১০ দিন) প্রয়োগ করুন। পরবর্তীতে ১৫-২০ দিন পরে সেচ করুন।",
    "Disease management": "রোগ ব্যবস্থাপনা",
    "Stem rot: Avoid excessive irrigation. Spray 0.1% solution of Bavistine twice during January and February at 15-20 days interval. Select disease resistant variety HB 1.Root rot: Seed treatment with Thiram, Bavistine and Carbofuran @ 2.5g/kg.":
        "কাণ্ড পচা: অতিরিক্ত সেচ এড়ানো উচিত। জানুয়ারি ও ফেব্রুয়ারি মাসে ১৫-২০ দিনের ব্যবধানে ব্যাভিস্টিন এর ০.১% মিশ্রণ স্প্রে করুন। রোগ প্রতিরোধক প্রজাতি HB 1 নির্বাচন করুন। শিকড় পচা: থিরাম, ব্যাভিস্টিন  এবং কারবোফিউরান @ ২.৫ গ্রাম/কেজি দিয়ে বীজের চিকিৎসা করুন।",
    "Insect Management": "পোকামাকড় ব্যবস্থাপনা",
    "Black ants: Apply Methyl Parathian 2% dust; White grass hopper: Spray malathion @1 lt/ha in 750 lts of water.":
        "কালো পিঁপড়ে: মিথাইল প্যারাথিয়ান ২% ডাস্ট প্রয়োগ করুন; সাদা ঘাস ঝাঁপ: ৭৫০ লিটার জলে ম্যালাথিওন @ ১ লিটার/ হেক্টর স্প্রে করুন। ",
    "Cutting Management": "কাটা ব্যবস্থাপনা",
    "Harvested in 55-60 DAS and subsequent cuts after every 30 – 40 days.":
        "বীজ বপনের ৫৫-৬০ দিন পরে  প্রথম কাট এবং পরবর্তী কাট ৩০ – ৪০ দিন পরে নিতে থাকুন।",
    "Toxicity": "বিষাক্ততা",
    "A substance known as ‘astrogenons‘ is present in berseem, the excess of which makes the animal sick and causes bloat disease. Fodder should be sprayed with linseed or mustard oil. Mixing of dry fodder which contains more fiber like wheat straw also reduces the problem of bloating.":
        ": বারসীমে ‘আস্ট্রোজেনোন’ নামক একটি পদার্থ উপস্থিত থাকে, যা অতিরিক্ত পরিমাণে পশুকে অসুস্থ করে এবং অতিরিক্ত গ্যাস সৃষ্টি করে। লিনসিড বা সরিষার তেল দিয়ে স্প্রে করুন। অধিক ফাইবারযুক্ত শুকনো চারা যেমন গমের তুষ মেশালে তা অতিরিক্ত গ্যাসের সমস্যা কমায়।",
    "Foot and Mouth disease in Buffalo": "খুরিয়া বা পা এবং মুখের ঘা রোগ ",
    "Foot and Mouth disease": "খুরিয়া বা পা এবং মুখের ঘা রোগ",
    "Dripping saliva from the mouth": "মুখ থেকে লালা পড়া ",
    "Fever": "জ্বর",
    "Blisters on mouth, tongue, gums, between hooves, udder and levee":
        "মুখ, জিভ, মাড়ি, খুরের মাঝে, স্তনপায়ূ এবং লেভির ওপর ফোসকা",
    "Reduces or stops animal feeding and chewing":
        "পশুর খাওয়া ও চিবানো কমে যাওয়া বা বন্ধ হয়ে যাওয়া",
    "Animal walks with a limp especially when there are insects in the hooves":
        "পশু কষ্টের সাথে হাঁটে, বিশেষত যখন খুরে কীটপতঙ্গ থাকে",
    "There is a sharp drop in milk production": "দুধ উৎপাদনে তীব্র হ্রাস ",
    "Control and Prevention": "নিয়ন্ত্রণ এবং প্রতিরোধ",
    "The area or building where the outbreak of mouth and mouth epidemic has occurred should be disinfected by mild acid, alkali or fumigation":
        "যেখানে মুখ এবং পা রোগের প্রাদুর্ভাব ঘটেছে সেই স্থান বা গোয়ালকে মৃদু অ্যাসিড, ক্ষার বা ধোঁয়া দ্বারা জীবাণুমুক্ত করা উচিত।",
    "Movement of vehicles and animals should be banned in the affected areas":
        "আক্রান্ত এলাকায় গাড়ি এবং পশু চলাচল নিষিদ্ধ করতে হবে।",
    "Affected animals should be kept separate from healthy animals":
        "আক্রান্ত পশুকে সুস্থ পশুদের থেকে আলাদা রাখতে হবে।",
    "Control is possible by vaccinating all susceptible animals to this disease and not allowing the virus to spread from infected animals":
        "সমস্ত সংবেদনশীল পশুকে টিকা দিতে হবে এবং সংক্রমিত পশুদের থেকে ছড়াতে দেওয়া যাবেনা",
    "Twice a year (May-June and October-November) vaccination is the only effective method of prevention":
        "বছরে দুবার (মে-জুন এবং অক্টোবর-নভেম্বর) টিকা প্রদান একমাত্র কার্যকর প্রতিরোধ পদ্ধতি।",
    "The first vaccine and after 15 to 30 days must be given to the cutlets and cuttings older than four months and vaccination must be done after every 6 months":
        "প্রথম টিকা দেওয়ার পর ১৫ থেকে ৩০ দিনের মধ্যে চার মাসের বেশি পুরনো বাচ্চাদের টিকা দিতে হবে এবং প্রতি ৬ মাস পরপর টিকা দিতে হবে।",
    "Hemorrhagic Septicemia in Buffalo":
        "হেমোরেজিক সেপটিসেমিয়া (গলা ফুলে যাওয়া রোগ) ",
    "Hemorrhagic Septicemia": "হেমোরেজিক সেপটিসেমিয়া",
    "Symptoms": "লক্ষণসমূহ",
    "Having a very high fever (up to 107⁰ F) and the animal dying within an hour to 24 hours or the animal being found dead without showing any symptoms to the farmer":
        "খুব উচ্চ তাপমাত্রা (১০৭⁰ ফা পর্যন্ত) এবং পশু এক ঘণ্টা থেকে ২৪ ঘণ্টার মধ্যে মারা যায় বা কোনো লক্ষণ ছাড়াই মৃত অবস্থায় পাওয়া যায়।",
    "Profuse salivation": "প্রচুর লালা পড়া",
    "Runny nose and difficulty in breathing":
        "নাক দিয়ে জল পড়া এবং শ্বাস নিতে অসুবিধা",
    "Reddened eyes": "চোখ লাল হয়ে যাওয়া ",
    "Stop grazing and become depressed":
        "ঘাস খাওয়া বন্ধ হয়ে যায় এবং বিষণ্ণ হয়ে যায়",
    "It has been seen in a very acute condition that the animals mouth becomes stagnant with food or water":
        "খুব তীব্র অবস্থায় মুখে খাবার বা জল জমে থাকা দেখা যায় ",
    "Cognition with pain in the throat, neck and chest":
        "গলা, ঘাড় এবং বুকের ব্যথা",
    "Control": 'নিয়ন্ত্রণ',
    "Immediately separate sick buffalo from healthy animals and sterilize the place and do not take it to public places such as pastures and other places where animals congregate as this disease spreads through inhalation, drinking water and feeding":
        "অবিলম্বে অসুস্থ গরু/মোষকে সুস্থ পশুদের থেকে আলাদা করুন এবং স্থান জীবাণুমুক্ত করুন। জনসমাগম স্থান যেমন মাঠে নিয়ে যাবেন না, কারণ এই রোগ শ্বাসপ্রশ্বাস, জল এবং খাবারের মাধ্যমে ছড়ায়। ",
    "Dig a pit at least 5 feet deep to the dead animal and press it well by sprinkling salt":
        "মৃত পশুর জন্য অন্তত ৫ ফুট গভীর একটি গর্ত খনন করুন এবং লবণ ছড়িয়ে ভালোভাবে কবর দিন। ",
    "Twice a year must be vaccinated against galghotu disease, first before the start of the rainy season (in the month of May-June) and the second before the onset of winter (in the month of October - November). By doing this, there can be a significant reductionin the animal mortality rate due to gallstone disease":
        "গলা ফুলে যাওয়া রোগের বিরুদ্ধে বছরে দুবার টিকা দিতে হবে, প্রথমবার বর্ষাকালের শুরুতে (মে-জুন মাসে) এবং দ্বিতীয়বার শীতের আগমনের আগে (অক্টোবর-নভেম্বর মাসে)। এতে গলা ফুলে যাওয়া রোগের কারণে পশু মৃত্যুর হার উল্লেখযোগ্যভাবে কমানো সম্ভব।",
    "Mastitis in Buffalo": 'মাসটাইটিস/ পালান প্রদাহ রোগ ',
    "Mastitis": "মাসটাইটিস",
    "Swollen and reddening of teats": "স্তন ফুলে যাওয়া এবং লাল হয়ে যাওয়া",
    "Milk mixed with blood": "দুধে রক্ত মিশে থাকা",
    "Milk mixed with yellow or brown fluid with flakes or clots with foul smelling":
        "দুধে হলুদ বা বাদামী তরল, ফ্লেক্স বা ক্লটস সহ এবং দুর্গন্ধযুক্ত",
    "Swollen udder with hot and pain while touching it":
        "গরম এবং স্পর্শ করার সময় ব্যথা সহ ফুলে যাওয়া ",
    "Swelling of udder as a hard mass": "স্তন শক্ত গুটির মতো ফুলে যাওয়া ",
    "Animal will not allow touching the udder and will kick while touching it":
        "পশু স্তন স্পর্শ করতে দেবে না এবং স্পর্শ করলে লাথি মারে",
    "Animal sheds should be clean and floor should be washed with running water":
        "পশুশালা পরিষ্কার থাকতে হবে এবং মেঝে জল দিয়ে ধোয়া উচিত।",
    "Milker should washed their hand with soap before milking of each animal":
        "দুধ দোয়ার আগে হাত সাবান দিয়ে ধোয়া উচিত।",
    "Teats/udder of the buffalo should be washed and dried up soft cloth before milking":
        "স্তনকে দুধ দোওয়ার আগে পরিষ্কার এবং নরম কাপড় দিয়ে মুছে ফেলতে হবে।",
    "Buffalo should not be allowed to sit just after the milking and may be engaged with either fodder/concentrate mixture":
        "দুধ দোওয়ার পর পশুকে বসতে দেওয়া উচিত নয়, বরং পশুকে খাদ্য/মিশ্রণ নিয়ে ব্যস্ত রাখা উচিত। ",
    "Milking should be done completely every time. Ensure that there is no left over milk in the udder":
        "প্রতিবার সম্পূর্ণ দুধ দোওয়া উচিত। নিশ্চিত করুন যে স্তনে কোনো দুধ অবশিষ্ট নেই।",
    "Infected buffalo should be kept isolated from the herd":
        "আক্রান্ত পশুকে অন্য পশুদের থেকে বিচ্ছিন্ন রাখতে হবে।",
    "Always maintain the proper hygienic condition in the herd and shed":
        "সবসময় পশুদের পশুশালায় সঠিকভাবে পরিস্কার রাখতে হবে ।",
    "Immediately after detecting clinical signs, it should be consulted with qualified veterinarian for further treatment":
        "ক্লিনিকাল লক্ষণগুলো পাওয়ার পর অবিলম্বে পশু চিকিৎসকের সাথে পরামর্শ করুন।",
    "Deworming Schedule for Buffalo": "কৃমিনাশক সূচি ",
    "Deworming and vaccination schedule": "কৃমিনাশক এবং টিকাদান সূচি ",
    "Age of Buffalo": "মহিষের বয়স",
    "Anthelmintic": "অ্যান্থেলমিনটিক",
    "Dose": "ডোজ",
    "Schedule": "সূচি",
    "3-7 days": "৩-৭ দিন",
    "Piparazine": "পাইপারাজিন",
    "5-10 ml per 10 kg of body weight": "১০ কেজি শরীরের ওজন প্রতি ৫-১০ মি.লি.",
    "Repeat in every 21 days upto 2 months":
        "প্রতি ২১ দিন পর পুনরাবৃত্তি ২ মাস পর্যন্ত",
    "3-6 months": "৩-৬ মাস",
    "Albendazole": "অ্যালবেনডাজল",
    "5 ml per kg of body weight": "শরীরের ওজন প্রতি ৫ মি.লি.",
    "Every month": "প্রতি মাসে",
    "6-18 months": "৬-১৮ মাস",
    "Albendazole or Ivermetic injection":
        "অ্যালবেনডাজল অথবা আইভারমেকটিন ইনজেকশন",
    "Every 3 months": "প্রতি ৩ মাসে",
    "Adult buffalo": "পূর্ণ বয়স্ক গরু বা মহিষ ",
    "Albendazole , Fendendazole or Ivermetic injection":
        "অ্যালবেনডাজল,ফেনডেনজোল, অথবা আইভারমেকটিন ইনজেকশন",
    "Twice in year preferably before rainy and winter season":
        "বছরে দুবার, প্রধানত বর্ষার এবং শীতকালে",
    "Vaccination Schedule": "টিকাদান সূচি",
    "Disease": "রোগ",
    "Age and time of vaccination": "টিকাদানের বয়স এবং সময়",
    "FMD": "পা এবং মুখের ঘা রোগ ",
    "First dose at 4 months of age and booster dose at 6 months of age.Repeat every six months interval preferably during March-April and September-October":
        "প্রথম ডোজ ৪ মাস বয়সে এবং বুস্টার ডোজ ৬ মাস বয়সে।প্রতি ছয় মাস পর পুনরাবৃত্তি করা উচিত সাধারণত মার্চ-এপ্রিল এবং সেপ্টেম্বর-অক্টোবর মাসে।",
    "Haemorrhagic septicemia": "গলা ফুলে যাওয়া রোগ ",
    "First dose at 4-6 months of age and booster dose should be repeated every year preferably before rainy season in the months of May-June":
        "প্রথম ডোজ ৪-৬ মাস বয়সে এবং বুস্টার ডোজ প্রতি বছর পুনরাবৃত্তি করা উচিত বর্ষাকালের আগে মে-জুন মাসে।",
    "Black quarter": "ব্ল্যাক কোয়ার্টার",
    "First dose at 6 months of age and booster dose should be repeated every year preferably before rainy season in the months of May-June":
        "প্রথম ডোজ ৬ মাস বয়সে এবং বুস্টার ডোজ প্রতি বছর পুনরাবৃত্তি করা উচিত বর্ষাকালের  আগে মে-জুন মাসে।",
    "Brucellosis": "ব্রুসেলোসিস",
    "Single dose for female calf at the age of 4-8 months":
        "বগনা  বাছুরের জন্য এক ডোজ ৪-৮ মাস বয়সে",
  })
  ..addAll({
    "Calf Management": "বাছুরের পরিচালনা ব্যবস্থাপনা:",
    "Shed should be provided to the claves with clean, dry and bedded area for rest. In calf shed maximum ventilation for hot weather should provide for at least one air change/minute. Provide fan and cooling facility during hotter part of the day.":
        "বাছুরদের জন্য পশুশালা পরিষ্কার এবং শুষ্ক হওয়া উচিত। বাছুরদের  শেড  থেকে গরম হাওয়া  বের  করার  জন্য পৰ্য্যাপ্ত  বায়ু  চলাচলের  বাব্যস্থা রাখা । দিনের গরম সময়ে ফ্যান এবং শীতলীকরণের ব্যবস্থা করা উচিত।",
    "Provide good quality calf starter (must contain 75% TDN and 14-16 per cent digestible crude protein). Increase the frequency of feeding to fulfill the dietary requirement of the calf for proper growth of the calf under heat stress condition. Offer feed during cool hours of the day.":
        "ভালো মানের আহার (যাতে ৭৫% TDN এবং ১৪-১৬ শতাংশ হজমযোগ্য অপরিশোধিত প্রোটিন থাকে) প্রদান করা উচিত। গরমের প্রভাবের পরিস্থিতিতে বাছুরের সঠিক বৃদ্ধির জন্য খাদ্য প্রয়োজন মেটাতে বারবার করে খাওয়াতে হবে। দিনের ঠান্ডা সময়ে খাবার দিন।",
    "Calves should be kept re-hydrated. Plenty fresh and cool water should be made available for calves. Calves should be taught for water drinking from first week of life.":
        "বাছুরদের জন্য প্রচুর পরিমাণে তাজা এবং ঠান্ডা জল দেওয়া উচিত। বাছুরদের জন্মের প্রথম সপ্তাহ থেকে জল পান করা শেখানো উচিত।",
    "Vaccination, tagging and disbudding activities should be carried out in cool hours of the day.":
        "টিকা দেওয়া, ট্যাগিং এবং শিং কাটা কার্যক্রমগুলি দিনের ঠান্ডা সময়ে পরিচালিত করা উচিত।",
    "Colostrum quality should be checked during summer months so that calf should get optimum immunity through colostrum.":
        "গ্রীষ্মকালে বাছুরকে উপযুক্ত রোগ প্রতিরোধ ক্ষমতা প্রদান করতে মায়ের প্রথম গাঢ় দুধ (কোলোস্ট্রাম) খাওয়ানো উচিত। ",
    "The feeding equipments use for calf feeding should properly disinfected during summer months to avoid chance of infection.":
        "গ্রীষ্মকালে বাছুরদের খাওয়ানোর জন্য ব্যবহৃত সরঞ্জামগুলি সঠিকভাবে জীবাণুমুক্ত করা উচিত যাতে সংক্রমণের সম্ভাবনা এড়ানো যায়।",
    "Housing": "আবাস ব্যাবস্থাপনা",
    "Adequate space should be provided during the heat stress period to the dairy animals for effective heat dissipation, especially in tie stalls, which are commonly observed at farmers doorsteps and present-day small commercial dairy farms.":
        "•	গরমের প্রভাবের সময় দুধদানকারী পশুদের পর্যাপ্ত স্থান প্রদান করা উচিত যাতে তাপের বিকিরণ সহজে হয়।",
    "Sheds must be provided, especially during the summer months, to reduce the heat load from radiation. The roof should be reflective. Roof painted with white paint and insulated with puff or straw and covered with seasonal vegetable plants like bottle gourd, pumpkin and ridge gourd grown from earth is quite effective in reducing the inside temperature of the shed.":
        "গ্রীষ্মকালে গরমের প্রভাব থেকে রেহাই পেতে ছায়া প্রদান করা উচিত। ছাদ আলোক প্রতিফলনকারী হওয়া উচিত। ছাদটি সাদা রঙ দিয়ে আঁকা এবং পাফ বা খড় দিয়ে নিরোধক করা এবং লাউ, কুমড়ো এবং ঝিঙের  মতো মৌসুমি লতানো গাছ দিয়ে আচ্ছাদিত করা উচিত।",
    "The fresh and cool drinking water facility under shaded areas should be ensured for effective heat stress management.":
        "গরমের প্রভাব ব্যবস্থাপনার জন্য ছায়াময় অঞ্চলে তাজা এবং ঠান্ডা পানীয় জল সরবরাহ নিশ্চিত করা উচিত।",
    "Holding and milking areas must have adequate ventilation, air circulation, and cooling facilities as less attention has been given under Indian conditions.":
        "দুধ দোওয়ার এলাকায় পর্যাপ্ত বায়ুচলাচল এবং শীতলতার ব্যবস্থা থাকতে হবে।",
    "In hot-dry weather, misting is quite effective in cooling the environment, which further helps to cool the animals. Fogging is very effective but under closed conditions and when the temperature is high and humidity is low. In fogging, desalinated water is generally recommended; otherwise, nozzle blocking is a common problem.":
        "গরম-শুষ্ক আবহাওয়ায়, জলের স্প্রে পরিবেশ ঠান্ডা করতে বেশ কার্যকর, যা প্রাণীদের ঠান্ডা করতেও সহায়ক। জলের স্প্রে খুবই কার্যকর তবে বন্ধ অবস্থায় এবং যখন তাপমাত্রা বেশি এবং আর্দ্রতা কম থাকে। জলের স্প্রে করার সময় লবণমুক্ত জল সুপারিশ করা হয়; অন্যথায়, নোজল ব্লকিং এর সমস্যা বাড়তে থাকে।",
    "In hot-humid conditions, sprinkling for a limited period along with fanning is quite effective. In closed housing for such a cooling system, proper ventilation must be ensured to reduce the humidity buildup.":
        "গরম-আর্দ্র অবস্থায়, ফ্যান সহ সীমিত সময়ের জন্য জলের স্প্রে বেশ কার্যকর। এমন শীতল ব্যবস্থা সহ বন্ধ আবাস আর্দ্রতার পরিমাণ কম করতে, বদ্ধ আবাস ব্যবস্থায় বায়ু চলাচল নিশ্চিন্ত করতে হবে। ",
    "Straw bedding (2 inch) or mattress or sand bedding are effective to improve the resting time of dairy animals.":
        "গবাদী পশুদের বিশ্রামের সময় খড়ের বিছানা (২ ইঞ্চি) বা বালি বিছানার ব্যবস্থা করতে হবে।",
    "Animal Shed should be constructed east-west direction. Height of the shed at centre should be 14-15 ft and height at eve 12-13 feet commonly used. Researchers even used 16-18 ft height at centre and 14-15 ft at eve to maintain better micro environment inside the shed. Natural tree shed in the open paddock area and farm premises is quite effective to reduce the heat load.":
        "পশুশালা পূর্ব-পশ্চিম দিকে নির্মিত হওয়া উচিত। পশুশালার কেন্দ্রের উচ্চতা ১৪-১৫ ফুট এবং ধারের উচ্চতা ১২-১৩ ফুট সাধারণত হওয়া উচিত। গবেষকরা মধ্যের ১৬-১৮ ফুট উচ্চতা এবং ধারের ১৪-১৫ ফুট উচ্চতাও ব্যবহার করেছেন যাতে পশুশালার ভিতরে ভালো পরিবেশ বজায় থাকে। পশুশালার প্রাঙ্গণে গাছের ছায়া তাপীয় প্রভাব কমাতে বেশ কার্যকর।",
    "Reproductive Management": "প্রজনন ব্যবস্থাপনা",
    "The incidence of anoestrus in buffalo ranges from 20 to 80% depending on season.Most buffalo cease ovarian cyclicity during hot summers probably due to the combined effects of nutrition, environment and management. In the heat stress period, four to five days of adequate cooling, especially around breeding, can enhance the fertility of dairy animals.":
        "মোষের মধ্যে অনিয়মিত ঋতুচক্রের ঘটনা ঋতু অনুসারে ২০ থেকে ৮০% পর্যন্ত পরিবর্তিত হয়। গ্রীষ্মকালে মোষের প্রজননগত সমস্যা বৃদ্ধি হয় সম্ভবত পুষ্টি, পরিবেশ এবং ব্যবস্থাপনার সম্মিলিত প্রভাবের কারণে। গরমের প্রভাবে, বিশেষ করে প্রজননের আশেপাশে চার থেকে পাঁচ দিনের পর্যাপ্ত শীতলতা, দুধদানকারী পশুদের প্রজনন ক্ষমতা বাড়াতে পারে।",
    "Keeping buffalo cool by wallowing, water sprinklers or shade improves fertility.":
        "মোষকে পুকুরে নিয়ে যাওয়া, জল স্প্রে করা বা ছায়া দেওয়ার মাধ্যমে শীতল রাখলে প্রজনন ক্ষমতা বৃদ্ধি হয়।",
    "Buffalo supplemented with UMMBs for 60 days before calving will have betterpostpartum reproductive performance.":
        "গর্ভপাতের ৬০ দিন আগে গবাদী পশুকে ইউরিয়া এবং গুড় খাওয়ালে প্রসব পরবর্তী প্রজনন কর্মক্ষমতা ভালো থাকবে।",
    "Regular supplementation of UMMBs early after calving also enhances production (8% more milk) and oestrus expression within 50 days. UMMBs also induce fertile oestrus in non-pregnant anoestrous buffalo.":
        "গর্ভপাতের পরপরই ইউরিয়া এবং গুরের মিশ্রণ নিয়মিত খাওয়ালে উৎপাদন (৮% বেশি দুধ) এবং ৫০ দিনের মধ্যে প্রজনন সক্ষম হয়। ইউরিয়া ও গুরের মিশ্রণ গর্ভবতী নয় এমন মোষেও প্রজনন উদ্দীপিত করে।",
    "Ameliorative strategies in the form of environmental enrichment and cooling mechanism depending on the weather condition, nutritional manipulation, stress-relieving supplements i.e., antioxidants, yeast, buffer, vitamins (Niacin, Vitamin C and Vitamin E) and minerals, electrolytes and hormonal treatment for reproductive management is quite effective.":
        "আহারের সাথে অ্যান্টিঅক্সিডেন্ট, ইস্ট, বাফার, ভিটামিন (নিয়াসিন, ভিটামিন সি এবং ভিটামিন ই) এবং খনিজ লবণ, ইলেক্ট্রোলাইটের সংযোজন গবাদী পশুর প্রজনন ক্ষমতাকে সমৃদ্ধ করে।  ",
    "Nutrient-enriched feed in the form of good quality green fodder, concentrate, bypass fat, and protein should be supplemented to improve dairy animals reproduction performance during hot weather conditions.":
        "গ্রীষ্মকালে গবাদী পশুদের প্রজনন কর্মক্ষমতা উন্নত করতে ভালো মানের সবুজ ঘাস, কনসেন্ট্রেট, বাইপাস ফ্যাট এবং প্রোটিন সমৃদ্ধ খাদ্য দেওয়া উচিৎ। ",
    "Useful Tips": "উপকারী পরামর্শ",
    "Farmers can quickly identify the animal is in heat stress or not by simply monitoring respiration rate. If the respiration rate is more than 80 breaths per minute, heat stress is a clear indication.":
        "কৃষকরা পশুর উপর গরমের প্রভাব আছে কি না তা সহজেই শ্বাস প্রশ্বাসের হার পর্যবেক্ষণ করে চিহ্নিত করতে পারেন। যদি শ্বাস প্রশ্বাসের হার প্রতি মিনিটে ৮০ বারের বেশি হয়, তাহলে গরমের প্রভাবের ইঙ্গিত স্পষ্ট ।",
    "The more straightforward way to understand when heat stress started is that if humanbeing starts feeling the stress as for animals, it already started.":
        "গরমের প্রভাব কখন শুরু হয়েছিল তা বোঝার সহজ উপায় হল যে একজন মানুষ যদি গরমের প্রভাব অনুভব করতে শুরু করে তাহলে গবাদি পশুর মধ্যে এটি ইতিমধ্যেই শুরু হয়ে গেছে।",
    "Wallowing is very effective for buffaloes due to their black skin colour and fewer sweat glands. Natural ponds are very common in the village area and quite effective amelioration of heat through wallowing. Artificially build 50 ft. wide X 100 ft. long and 4 to 6 ft. depth wallowing pond is suitable for 100 animals.":
        "কালো ত্বকের রঙ এবং কম ঘাম গ্রন্থির কারণে মোষেদের মধ্যে গরমের  প্রভাব বেশি হয়  তাই এদেরকে পুকুরে নিয়ে যাওয়া খুবই দরকার। গ্রামীণ এলাকার পুকুর মোষেদের জন্য খুবই কার্যকারী। কৃত্রিমভাবে তৈরি ৫০ ফুট চওড়া X ১০০ ফুট লম্বা এবং ৪ থেকে ৬ ফুট গভীর পুকুর ১০০টি প্রাণীর জন্য উপযুক্ত।",
    "Optimum body condition score maintenance in different stages of physiological state and especially the animals are going to calve in heat stress period can be an effective strategy.":
        "উপযুক্ত শারীরিক পরিকাঠামো রক্ষণাবেক্ষণ করা উচিত। ",
    "Identification of genotype adapted to climatic stress and formulation of region-specific climate-resilient breeding strategies of livestock to select heat-tolerant livestock.":
        "জলবায়ু প্রভাবের সাথে খাপ খাওয়ানো জিনোটাইপের শনাক্তকরণ এবং তাপ-সহনশীল প্রাণী নির্বাচনের জন্য পশুসম্পদের অঞ্চল-নির্দিষ্ট জলবায়ু-সাশ্রয়ী প্রজনন কৌশলগুলির প্রণয়ন প্রজননের জন্য তাপ সহনশীল প্রজাতির ব্যবহার করা উচিত। ",
    "Fly control measures should be taken effectively as during summer months the problems of fly increases.":
        "•	মাছি নিয়ন্ত্রণ ব্যবস্থা নেওয়া উচিত কারণ গ্রীষ্মের মাসগুলিতে মাছির সমস্যা বৃদ্ধি পায়।",
    "Custom Drawer": "কাস্টম ড্রয়ার",
    "Open Climate Advisory": "আবহাওয়ার পরামর্শ খুলুন",
    "Today": "আজ",
    "Next Days": "পরবর্তী দিনগুলি",
    "MON": "সোম",
    "TUE": "মঙ্গল",
    "WED": "বুধ",
    "THURS": "বৃহস্পতি",
    "FRI": "শুক্র",
    "SAT": "শনি",
    "SUN": "রবি",
    "kmps": "কিমি.",
    "mm": "মিমি",
    "Max Temp": "সর্বোচ্চ টেম্প",
    "Min Temp": "সর্বনিম্ন টেম্প",
    "Rainfall": "বৃষ্টিপাত",
    "Humidity": "আর্দ্রতা",
    "Wind Speed": "বাতাসের গতি",
    "Wind Dir": "হাওয়া দির",
    "Cloud Cover": "মেঘের আচ্ছাদন",
    "(octa)": "(অক্টা)"
  })
  ..addAll({
    "Management During Thermal Stress": "তাপীয় প্রবাহের সময় ব্যবস্থাপনা",
    "Symptoms of Heat Stress": "তাপ চাপের লক্ষণ",
    "Thermal stress occurs when the ambient temperature lies above or below thermoneutral zone. Dairy animals have been found to be negatively impacted with increased temperature and humidity.":
        "তাপীয় প্রবাহ ঘটে যখন পারিপার্শ্বিক তাপমাত্রা সহনশীল তাপমাত্রার উপর বা নিচে থাকে। দুধদানকারী পশুদের, তাপমাত্রা এবং আর্দ্রতা বৃদ্ধির কারণে প্রবাহ নেতিবাচকভাবে প্রভাবিত হতে দেখা গেছে।",
    "Rapid and weak pulse and rapid but shallow breathing":
        "দ্রুত এবং দুর্বল নাড়ি এবং দ্রুত কিন্তু অগভীর শ্বাস",
    "Abnormal vital parameters: Elevated heart rate, respiration rate, rectal temperature etc.":
        "অস্বাভাবিক গুরুত্বপূর্ণ সঙ্কেত: হৃদস্পন্দনের হার, শ্বাসপ্রশ্বাসের হার, রেকটাল তাপমাত্রা ইত্যাদি বৃদ্ধি পাওয়া।",
    "Unusual salivation and dizziness/unconsciousness":
        "অস্বাভাবিক লালাস্রাব এবং মাথা ঘোরা/অচেতনতা",
    "Skin becomes dull and may be cold":
        "ত্বক ম্লান হয়ে যায় এবং ঠান্ডা হতে পারে",
    "In case of heat stroke, body temperature is very high sometimes as high as 106 - 108°F.":
        "তাপীয় প্রবাহের ফলে, শরীরের তাপমাত্রা খুব বেশি হয় – কখনও কখনও তাপমাত্রা ১০৬ – ১০৮°F পর্যন্ত হয়ে যায়।",
    "Use of Water to Mitigate Heat Stress":
        "তাপীয় প্রবাহ কমানোর জন্য জলের ",
    "Use of water": "জল ব্যবহার",
    "Use of Water": "জল ব্যবহার",
    "The most effective way of combating heat stress in buffalo is wallowing in the water pond":
        "গবাদী পশুর তাপীয় প্রবাহ মোকাবেলার সবচেয়ে কার্যকর উপায় হল পশুকে পুকুরের নিয়ে যাওয়া।",
    "Various cooling systems have been developed for evaporative cooling such as holding-pen cooling,exit-lane cooling, and free-stall cooling. These systems are applicable for the animals maintained in covered pucca sheds. An evaporative system which uses water mist with fan is more effective and economises water use in comparison to repeatedly bathing the animals":
        "পশুশালা ঠান্ডা করার জন্য বিভিন্ন শীতলকরণ ব্যবস্থা যেমন হোল্ডিং-পেন কুলিং, এক্সিট-লেন কুলিং এবং ফ্রি-স্টল কুলিং ব্যবহার করা উচিত । এমন একটি বাষ্পীভবনের ব্যবস্থা করতে হবে যা ফ্যান সহ জল মিস্ট ব্যবহার করে তা বারবার প্রাণীকে স্নান করানোর তুলনায় বেশি কার্যকরী হয় এবং এটি জলের ব্যবহার সাশ্রয় করতে সাহায্য করবে।",
    "The buffalo needs at least twice a day bath in the summer. Misting/Fogging of water in the microenvironment of the animal at least thrice in an hour along with provision of fan is useful in hot dry weather. Auto Mister/ Fugger with mini pumps and cyclic timers are preferable":
        "গ্রীষ্মকালে পশুকে দিনে কমপক্ষে দু'বার স্নান করানো দরকার। গরম শুষ্ক আবহাওয়ায় পশুশালায় দিনে কমপক্ষে তিনবার জল মিসটিং/ফগিং করা এবং ফ্যানের ব্যবস্থা রাখা দরকার। ",
    "Heat stress can also be managed by spraying/ sprinkling water directly on the body of animals for a period of 1 to 5 minutes at an interval of 10- 30 minutes. Fans/blowers should be used to induce evaporation from the skin of animals":
        "তাপীয় প্রবাহের সময় প্রাণীদের শরীরে সরাসরি ১ থেকে ৫ মিনিটের জন্য ১০-৩০ মিনিটের ব্যবধানে জল ছিটানো যেতে পারে। প্রাণীদের ত্বক থেকে বাষ্পীভবন তরান্বিতপ্ররোচিত করতে ফ্যান বা ব্লোয়ার ব্যবহার করা উচিত।",
    "Ensure adequate round the clock drinking water to animals, which should be provided under shade":
    "Evaporative cooling systems like holding-pen cooling, exit-lane cooling, and free-stall cooling are applicable in covered sheds. An evaporative system using water mist with fans is more efficient and economizes water compared to bathing.":
        "পশুশালা ঠান্ডা করার জন্য বিভিন্ন শীতলকরণ ব্যবস্থা যেমন হোল্ডিং-পেন কুলিং, এক্সিট-লেন কুলিং এবং ফ্রি-স্টল কুলিং ব্যবহার করা উচিত । এমন একটি বাষ্পীভবনের ব্যবস্থা করতে হবে যা ফ্যান সহ জল মিস্ট ব্যবহার করে তা বারবার প্রাণীকে স্নান করানোর তুলনায় বেশি কার্যকরী হয় এবং এটি জলের ব্যবহার সাশ্রয় করতে সাহায্য করবে।"
    "Buffalo need at least two baths per day in summer. Misting/fogging the microenvironment thrice per hour with fans helps in hot-dry weather. Automatic misters with mini pumps and timers are preferable.":
        "গ্রীষ্মকালে পশুকে দিনে কমপক্ষে দু'বার স্নান করানো দরকার। গরম শুষ্ক আবহাওয়ায় পশুশালায় দিনে কমপক্ষে তিনবার জল মিসটিং/ফগিং করা এবং ফ্যানের ব্যবস্থা রাখা দরকার।"
    "Spraying or sprinkling water directly on animals for 1–5 minutes every 10–30 minutes, combined with fans/blowers, increases evaporative heat loss.":
        "তাপীয় প্রবাহের সময় প্রাণীদের শরীরে সরাসরি ১ থেকে ৫ মিনিটের জন্য ১০-৩০ মিনিটের ব্যবধানে জল ছিটানো যেতে পারে। প্রাণীদের ত্বক থেকে বাষ্পীভবন তরান্বিতপ্ররোচিত করতে ফ্যান বা ব্লোয়ার ব্যবহার করা উচিত।"
    "Ensure round-the-clock access to drinking water under shade.":
        "গোয়ালে পর্যাপ্ত পানীয় জল ২৪ ঘণ্টা নিশ্চিত করা উচিত।"
        "গোয়ালে পর্যাপ্ত পানীয় জল ২৪ ঘণ্টা নিশ্চিত করা উচিত।",
    "Other Heat Stress Management Strategies":
        "অন্যান্য তাপীয় প্রবাহ ব্যবস্থাপনার কৌশলসমূহ",
    "During heat stress conditions buffaloes should not be allowed to move freely during day hours because they need protection against warm air storms, direct sun exposure and they should be provided with shelter in cool and shady places":
        "তাপীয় প্রবাহের সময় গবাদী পশুদের দিনের বেলা মুক্তভাবে চলাফেরা করতে দেওয়া উচিত নয় কারণ তাদের গরম বাতাসের থেকে সুরক্ষা প্রয়োজন, সরাসরি সূর্যালোকের সংস্পর্শে না থাকা এবং শীতল এবং ছায়াময় জায়গায় আশ্রয় দেওয়া উচিত।",
    "The most effective source of shade is trees. They provide not only protection from sunlight, but also create a cooling effect through the evaporation of moisture from their leaves":
        "ছায়ার সবচেয়ে কার্যকর উৎস হল গাছ। তারা কেবল সূর্যালোক থেকে সুরক্ষা প্রদান করে না, তাদের পাতা থেকে আর্দ্রতার বাষ্পীভবনের মাধ্যমে শীতল প্রভাবও তৈরি করে।",
    "Shade trees provide protection and cooling via moisture evaporation from leaves.":
        "ছায়াদার গাছ পাতার আর্দ্রতা বাষ্পীভবনের মাধ্যমে সুরক্ষা ও শীতলতা প্রদান করে।"
    "If shade trees are not available, thatched roof of a minimum height of 9 feet should be provided. Agri-nets with 20% perforation are also useful. If facilities are not available with the individual farmers, facilities available at the village shall be used by the community. Materials like paddy straw etc,painting the roof with white paint or,providing a false ceiling insulation will help provide a cooler environment. Create barriers against hot wind using thatched wall or wet gunny cloth/ gunny bags":
        "ছায়া প্রদানকারী গাছ না থাকলে, কমপক্ষে ৯ ফুট উচ্চতার খড়ের ছাদ প্রদান করা উচিত। ২০% ছিদ্রযুক্ত জাল ও খুব কার্যকরী। ছাদে খড়, সাদা রঙ বা কৃত্রিম ছাদের আস্তরণ, গরমের প্রভাব কমাতে সাহায্য করে। গবাদী পশুকে গরম হাওয়া থেকে বাঁচাতে চটের বস্তাকে ভিজিয়ে দেওয়ালে টাঙ্গিয়ে রাখা উচিৎ। ",
    "If trees are unavailable, a thatched roof of at least 9 feet is useful. Agri-nets (20% perforation), white-painted roofs, false ceiling insulation, or barriers (thatched walls or wet gunny cloth) help create cooler environments.":
        "যদি গাছ না থাকে, অন্তত ৯ ফুট খড়ের ছাউনি ব্যবহার করতে হবে। ২০% ছিদ্রের এগ্রি-নেট, সাদা রঙ করা ছাদ, নকল সিলিং ইনসুলেশন বা খড়ের দেয়াল/ভেজা বস্তার ব্যারিয়ার শীতল পরিবেশ তৈরিতে সহায়তা করে।"
    "The buffalo shed should be well ventilated that the polluted air can directly diffused outside and clean and fresh air can enter into it. Ensure one ventilator of 3 x 1 feet per cow in covered shed. In these sheds heavy duty fan is best option to facilitate ventilation":
        "পশুশালার ছাউনি ভালোভাবে বাতাস চলাচলের উপযোগী হওয়া উচিৎ, যাতে দূষিত বায়ু সরাসরি বাইরে বেরিয়ে যেতে পারে এবং পরিষ্কার ও তাজা হাওয়া ভিতরে প্রবেশ করতে পারে। গরমকালে বড় বড় ফ্যান চালিয়ে হাওয়া চলাচলের প্রবাহকে তরান্বিত করা যেতে পারে। ",
    "Sheds should be well-ventilated so polluted air exits and fresh air enters. Provide one 3x1 ft ventilator per cow in covered sheds; heavy-duty fans aid ventilation.":
        "শেডগুলি ভালোভাবে বায়ুচলাচল হওয়া উচিত যাতে দূষিত বাতাস বের হয়ে যায় এবং টাটকা বাতাস প্রবেশ করতে পারে। ঢাকা শেডে প্রতি গরুর জন্য একটি 3x1 ফুট ভেন্টিলেটর দিন; শক্তিশালী ফ্যান বায়ু চলাচলে সহায়তা করে।"
    "The proper plantation should be managed in surroundings so that the environment may be cool and fresh and warm air storm could not enter directly in the shed":
        "পশুশালার আশেপাশে বেশি পরিমাণে গাছ লাগানো উচিৎ যাতে পরিবেশ ঠাণ্ডা ও তাজা থাকে এবং গরম হাওয়া সরাসরি ভিতরে প্রবেশ না করে। ",
    "Air movement: Air movement is more important during hot-humid climate for providing cooling and comfort to the animal. Air movement increases the rate of heat loss from animals body surface, only as long as the air temperature is lower than the animals skin temperature":
        "গরম আর্দ্র আবহাওয়ায় শীতলতা এবং আরাম প্রদানের জন্য হাওয়া চলাচল খুবই গুরুত্বপূর্ণ, হাওয়া চলাচল গবাদী পশুর শরীরের উপর থেকে তাপ বিকিরণের হারকে ত্বরান্বিত করে। ",
    "Air movement is crucial in hot-humid climates for cooling; it increases heat loss if air temperature is below skin temperature.":
        "গরম-আর্দ্র আবহাওয়ায় ঠান্ডার জন্য বাতাসের চলাচল অত্যন্ত গুরুত্বপূর্ণ; যদি বাতাসের তাপমাত্রা ত্বকের নিচে থাকে তবে এটি তাপ ক্ষয় বাড়ায়।"
    "Feeding should be practiced during early morning, evening and at night":
    "Feed during early morning, evening, and night to avoid heat peaks.":
        "তাপমাত্রা বাড়ার সময় এড়াতে ভোর, সন্ধ্যা ও রাতে চারা দিন।"
    "Prefer grazing in early morning and late evening when temperatures are lower.":
        "তাপমাত্রা কম থাকলে ভোর ও গোধূলিতে চারণে অগ্রাধিকার দিন।"
    "Increase ration density to deliver nutrients with reduced dry matter intake. Low-fibre, high-fermentable carbohydrate diets produce lower dietary heat increment.":
        "কম শুষ্ক পদার্থ খাইয়ে প্রয়োজনীয় পুষ্টি দিতে রেশন ঘনত্ব বাড়ান। কম ফাইবার ও বেশি গাঁজনশীল কার্বোহাইড্রেট খাদ্য কম তাপ উত্পাদন করে।"
    "Provide increased mineral supplementation during heat; potassium-rich mineral mixtures are preferred.":
        "গরমে খনিজের পরিমাণ বাড়ান; পটাশিয়াম সমৃদ্ধ মিশ্রণই উত্তম।"
        "গরমের প্রবাহ থেকে বাঁচাতে পশুকে ভোরবেলা, সন্ধ্যে ও রাতে খাওয়ানো উচিৎ এবং সকাল ও সন্ধ্যেবেলার দিকে চরাতে নিয়ে যাওয়া উচিৎ। ",
    "Prefer grazing during early morning and late evening hours to avoid the heat stress":
        "তাপের চাপ এড়াতে ভোরবেলা এবং সন্ধ্যার সময় চারণকে পছন্দ করুন",
    "Ration density may be increased so as to provide same nutrients at reduced dry matter intake. Diets with low-fibre and high fermentable carbohydrate have lower dietary heat increment compared to high fibre diets":
        "গ্রীষ্মকালে দানার পরিমাণ বাড়ানো উচিৎ। কম ফাইবার এবং উচ্চ পচনশীল খাবার দেওয়া উচিৎ যাতে খাওয়ার পর শরীরে কম তাপমাত্রা বৃদ্ধি হয়।",
    "Ensure increased mineral supplementation during hot weather to meet the increased demand of minerals. Potassium rich mineral mixture should be preferred":
        "খনিজগুলির বর্ধিত চাহিদা মেটাতে গরম আবহাওয়ায় খনিজ পরিপূরক বৃদ্ধি নিশ্চিত করুন। গ্রীষ্মকালে পটাশিয়াম যুক্ত খনিজ মিশ্রণ দেওয়া যেতে পারে।  ",
    "Managing Cold Stress": "শীতল প্রবাহ ব্যবস্থাপনা",
    "Monitor weather conditions and act accordingly. Monitor temperature changes and provide more feed to animals in colder weather conditions":
    "Monitor weather conditions and provide extra feed during colder temperatures.":
        "আবহাওয়া পর্যবেক্ষণ করুন এবং ঠান্ডায় বাড়তি খাদ্য দিন।"
        "আবহাওয়ার পরিস্থিতি পর্যবেক্ষণ করুন এবং সেই অনুযায়ী কাজ করুন। তাপমাত্রার পরিবর্তনগুলি পর্যবেক্ষণ করুন এবং ঠান্ডা আবহাওয়ার পরিস্থিতিতে প্রাণীদের আরও বেশি খাবার সরবরাহ করুন।",
    "Ensure there is enough shelter from the wind. Effects of cold stress increase when wind speed increases. Any kind of available protection, whether it is natural (bush, valley bottoms or hillsides) or man-made (such as simple windbreak fences or shelters) can be highly valuable in helping animals cope with extreme temperatures and wind-chill effects":
    "Ensure windbreaks or shelters to protect animals from cold winds; natural bushes or simple fences can be effective.":
        "ঠান্ডা বাতাস থেকে রক্ষায় উইন্ডব্রেক বা আশ্রয় নিশ্চিত করুন; প্রাকৃতিক ঝোপ বা সাধারণ বেড়া কার্যকর হতে পারে।"
        "ঠাণ্ডা হাওয়া থেকে রক্ষা করার জন্য উপযুক্ত খড়ের ব্যবস্থা করতে হবে। শীতের প্রভাব হাওয়ার গতির সাথে সাথে বাড়তে থাকে। সেইজন্য গরু এবং মহিষকে তীব্র ঠাণ্ডা থেকে বাঁচানোর জন্য উপযুক্ত সুরক্ষা ব্যবস্থা করতে হবে। ",
    "Provide bedding to help keep animal clean and dry. Bedding, such as barley straw, helps to withstand cold stress":
        "গবাদী পশুকে শুষ্ক এবং পরিষ্কার বিছানা দিন। বালি এবং খড়ের মতো বিছানা শীত প্রবাহ কম করতে সাহায্য করে। ",
    "Provide bedding, such as straw, to keep animals clean and dry and help them withstand cold stress.":
        "জন্তুদের পরিষ্কার ও শুকনো রাখতে এবং ঠান্ডা চাপ সহ্য করতে খড় ইত্যাদি বিছান দিন।"
    "Increase grain and hay when temperatures drop below the lower critical threshold.":
        "তাপমাত্রা নিম্নসীমার নিচে নেমে গেলে শস্য ও ঘাস বাড়ান।"
    "Provide additional feed. Increase grain and hay for when temperatures drop below the lower critical threshold level":
        "যখন নিম্ন তাপমাত্রা সহনশীল তাপমাত্রার নীচে নেমে যায় তখন গরু এবং মহিষকে অতিরিক্ত দানা এবং খড় প্রদান করুন।",
    "Provide water. Make sure animals have ample water available at all times. A limit in water available will limit feed intake and make it more difficult for animal to meet their energy requirements. Excessively cold water can severely limit water intake":
    "Ensure ample water is available; warm water may be necessary to encourage intake, as cold water can limit consumption.":
        "পর্যাপ্ত পানি নিশ্চিত করুন; ঠান্ডা পানি খাওয়া কমাতে পারে, তাই প্রয়োজনে গরম পানি দিন।"
        "গবাদী পশুকে পর্যাপ্ত পরিমাণে জল দিন। তীব্র ঠাণ্ডার সময় গবাদী পশু কম জল খায় সেইজন্য হালকা গরম জল দেওয়া যেতে পারে। "
  })
  ..addAll({
    'Climate Change and Dairy Farming': 'জলবায়ু পরিবর্তন এবং দুগ্ধ চাষ',
    'Heat Stress': 'তাপ প্রবাহ',
    'Increased temperatures in India can cause severe heat stress in dairy animals. Studies show that heat stress can reduce milk production by 10-25% in cows and buffaloes during peak summer months.':
        'তাপমাত্রা বৃদ্ধির ফলে গরু ও মহিষের উপর মারাত্মক প্রভাব পড়তে পারে। গবেষণায় দেখা গেছে যে চরম গ্রীষ্মের মাসগুলিতে তাপ প্রবাহ গরু ও মহিষের দুধ উৎপাদন ১০-২৫% কমিয়ে দিতে পারে।',
    'Reproductive Health': 'প্রজনন স্বাস্থ্য',
    'Heat stress impacts reproductive efficiency. Research indicates that conception rates in dairy cows can drop by up to 30% during heat waves. In buffaloes, silent heat and low conception rates during summer are serious problems in northern India. In males, the semen quality and libido also get affected by heat stress.':
        'তাপ প্রবাহ প্রজনন দক্ষতাকে প্রভাবিত করে। গবেষণায় দেখা গেছে যে চরম তাপ প্রবাহের সময় গরু ও মহিষের গর্ভধারণের হার ৩০% পর্যন্ত কমে যেতে পারে। মহিষের ক্ষেত্রে, গ্রীষ্মে, নীরব ঋতুস্রাব এবং কম গর্ভধারণের হার উত্তর ভারতে একটি গুরুতর সমস্যা। পুরুষদের ক্ষেত্রে, তাপ প্রবাহের ফলে বীর্যের গুণমান এবং যৌন চাহিদাও প্রভাবিত হয়।',
    'Milk Composition': 'দুধের উপাদান',
    'Heat stress can reduce the fat and protein content in milk. Studies have shown that in heat-stressed cows, the fat content of milk can drop by 0.2-0.5 percentage points.':
        'তাপ প্রবাহ দুধের চর্বি এবং প্রোটিনের পরিমাণ কমিয়ে দিতে পারে। গবেষণায় দেখা গেছে যে গরুর দুধে চর্বির পরিমাণ ০.২-০.৫ শতাংশ পয়েন্ট কমে যেতে পারে।',
    'Feed Quality and Quantity': 'গবাদি পশুর খাদ্যের গুণমান এবং পরিমাণ',
    'Climate change can lead to altered rainfall patterns and more frequent droughts, affecting the availability and quality of fodder. Poor fodder quality can lead to lower milk production and increased costs for dairy farmers.':
        'জলবায়ু পরিবর্তন বৃষ্টির প্যাটার্ন পরিবর্তন করতে পারে এবং আরও ঘন ঘন খরা সৃষ্টি করতে পারে, যা চারণভূমির প্রাপ্যতা এবং গুণমানকে প্রভাবিত করে। খারাপ চারণভূমির গুণমান কম দুধ উৎপাদন এবং কৃষকদের জন্য বাড়তি খরচ সৃষ্টি করতে পারে।',
    'Disease and Parasites': 'রোগ ও পরজীবী',
    'Higher temperatures and humidity levels can lead to an increase in vector-borne diseases such as tick-borne diseases. The incidence of diseases like mastitis, Foot and Mouth Disease (FMD) can rise, affecting productivity.':
        'উচ্চ তাপমাত্রা এবং আর্দ্রতার মাত্রা ভেক্টর-জনিত রোগ যেমন পোকা ও মাকড়-জনিত রোগের বৃদ্ধি ঘটাতে পারে। স্তনদাহ, পা ও মুখের রোগ (খুরাই বা এফএমডি) এর মতো রোগের সংখ্যা বাড়তে পারে, যা উৎপাদনশীলতাকে প্রভাবিত করে।',
    'Animal Welfare': 'পশুর আরাম',
    'Increased temperatures and humidity negatively affect animal welfare, causing stress and discomfort. This can lead to increased mortality rates during extreme heat events.':
        'উচ্চ তাপমাত্রা এবং আর্দ্রতা পশুর আরামে ব্যাঘাত সৃষ্টি করে, যা তাদের স্বাস্থ্যের ক্ষতি ও অস্বস্তির কারণ হতে পারে। এটি চরম তাপ প্রবাহের সময় মৃত্যুর হার বাড়াতে পারে।',
    'Adaptation Costs': 'অভিযোজন খরচ',
    'Farmers may need to invest in cooling systems, improved housing, and changes in management practices. The cost of installing fans, sprinklers, and cooling pads can be substantial, often ranging from INR 20,000 to 50,000 per animal shed.':
        'কৃষকদের কুলিং সিস্টেম, উন্নত আবাসন এবং ব্যবস্থাপনা পদ্ধতিতে পরিবর্তনের জন্য বিনিয়োগ করতে হতে পারে। ফ্যান, স্প্রিংকলার এবং কুলিং প্যাড লাগানোর খরচ যথেষ্ট হতে পারে, প্রায়ই পশুর শেড প্রতি 20,000 থেকে 50,000 টাকা পর্যন্ত হতে পারে।',
    'Biodiversity Loss': 'জীববৈচিত্র্যের ক্ষতি',
    'Climate change impacts the biodiversity of pasturelands. Loss of plant species reduces the variety of feed available, impacting the nutritional intake of dairy animals.':
        'জলবায়ু পরিবর্তন চারণভূমির জীববৈচিত্র্যকে প্রভাবিত করে। উদ্ভিদ প্রজাতির ক্ষতি খাদ্যের বৈচিত্র্য কমিয়ে দেয় এবং শেষ পর্যন্ত প্রাণীর খাদ্যের পুষ্টির গুণমানকে প্রভাবিত করে।',
    'Economic Impact on Farmers': 'কৃষকদের ওপর অর্থনৈতিক প্রভাব',
    'The cumulative effect of reduced milk production, increased costs for feed, water, and veterinary care, and potential loss of livestock due to extreme weather events can significantly affect the livelihood of dairy farmers.':
        'দুধ উৎপাদন কমে যাওয়া, বেড়ে যাওয়া খাদ্যের এবং পশুচিকিৎসার খরচ, এবং চরম আবহাওয়া কারণে পশু মৃত্যু সম্ভাবনার সামগ্রিক প্রভাব কৃষকদের আয়ের ওপর উল্লেখযোগ্যভাবে প্রভাব ফেলতে পারে।',
  })..addAll({
'January': 'জানুয়ারি',
  'February': 'ফেব্রুয়ারি',
  'March': 'মার্চ',
  'April': 'এপ্রিল',
  'May': 'মে',
  'June': 'জুন',
  'July': 'জুলাই',
  'August': 'আগস্ট',
  'September': 'সেপ্টেম্বর',
  'October': 'অক্টোবর',
  'November': 'নভেম্বর',
  'December': 'ডিসেম্বর',
  })..addAll({
    'Full Name': 'পুরো নাম',
    'Enter your Full Name': 'আপনার পুরো নাম লিখুন',
    'Email ID': 'ইমেইল আইডি',
    'Mobile Number': 'মোবাইল নম্বর',
    'Register': 'নিবন্ধন করুন',
    'Already Have Account - ': 'ইতিমধ্যে অ্যাকাউন্ট আছে - ',
    'Login': 'লগইন করুন',
    'Send OTP': 'OTP পাঠান',
    'Skip': 'এড়িয়ে যান',
    'Enter OTP': 'OTP লিখুন',
    'Please Enter Something': 'অনুগ্রহ করে কিছু লিখুন',
    'FeedBack Submitted Successfully!': 'মতামত সফলভাবে জমা হয়েছে!',
    'Notification': 'বিজ্ঞপ্তি',
    'OK': 'ঠিক আছে',
    'Enter your Mobile Number': 'আপনার মোবাইল নম্বর লিখুন',
    'Enter your Email Id': 'আপনার ইমেইল আইডি লিখুন',
    'Select State & District': 'রাজ্য ও জেলা নির্বাচন করুন',
    'Filter': 'ফিল্টার',
    'Remove Filter': 'ফিল্টার অপসারণ করুন',
    'Select Location & Language': 'অবস্থান ও ভাষা নির্বাচন করুন',
    'Last updated:': 'সর্বশেষ আপডেট:',
    'State': 'রাজ্য',
    'Already Have Accounts - ': 'ইতিমধ্যে অ্যাকাউন্ট আছে - '
})..addAll({
    'Ration Formulation for a lactating buffalo with body weight 450-500 Kg) during heat stress season': 'তাপ চাপের মৌসুমে দুগ্ধবতী মহিষের (শরীরের ওজন 450-500 কেজি) জন্য রেশন ফর্মুলেশন',
    'Ration ingredient': 'রেশন উপাদান',
    'Milk Yield': 'দুধের উৎপাদন',
    'Kg': 'কেজি',
    'Green Fodder (Maize/Jowar)': 'সবুজ ঘাস (ভুট্টা/জোয়ার)',
    'Dry fodder (straw/Maize Stover)': 'শুকনো ঘাস (খড়/ভুট্টার ডাঁটা)',
    'Grain (Maize/Jowar)': 'শস্য (ভুট্টা/জোয়ার)',
    'Concentrate mixture*': 'ঘনীভূত মিশ্রণ*',
    '*Concentrate mixture formulation': '*ঘনীভূত মিশ্রণ ফর্মুলেশন',
    'Ingredients': 'উপাদান',
    'Formulation': 'ফর্মুলেশন',
    'Maize/Jowar/ wheat/ rice/oats admixture': 'ভুট্টা/জোয়ার/গম/চাল/ওট মিশ্রণ',
    'Jowar': 'জোয়ার',
    'Rice bran (deoiled)': 'চালের ভুসি (তেলমুক্ত)',
    'Wheat bran (deoiled)': 'গমের ভুসি (তেলমুক্ত)',
    'Groundnut cake': 'চীনাবাদামের খৈল',
    'Soyabean cake': 'সয়াবিন খৈল',
    'Mustard cake': 'সরিষার খৈল',
    'Cotton seed cake (decorticated)': 'তুলা বীজের খৈল (খোসামুক্ত)',
    'Cotton seed cake (undecorticated)': 'তুলা বীজের খৈল (খোসাসহ)',
    'Mineral mixture': 'খনিজ মিশ্রণ',
    'Salt': 'লবণ',
    'Total': 'মোট',
    'Note': 'নোট',
    'Provide additional 1.5 – 2 kg concentrate mixture during heat stress season': 'তাপ চাপের মৌসুমে অতিরিক্ত 1.5 - 2 কেজি ঘনীভূত মিশ্রণ প্রদান করুন',
    'Provide additional 1 kg of concentrate mixture per 2.5 litre of milk production beyond 10/15 kg of milk production': '10/15 কেজি দুধ উৎপাদনের বাইরে প্রতি 2.5 লিটার দুধ উৎপাদনের জন্য অতিরিক্ত 1 কেজি ঘনীভূত মিশ্রণ প্রদান করুন',
    'Provide 500 gm of grain or 2.5 Kg cereal fodder for every 50 Kg increase in body weight beyond 500 Kg': '500 কেজির বেশি শরীরের ওজন বৃদ্ধির প্রতি 50 কেজির জন্য 500 গ্রাম শস্য বা 2.5 কেজি শস্যের ঘাস প্রদান করুন',
    'Due to the dry weather, farmers can irrigate the moong crop as per the crop requirement. Weeds are a big problem during the first 4-5 weeks of sowing. Therefore, weeding should be done within 15-20 days of sowing.':
    'শুষ্ক আবহাওয়ার সম্ভাবনা থাকায়, কৃষকরা ফসলের চাহিদা অনুযায়ী মুগ ফসলে সেচ দিতে পারেন। বীজ বপনের প্রথম ৪-৫ সপ্তাহে আগাছার সমস্যা বেশি দেখা যায়। তাই, বপনের ১৫-২০ দিনের মধ্যে আগাছা পরিষ্কার করা উচিত।',
})..addAll({
'The National Dairy Research Institute, Karnal, India is a Deemed University under the Indian Council of Agricultural Research of the Ministry of Agriculture and Farmers Welfare, Government of India. The premier ‘Research Institute’ of India in the field of dairy, the National Dairy Research Institute has developed considerable expertise over the last five decades in different areas of Dairy Production, Processing, Management and Human Resource Development.':'রাষ্ট্রীয় ডেরি অনুসন্ধান সংস্থান (এনডিআরআই), কার্নাল হল ভারত সরকারের কৃষি ও কৃষক কল্যাণ মন্ত্রকের অধীনে ভারতীয় কৃষি অনুসন্ধান পরিষদের একটি মান্য বিশ্ববিদ্যালয়।  ভারতে দুগ্ধ ক্ষেত্রে শীর্ষস্থানীয় `গবেষণা প্রতিষ্ঠান` হিসাবে, রাষ্ট্রীয় ডেরি অনুসন্ধান সংস্থান গত পাঁচ দশকে দুগ্ধ উৎপাদন, প্রক্রিয়াকরণ, ব্যবস্থাপনা এবং মানব সম্পদ উন্নয়নের বিভিন্ন ক্ষেত্রে উল্লেখযোগ্য দক্ষতা অর্জন করেছে। ',
  'Being the National Institute, it conducts basic and applied research with the objective to enhance animal productivity and also to develop cost-effective technologies for the benefit of the millions of the farming community. The Institute has had been continuously working to develop its research and developed as well as human resource development programmes to better serve the nation in terms of food security, employment generation, poverty alleviation and economic prosperity.':'জাতীয় প্রতিষ্ঠান হিসেবে এটি গবাদী পশুর উৎপাদনশীলতা বৃদ্ধির উদ্দেশ্যে ও লক্ষ লক্ষ কৃষক সম্প্রদায়ের সুবিধার জন্য এবং উন্নয়নের উদ্দেশ্যে মৌলিক ও প্রয়োগ মুলক গবেষণা করে। প্রতিষ্ঠানটি তার গবেষণা ও উন্নয়ন কর্মসূচি এবং মানব সম্পদ উন্নয়ন কর্মসূচি উন্নত করতে ক্রমাগত কাজ করে আসছে যাতে খাদ্য নিরাপত্তা, কর্মসংস্থান সৃষ্টি, দারিদ্র্য বিমোচন এবং অর্থনৈতিক সমৃদ্ধির ক্ষেত্রে দেশকে আরও ভালোভাবে সেবা প্রদান করতে পারে।'
});
