Map<String, String> pbi = {
  'Dairy Animal and Climate Change': 'ਡੇਰੀ  ਪਸ਼ੂ ਅਤੇ ਮੌਸਮੀ ਤਬਦੀਲੀ',
  'NDRI Climate Services': 'ਰਾਸ਼ਟਰੀ ਡੇਰੀ ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ ਜਲਵਾਯੂ ਸੇਵਾਵਾਂ',
  'An effort by ICAR-National Dairy Research Institute, Karnal to promote climate resilient Murrah buffalo rearing practices':
      'ਭਾਰਤੀ ਕ੍ਰਿਸ਼ੀ ਅਨੁਸੰਧਾਨ ਪਰਿਸ਼ਦ -ਰਾਸ਼ਟਰੀ ਡੇਰੀ ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ, ਕਰਨਾਲ ਦੁਆਰਾ ਮੌਸਮੀ ਲਚੀਲੇ ਮੁਰਰ੍ਹਾ ਮੱਝ ਪਾਲਣ ਦੀਆਂ ਤਕਨੀਕਾਂ ਨੂੰ ਪ੍ਰਚਾਰਿਤ ਕਰਨ ਦਾ ਇੱਕ ਯਤਨ',
  'Climate Resilient Dairy Farming practices': 'ਮੌਸਮ ਅਨੁਕੂਲ ਡੇਰੀ  ਖੇਤੀ ਅਭਿਆਸ',
  'Climate services by ICAR-National Dairy Research Institute (NDRI), Karnal':
      'ICAR-ਰਾਸ਼ਟਰੀ ਡੇਰੀ  ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ(NDRI),, ਕਰਨਾਲ ਦੁਆਰਾ ਮੌਸਮ ਸੇਵਾਵਾਂ',
  'Murrah Buffalo': 'ਮੁਰਰਾ ਮੱਝ',
  'Cattle': 'ਪਸ਼ੂ',
  'Dairy Animal': 'ਡੇਰੀ  ਪਸ਼ੂ',
  'Home': 'ਘਰ',
  'Enter Your Name:': 'ਆਪਣਾ ਨਾਮ ਦਾਖਲ ਕਰੋ:',
  'Phone Number': 'ਫੋਨ ਨੰਬਰ',
  'Enter Your Phone number': 'ਆਪਣਾ ਫੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ',
  'Enter Your District': 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਦਾਖਲ ਕਰੋ',
  'FeedBack/Message': 'ਫੀਡਬੈਕ/ਸੁਨੇਹਾ',
  'Write your Feedback here': 'ਇੱਥੇ ਆਪਣੀ ਫੀਡਬੈਕ ਲਿਖੋ',
  'Feedback': 'ਫੀਡਬੈਕ',
  'Dashboard': 'ਡੈਸ਼ਬੋਰਡ',
  'Daily forecast': 'ਰੋਜ਼ਾਨਾ ਭਵਿੱਖਬਾਣੀ',
  'Climate Advisory': 'ਮੌਸਮ ਸਲਾਹ',
  'Past advisories': 'ਪਿਛਲੀਆਂ ਸਲਾਹਾਂ',
  'Location': '',
  'Language': 'ਭਾਸ਼ਾ',
  'Distt': 'ਜ਼ਿਲ੍ਹਾ',
  'Weekly Weather Forecast': 'ਸਪਤਾਹਿਕ ਮੌਸਮ ਭਵਿੱਖਬਾਣੀ',
  'Period': 'ਅਵਧੀ',
  'Tmax': 'ਉੱਚਤਮ  ਤਾਪਮਾਨ',
  'Tmin': 'ਨਿਊਨਤਮ  ਤਾਪਮਾਨ',
  'Rainfall(mm)': "ਮੀਂਹ  (ਮਿਲੀਮੀਟਰ)",
  'RH(%)': 'ਸੰਬੰਧਿਤ ਨਮੀ (%)',
  'Wind Speed(kmph)': 'ਹਵਾ ਦੀ ਰਫਤਾਰ (ਕਿਲੋਮੀਟਰ ਪ੍ਰਤੀ ਘੰਟਾ)',
  'Wind Direction (Degree)': 'ਹਵਾ ਦੀ ਦਿਸ਼ਾ (ਡਿਗਰੀ)',
  'Cloud cover(octa)': 'ਬੱਦਲਾਂ ਦੀ ਢੱਕਣ (ਆਕਟਾ)',
  'THI': 'ਤਾਪਮਾਨ-ਨਮੀ ਸੂਚਕ ',
  'Climate services for the period of ': 'ਮੌਸਮ ਸੇਵਾਵਾਂ ਦੀ ਅਵਧੀ ਲਈ  ',
  'Major crops': 'ਮੁੱਖ ਫਸਲਾਂ',
  'Climate Services For Murrah Buffalo': 'ਮੁਰਰਾ ਮੱਝਾਂ  ਲਈ ਮੌਸਮ ਸੇਵਾਵਾਂ',
  'Date': 'ਮਿਤੀ',
  'WEATHER SUMMARY': 'ਮੌਸਮ ਸਾਰ',
  'ADVISORY SERVICES FOR DAIRY ANIMALS': 'ਡੇਰੀ  ਪਸ਼ੂਆਂ ਲਈ ਸਲਾਹਕਾਰੀ ਸੇਵਾਵਾਂ',
  'ADVISORY SERVICES FOR MAJOR CROPS': 'ਮੁੱਖ ਫਸਲਾਂ ਲਈ ਸਲਾਹਕਾਰੀ ਸੇਵਾਵਾਂ',
  'Impact of climate change on dairy animal':
      'ਡੇਰੀ  ਪਸ਼ੂਆਂ `ਤੇ ਮੌਸਮੀ ਤਬਦੀਲੀ ਦਾ ਅਸਰ',
  'Climate services': 'ਮੌਸਮ ਸੇਵਾਵਾਂ',
  'Feedback/Raise Your Question': 'ਫੀਡਬੈਕ/ਸਵਾਲ ਲਿਖੋ',
  'Name': 'ਨਾਮ',
  'District': 'ਜ਼ਿਲ੍ਹਾ',
  'Mobile Number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
  'Type feedback/Question': 'ਪ੍ਰਤੀਕਿਰਿਆ/ਪ੍ਰਸ਼ਨ ਟਾਈਪ ਕਰੋ',
  'Submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
  'About Murrah Buffalo': 'ਮੁਰਰਾ ਮੱਝ ਬਾਰੇ',
  'Feeding Management': 'ਖੁਰਾਕ ਪ੍ਰਬੰਧ',
  'Fodder Management': 'ਚਾਰਾ ਪ੍ਰਬੰਧਨ',
  'Health Care Management': 'ਸਿਹਤ ਪ੍ਰਬੰਧ',
  'Management Practices': 'ਪ੍ਰਬੰਧ ਅਭਿਆਸ',
  'Thermal Stress Management': 'ਤਾਪਮਾਨ ਤਣਾਅ ਪ੍ਰਬੰਧਨ',
  'Weather Forecast': 'ਮੌਸਮ ਭਵਿੱਖਬਾਣੀ',
  'Temperature Maximum': 'ਉੱਚਤਮ  ਤਾਪਮਾਨ',
  'Temperature Minimum': 'ਨਿਊਨਤਮ  ਤਾਪਮਾਨ',
  'Temperature Humidity Index': 'ਤਾਪਮਾਨ ਨਮੀ ਸੂਚਕਾਂਕ',
  'About NDRI, Karnal': 'ਰਾਸ਼ਟਰੀ ਡੇਰੀ  ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ, ਕਰਨਾਲ ਬਾਰੇ',
  'NDRI, Karnal': 'ਰਾਸ਼ਟਰੀ ਡੇਰੀ  ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ, ਕਰਨਾਲ',
  'About App': 'ਐਪ ਬਾਰੇ',
  'Climate Resilient Practices': 'ਜਲਵਾਯੂ ਲਚੀਲਾ ਅਭਿਆਸ',
  'Climate Resillient Murrah Buffalo Rearing practices':
      'ਜਲਵਾਯੂ ਲਚੀਲਾ ਮੁਰਰਾ ਮੱਝ ਪਾਲਣ ਅਭਿਆਸ',
  'Climate Resillient Cattle Rearing practices': 'ਜਲਵਾਯੂ ਲਚੀਲਾ ਪਸ਼ੂ ਪਾਲਣ ਅਭਿਆਸ',
  'Sign out': 'ਸਾਈਨ ਆਉਟ',
  'Select Language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
  'Select State': 'ਰਾਜ ਚੁਣੋ',
  'Select District': 'ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
  'Please Select One': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਚੁਣੋ',
  'English': 'ਅੰਗਰੇਜ਼ੀ',
  'Hindi': 'ਹਿੰਦੀ',
  'Punjabi':'ਪੰਜਾਬੀ',
  'Bengali':'ਬੰਗਾਲੀ',
  'Type your District': 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਟਾਈਪ ਕਰੋ',
  'Type your State': 'ਆਪਣਾ ਰਾਜ ਟਾਈਪ ਕਰੋ',
  'Necess of feeding Management in Summer and Winter':
      'ਗਰਮੀ ਅਤੇ ਸਰਦੀ ਵਿੱਚ ਖੁਰਾਕ ਪ੍ਰਬੰਧ ਦੀ ਲੋੜ',
  'In Winters': 'ਸਰਦੀ ਦੇ ਮੌਸਮ ਵਿੱਚ',
  'In Summers': 'ਗਰਮੀ ਦੇ ਮੌਸਮ ਵਿੱਚ',
  'Necessity': 'ਲੋੜ',
  'Climate Smart Practices': 'ਜਲਵਾਯੂ ਸਮਾਰਟ ਅਭਿਆਸ',
  'Temperature and humidity during April to middle of September are the cause of heat stress of the livestock. This heat stress results from the animal’s inability to dissipate sufficient heat to maintain its body temperature.':
      'ਅਪ੍ਰੈਲ ਤੋਂ ਸਤੰਬਰ ਦੇ ਮੱਧ ਤੱਕ ਤਾਪਮਾਨ ਅਤੇ ਨਮੀ ਗਰਮੀ ਪਸ਼ੂਆਂ ਦੇ ਤਣਾਅ ਦਾ ਕਾਰਨ ਹਨ। ਕਾਫੀ ਗਰਮੀ ਵਿਚ ਜਾਨਵਰਾਂ ਦੁਆਰਾ ਸਰੀਰ ਦੇ ਤਾਪਮਾਨ ਦੇ ਫੈਲਣ ਦੀ ਅਯੋਗਤਾ ਦਾ ਨਤੀਜਾ ਇਹ ਗਰਮੀ ਦਾ ਤਣਾਅ ਹੈ।',
  'High ambient temperature, relative humidity and radiant energy compromise the ability of animals to dissipate heat.':
      'ਜਾਨਵਰਾਂ ਦੀ ਗਰਮੀ ਨੂੰ ਦੂਰ ਕਰਨ ਦੀ ਸਮਰੱਥਾ ਵਿਚ ਵਾਤਾਵਰਣ ਦਾ ਉੱਚ ਤਾਪਮਾਨ, ਨਮੀ ਅਤੇ ਚਮਕਦਾਰ ਊਰਜਾ ਨਾਲ ਸ਼ਾਮਲ ਹੁੰਦਾ ਹੈ।',
  'Therefore, it increases in body temperature and reduces in productive performance particularly in milk production. This decrease can be either transitory or long term depending on the length and severity of heat stress.':
      'ਇਸ ਲਈ, ਇਹ ਸਰੀਰ ਦੇ ਤਾਪਮਾਨ ਵਿੱਚ ਵਾਧਾ ਕਰਦਾ ਹੈ ਅਤੇ ਉਤਪਾਦਕਤਾ ਵਿੱਚ ਕਮੀ ਕਰਦਾ ਹੈ ਖਾਸ ਕਰਕੇ ਦੁੱਧ ਦੇ ਉਤਪਾਦਨ ਵਿੱਚ। ਇਹ ਕਮੀ ਜਾਂ ਤਾਂ ਅਸਥਾਈ ਜਾਂ ਲੰਬੇ ਸਮੇਂ ਲਈ ਹੋ ਸਕਦੀ ਹੈ ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੀ ਲੰਬਾਈ ਅਤੇ ਤੀਬਰਤਾ `ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ।',
  'The decrease in milk production may ranges from 10 to 25%. Therefore, it is utmost necessary to manage feeding practices during summer to alleviate heat stress of the dairy animals.':
      'ਦੁੱਧ ਦੇ ਉਤਪਾਦਨ ਵਿੱਚ ਕਮੀ 10 ਤੋਂ 25% ਤੱਕ ਹੋ ਸਕਦੀ ਹੈ। ਇਸ ਲਈ, ਡੇਰੀ ਜਾਨਵਰਾਂ ਵਿਚ ਗਰਮੀ ਦੇ ਤਣਾਅ ਨੂੰ ਘੱਟ ਕਰਨ ਲਈ ਗਰਮੀਆਂ ਦੌਰਾਨ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨਾ ਸਭ ਤੋਂ ਵੱਧ ਜ਼ਰੂਰੀ ਹੈ।',
  'During winter season many animals often refuse to eat, become feverish and pneumonitic which in turn affects the milk production, health and reproduction of the animal. Severe cold surroundings result in increased energy loss, which has to be compensated by giving extra calorie-rich feed and special care.':
      'ਸਰਦੀਆਂ ਦੇ ਮੌਸਮ ਵਿੱਚ ਬਹੁਤ ਸਾਰੇ ਜਾਨਵਰ ਅਕਸਰ ਖਾਣਾ ਖਾਣ ਤੋਂ ਇਨਕਾਰ ਕਰਦੇ ਹਨ, ਬੁਖਾਰ ਹੋ ਜਾਂਦੇ ਹਨ ਅਤੇ ਸਾਹ ਵਿਚ ਮੁਸ਼ਕਿਲ  ਜੋ ਬਦਲੇ ਵਿੱਚ ਦੁੱਧ ਦੇ ਉਤਪਾਦਨ, ਸਿਹਤ ਅਤੇ ਪ੍ਰਜਨਨ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ।ਗੰਭੀਰ ਠੰਡੇ ਮਾਹੌਲ ਦੇ ਨਤੀਜੇ ਵਜੋਂ ਊਰਜਾ ਦਾ ਨੁਕਸਾਨ ਵਧ ਜਾਂਦਾ ਹੈ, ਜਿੰਦਾ ਮੁਆਵਜ਼ਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ ਵਾਧੂ ਕੈਲੋਰੀ-ਅਮੀਰ ਫੀਡ ਅਤੇ ਵਿਸ਼ੇਸ਼ ਦੇਖਭਾਲ ਦੇ ਕੇ।',
  'Feeding Management During Summer': 'ਗਰਮੀਆਂ ਦੌਰਾਨ ਖੁਰਾਕ ਦਾ ਪ੍ਰਬੰਧ',
  'Provision of or fresh tap water or at least normal drinking water to the livestock as per requirement throughout day and night':
      'ਪਸ਼ੂਆਂ ਲਈ ਤਾਜ਼ੇ ਟੂਟੀ ਦੇ ਪਾਣੀ ਜਾਂ ਘੱਟੋ-ਘੱਟ ਆਮ ਪੀਣ ਵਾਲੇ ਪਾਣੀ ਦਾ ਪ੍ਰਬੰਧ ਦਿਨ ਅਤੇ ਰਾਤ ਲੋੜ ਅਨੁਸਾਰ।',
  'Prefer to feed the animal during night time or early morning':
      'ਰਾਤ ਦੇ ਸਮੇਂ ਜਾਂ ਸੁਬ੍ਹਾ - ਸੁਬ੍ਹਾ ਪਸ਼ੂ ਨੂੰ ਭੋਜਨ ਦੇਣ ਨੂੰ ਤਰਜੀਹ ਦਿਓ।',
  'Prefer grazing during early morning and late evening':
      'ਸਵੇਰੇ ਅਤੇ ਦੇਰ ਸ਼ਾਮ ਨੂੰ ਚਰਾਉਣ ਨੂੰ ਤਰਜੀਹ ਦਿਓ।',
  'Ration especially energy density of the ration must be increased by decreasing straw and increasing concentrate mixture':
      'ਰਾਸ਼ਨ ਖਾਸ ਕਰਕੇ ਰਾਸ਼ਨ ਦੀ ਊਰਜਾ ਘਣਤਾ ਤੂੜੀ ਨੂੰ ਘਟਾ ਕੇ ਅਤੇ ਸੰਘਣੇ ਮਿਸ਼ਰਣ ਨੂੰ ਵਧਾ ਕੇ ਵਧਾਇਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।',
  'Provide diet with low fiber and high soluble carbohydrate':
      'ਘੱਟ ਫਾਈਬਰ ਅਤੇ ਉੱਚ ਘੁਲਣਸ਼ੀਲ ਕਾਰਬੋਹਾਈਡਰੇਟ ਵਾਲੀ ਖੁਰਾਕ ਦਿਓ।',
  'Provide potassium rich mineral mixture':
      'ਪੋਟਾਸ਼ੀਅਮ ਨਾਲ ਭਰਪੂਰ ਖਣਿਜ ਮਿਸ਼ਰਣ ਪ੍ਰਦਾਨ ਕਰੋ।',
  'Feeding Management During Winter': 'ਸਰਦੀਆਂ ਦੌਰਾਨ ਖੁਰਾਕ ਦਾ ਪ੍ਰਬੰਧ',
  'Nutrition, especially balanced rations, fortified and supplemented with protein ingredients like whole cotton seed or cakes, becomes important':
      'ਪੋਸ਼ਣ, ਖਾਸ ਕਰਕੇ ਸੰਤੁਲਿਤ ਰਾਸ਼ਨ, ਮਜ਼ਬੂਤ ਅਤੇ ਪ੍ਰੋਟੀਨ ਨਾਲ ਪੂਰਕ ਸਾਰੀ ਕਪਾਹ ਦੇ ਬੀਜ ਜਾਂ ਕੇਕ ਵਰਗੇ ਤੱਤ ਮਹੱਤਵਪੂਰਨ ਬਣ ਜਾਂਦੇ ਹਨ।',
  'Rations containing about 17 per cent fibre in the animal feed are also helpful to increase fat percentage in milk. Concentrate mixture should comprise grains (40 percent), oil cakes (32 per cent), brans (25 per cent), mineral mixture (2 per cent) and common salt (1 per cent)':
      'ਦੁੱਧ ਵਿੱਚ ਚਰਬੀ ਦੀ ਪ੍ਰਤੀਸ਼ਤਤਾ ਵਧਾਓ ਲਈ ਪਸ਼ੂ ਖੁਰਾਕ ਵਿੱਚ ਲਗਭਗ 17 ਪ੍ਰਤੀਸ਼ਤ ਫਾਈਬਰ ਵਾਲੇ ਰਾਸ਼ਨ ਵੀ ਮਦਦਗਾਰ ਹੁੰਦੇ ਹਨ। ਗਾੜ੍ਹੇ ਮਿਸ਼ਰਣ ਵਿੱਚ ਅਨਾਜ (40 ਪ੍ਰਤੀਸ਼ਤ), ਤੇਲ ਦੇ ਕੇਕ (32 ਪ੍ਰਤੀਸ਼ਤ), ਛਾਲੇ (25 ਪ੍ਰਤੀਸ਼ਤ), ਖਣਿਜ ਮਿਸ਼ਰਣ (2 ਪ੍ਰਤੀਸ਼ਤ) ਅਤੇਆਮ ਲੂਣ (1 ਪ੍ਰਤੀਸ਼ਤ)।',
  'Milch animals should be fed with a mixture of oil cakes and jiggery to maintain the body temperature':
      'ਸਰੀਰ ਦਾ ਤਾਪਮਾਨ ਬਰਕਰਾਰ ਰੱਖਣ ਲਈ ਦੁਧਾਰੂ ਪਸ਼ੂਆਂ ਨੂੰ ਤੇਲ ਦੇ ਕੇਕ ਅਤੇ ਗੁੜ ਦੇ ਮਿਸ਼ਰਣ ਨਾਲ ਖੁਆਉਣਾ ਚਾਹੀਦਾ ਹੈ।',
  'Essential salts / mineral mixture in appropriate quantities must be mixed with feed and given to the animals':
      'ਜ਼ਰੂਰੀ ਲੂਣ/ਖਣਿਜ ਮਿਸ਼ਰਣ ਨੂੰ ਢੁਕਵੀਂ ਮਾਤਰਾ ਵਿੱਚ ਫੀਡ ਵਿੱਚ ਮਿਲਾਉਣਾ ਅਤੇ ਜਾਨਵਰਾਂ ਨੂੰ ਦਿੱਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।',
  'Apart from this the extra energy-rich grains at approximately 0.8 per cent of body weight should be fed to counter the stress of cold for maintaining normal milk production and other activities':
      'ਇਸ ਤੋਂ ਇਲਾਵਾ ਠੰਡੇ ਦੇ ਤਣਾਅ ਦਾ ਮੁਕਾਬਲਾ ਕਰਨ ਲਈ ਅਤੇ ਆਮ ਦੁੱਧ ਨੂੰ ਬਣਾਈ ਰੱਖਣ ਲਈ ਉਤਪਾਦਨ ਅਤੇ ਹੋਰ ਗਤੀਵਿਧੀਆਂ ਲਈ ਸਰੀਰ ਦੇ ਭਾਰ ਦੇ ਲਗਭਗ 0.8 ਪ੍ਰਤੀਸ਼ਤ ਵਾਧੂ ਊਰਜਾ ਨਾਲ ਭਰਪੂਰ ਅਨਾਜ ਖੁਆਇਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।',
  'To prevent bloat in animals, mix berseem with dry fodder like wheat straw. Never feed rice straw alone.':
      'ਪਸ਼ੂਆਂ ਵਿੱਚ ਬਲੋਟ ਨੂੰ ਰੋਕਣ ਲਈ, ਬਰਸੀਮ ਨੂੰ ਸੁੱਕੇ ਚਾਰੇ ਜਿਵੇਂ ਕਿ ਕਣਕ ਦੀ ਪਰਾਲੀ ਵਿੱਚ ਮਿਲਾ ਦਿਓ। ਕਦੇ ਵੀ ਚੌਲਾਂ ਦੀ ਪਰਾਲੀ ਨੂੰ ਇਕੱਲੇ ਨਹੀਂ।',
  'Water, possibly lukewarm, should be clean and available four times a day at their drinking time':
      'ਪਾਣੀ, ਸੰਭਵ ਤੌਰ `ਤੇ ਕੋਸਾ, ਸਾਫ਼ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ ਅਤੇ ਦਿਨ ਵਿੱਚ ਚਾਰ ਵਾਰ ਉਪਲਬਧ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
  'The quantity of green fodder must be kept in limited quantities in the animal feed, as it increases the chances of occurrence of diarrhea.Most of the time green fodder are to be mixed with straw to prevent diarrhea. Addition of straw will be useful in chewing activity which is essential for increasing body temperature.':
      'ਪਸ਼ੂਆਂ ਦੇ ਚਾਰੇ ਵਿੱਚ ਹਰੇ ਚਾਰੇ ਦੀ ਮਾਤਰਾ ਸੀਮਤ ਮਾਤਰਾ ਵਿੱਚ ਰੱਖੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ, ਕਿਉਂਕਿ ਇਹ ਦਸਤ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ ਨੂੰ ਵਧਾਉਂਦਾ ਹੈ। ਬਹੁਤੀ ਵਾਰ ਦਸਤ ਨੂੰ ਰੋਕਣ ਲਈ ਹਰੇ ਚਾਰੇ ਨਾਲ ਤੂੜੀ ਨੂੰ ਮਿਲਾਉਣਾ ਹੁੰਦਾ ਹੈ। ਤੂੜੀ ਦਾ ਜੋੜ ਚਬਾਉਣ ਦੀ ਗਤੀਵਿਧੀ ਵਿੱਚ ਲਾਭਦਾਇਕ ਹੋਵੇਗਾ ਜੋ ਸਰੀਰ ਦੇ ਤਾਪਮਾਨ ਨੂੰ ਵਧਾਉਣ ਲਈ ਜ਼ਰੂਰੀ ਹੈ।',
  'If there is an adequate quantity of green fodder still available after feeding the animals, this must be dried in the sun and stored for periods of shortage':
      'ਜੇਕਰ ਜਾਨਵਰ ਨੂੰ ਫੀਡ ਕਰਨ ਤੋਂ ਬਾਅਦ ਵੀ ਹਰੇ ਚਾਰੇ ਦੀ ਕਾਫੀ ਮਾਤਰਾ ਉਪਲਬਧ ਹੈ, ਇਸ ਨੂੰ ਸੂਰਜ ਵਿੱਚ ਸੁਕਾਉਣਾ ਚਾਹੀਦਾ ਹੈ ਅਤੇ ਘਾਟ ਦੇ ਸਮੇਂ ਲਈ ਸਟੋਰ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ।',
  'Climate Smart Feeding Practices': 'ਜਲਵਾਯੂ ਸਮਾਰਟ ਫੀਡਿੰਗ ਅਭਿਆਸ',
  'Providing balanced ration with concentrate mixture having buffer (Sodium bi-carbonate or cation based mineral supplement) for high producing buffalo during heat stress period.':
      'ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੀ ਮਿਆਦ ਦੇ ਦੌਰਾਨ ਉੱਚ ਉਤਪਾਦਕ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਲਈ ਬਫਰ (ਸੋਡੀਅਮ ਬਾਇ- ਕਾਰਬੋਨੇਟ ਜਾਂ ਕੈਸ਼ਨ ਅਧਾਰਤ ਖਣਿਜ ਪੂਰਕ) ਵਾਲੇ ਸੰਘਣੇ ਮਿਸ਼ਰਣ ਨਾਲ ਸੰਤੁਲਿਤ ਰਾਸ਼ਨ ਪ੍ਰਦਾਨ ਕਰਨਾ।',
  'Mineral mixture supplementation with feed @ 50-100 gm per milch buffalo perday depending upon body weight and production performance.':
      'ਪ੍ਰਤੀ ਦੁਧਾਰੂ ਮੱਝ ਅਤੇ ਗਾਂ ਪ੍ਰਤੀ 50-100 ਗ੍ਰਾਮ ਫੀਡ ਦੇ ਨਾਲ ਖਣਿਜ ਮਿਸ਼ਰਣ ਪੂਰਕ ਦਿਨ ਸਰੀਰ ਦੇ ਭਾਰ ਅਤੇ ਉਤਪਾਦਨ ਦੇ ਪ੍ਰਦਰਸ਼ਨ `ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ।',
  'Supplementation of dietary soluble carbohydrate may compensate the heat stress related reduction in milch buffalo without affecting chewing activity.':
      'ਖੁਰਾਕ ਵਿੱਚ ਘੁਲਣਸ਼ੀਲ ਕਾਰਬੋਹਾਈਡਰੇਟ ਦੀ ਪੂਰਤੀ ਦੁਧਾਰੂ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਵਿੱਚ ਗਰਮੀ ਤਣਾਅ ਦੀ ਕਮੀ ਕਰ ਸਕਦੀ ਹੈ ਬਿਨਾਂ ਚਬਾਉਣ ਦੀ ਗਤੀਵਿਧੀ ਕਿਸੇ ਪ੍ਰਭਾਵ ਦੇ।',
  'Supplementation of ‘Prill Fat’ (saturated fat) of 50-75 gm per lactating Murrah buffalo per day during heat stress may compensate reduced milk production.':
      '50-75 ਗ੍ਰਾਮ ‘ਪ੍ਰਿਲ ਫੈਟ’ (ਸੰਤ੍ਰਿਪਤ ਚਰਬੀ) ਦੀ ਪੂਰਤੀ ਪ੍ਰਤੀ ਦੁੱਧ ਚੁੰਘਾਉਣ ਵਾਲੀ ਮੁਰਾਹ ਦੀ ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੌਰਾਨ ਮੱਝ ਪ੍ਰਤੀ ਦਿਨ ਦੁੱਧ ਦੇ ਉਤਪਾਦਨ ਵਿੱਚ ਕਮੀ ਦੀ ਭਰਪਾਈ ਕਰ ਸਕਦੀ ਹੈ।',
  'Vitamin A, C, E and Zinc supplementation showed positive effects towards ameliorating environmental heat stress':
      'ਵਿਟਾਮਿਨ ਏ, ਸੀ, ਈ ਅਤੇ ਜ਼ਿੰਕ ਪੂਰਕ ਨੇ ਪ੍ਰਤੀ ਸਕਾਰਾਤਮਕ ਪ੍ਰਭਾਵ ਦਿਖਾਇਆ ਵਾਤਾਵਰਣ ਦੀ ਗਰਮੀ ਦੇ ਤਣਾਅ ਨੂੰ ਘਟਾਉਣਾ।',
  'Disclaimer': 'ਬੇਦਾਅਵਾ',
  'How to save animal from Thermal stress?':
      'ਪਸ਼ੂ ਨੂੰ ਥਰਮਲ ਸਟ੍ਰੈਸ ਤੋਂ ਕਿਵੇਂ ਬਚਾਉਣਾ ਹੈ?',
  'Sign Out': 'ਸਾਈਨ ਆਉਟ',
}
  ..addAll({
    'Andaman and Nicobar Islands': 'ਅੰਡਮਾਨ ਅਤੇ ਨਿਕੋਬਾਰ ਟਾਪੂ',
    'Andhra Pradesh': 'ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼',
    'Arunachal Pradesh': 'ਅਰੂਣਾਚਲ ਪ੍ਰਦੇਸ਼',
    'Assam': 'ਅਸਾਮ',
    'Bihar': 'ਬਿਹਾਰ',
    'Chandigarh': 'ਚੰਡੀਗੜ੍ਹ',
    'Chhattisgarh': 'ਛੱਤੀਸਗੜ੍ਹ',
    'Dadra and Nagar Haveli and Daman and Diu':
        'ਦਾਦਰਾ ਅਤੇ ਨਗਰ ਹਵੇਲੀ ਅਤੇ ਦਮਨ ਅਤੇ ਦਿਉ',
    'Delhi': 'ਦਿੱਲੀ',
    'Goa': 'ਗੋਆ',
    'Gujarat': 'ਗੁਜਰਾਤ',
    'Haryana': 'ਹਰਿਆਣਾ',
    'Himachal Pradesh': 'ਹਿਮਾਚਲ ਪ੍ਰਦੇਸ਼',
    'Jammu and Kashmir': 'ਜੰਮੂ ਅਤੇ ਕਸ਼ਮੀਰ',
    'Jharkhand': 'ਝਾਰਖੰਡ',
    'Karnataka': 'ਕਰਨਾਟਕ',
    'Kerala': 'ਕੇਰਲ',
    'Ladakh': 'ਲਾਦਾਖ',
    'Lakshadweep': 'ਲੱਖਸ਼ਦੀਪ',
    'Madhya Pradesh': 'ਮਧ ਪ੍ਰਦੇਸ਼',
    'Maharashtra': 'ਮਹਾਰਾਸ਼ਟਰ',
    'Manipur': 'ਮਣੀਪੁਰ',
    'Meghalaya': 'ਮੇਘਾਲਾ',
    'Mizoram': 'ਮਿਜੋਰਮ',
    'Nagaland': 'ਨਾਗਾਲੈਂਡ',
    'Odisha': 'ਓਡੀਸ਼ਾ',
    'Puducherry': 'ਪੁਡੁੱਚੇਰੀ',
    'Punjab': 'ਪੰਜਾਬ',
    'Rajasthan': 'ਰਾਜਸਥਾਨ',
    'Sikkim': 'ਸਿੱਕਿਮ',
    'Tamil Nadu': 'ਤਮਿਲਨਾਡੂ',
    'Telangana': 'ਤਲੰਗਾਨਾ',
    'Tripura': 'ਤ੍ਰਿਪੁਰਾ',
    'Uttar Pradesh': 'ਉੱਤਰ ਪ੍ਰਦੇਸ਼',
    'Uttarakhand': 'ਉੱਤਰਾਖੰਡ',
    'West Bengal': 'ਪੱਛਮੀ ਬੰਗਾਲ',
  })
  ..addAll({
    'Nicobar': 'ਨਿਕੋਬਾਰ',
    'North and Middle Andaman': 'ਉੱਤਰੀ ਅਤੇ ਮੱਧ ਅੰਡੇਮਾਨ',
    'South Andaman': 'ਦੱਖਣੀ ਅੰਡੇਮਾਨ',
    'Anantapur': 'ਅਨੰਤਪੁਰ',
    'Chittoor': 'ਚਿੱਤੂਰ',
    'East Godavari': 'ਪੂਰਬੀ ਗੋਦਾਵਰੀ',
    'Guntur': 'ਗੁੰਟੂਰ',
    'Krishna': 'ਕ੍ਰਿਸ਼ਨਾ',
    'Kurnool': 'ਕੁਰਨੂਲ',
    'Prakasam': 'ਪ੍ਰਕਾਸ਼ਮ',
    'Sri Potti Sriramulu Nellore': 'ਸ਼੍ਰੀ ਪੋੱਤੀ ਸ਼੍ਰੀਰਾਮੁਲੂ ਨੇਲੋਰ',
    'Srikakulam': 'ਸ਼੍ਰੀਕਾਕੁਲਮ',
    'Visakhapatnam': 'ਵਿਸ਼ਾਖਾਪਟਨਮ',
    'Vizianagaram': 'ਵਿਜਯਨਗਰਮ',
    'West Godavari': 'ਪੱਛਮੀ ਗੋਦਾਵਰੀ',
    'YSR Kadapa': 'ਵਾਈਐਸਆਰ ਕਡਾਪਾ',
    'Anjaw': 'ਅੰਜਾਵ',
    'Changlang': 'ਚਾਂਗਲਾਂਗ',
    'Dibang Valley': 'ਦਿਬਾਂਗ ਵੈਲੀ',
    'East Kameng': 'ਪੂਰਬੀ ਕਾਮੇਂਗ',
    'East Siang': 'ਪੂਰਬੀ ਸਿਆਂਗ',
    'Kamle': 'ਕਾਮਲੇ',
    'Kra Daadi': 'ਕਰਾ ਦਾਦੀ',
    'Kurung Kumey': 'ਕੁਰੁੰਗ ਕੁਮੇ',
    'Lepa Rada': 'ਲੇਪਾ ਰਾਡਾ',
    'Lohit': 'ਲੋਹਿਤ',
    'Longding': 'ਲੋਂਗਡਿੰਗ',
    'Lower Dibang Valley': 'ਹੇਠਲੀ ਦਿਬਾਂਗ ਵੈਲੀ',
    'Lower Siang': 'ਹੇਠਲੀ ਸਿਆਂਗ',
    'Lower Subansiri': 'ਹੇਠਲੀ ਸੁਬਨਸਿਰੀ',
    'Namsai': 'ਨਾਮਸਾਈ',
    'Pakke Kessang': 'ਪੱਕੇ ਕੇਸਾਂਗ',
    'Papum Pare': 'ਪਾਪੁਮ ਪਾਰੇ',
    'Shi Yomi': 'ਸ਼ੀ ਯੋਮੀ',
    'Siang': 'ਸਿਆਂਗ',
    'Tawang': 'ਤਵਾਂਗ',
    'Tirap': 'ਤਿਰਾਪ',
    'Upper Siang': 'ਉੱਪਰਲੀ ਸਿਆਂਗ',
    'Upper Subansiri': 'ਉੱਪਰਲੀ ਸੁਬਨਸਿਰੀ',
    'West Kameng': 'ਪੱਛਮੀ ਕਾਮੇਂਗ',
    'West Siang': 'ਪੱਛਮੀ ਸਿਆਂਗ',
    'Baksa': 'ਬਕਸਾ',
    'Barpeta': 'ਬਾਰਪੇਟਾ',
    'Biswanath': 'ਬਿਸ਼ਵਨਾਥ',
    'Bongaigaon': 'ਬੋਂਗਾਈਗਾਓਂ',
    'Cachar': 'ਕਾਚਾਰ',
    'Charaideo': 'ਚਰਾਈਦੇਓ',
    'Chirang': 'ਚਿਰਾਂਗ',
    'Darrang': 'ਦਰਾਂਗ',
    'Dhemaji': 'ਧੇਮਾਜੀ',
    'Dhubri': 'ਧੁਬਰੀ',
    'Dibrugarh': 'ਡਿਬਰੂਗੜ੍ਹ',
    'Dima Hasao': 'ਦੀਮਾ ਹਸਾਓ',
    'Goalpara': 'ਗੋਆਲਪਾਰਾ',
    'Golaghat': 'ਗੋਲਾਘਾਟ',
    'Hailakandi': 'ਹੈਲਾਕਾਂਡੀ',
    'Hojai': 'ਹੋਜਾਈ',
    'Jorhat': 'ਜੋਰਹਾਟ',
    'Kamrup Metropolitan': 'ਕਾਮਰੂਪ ਮਹਾਨਗਰ',
    'Kamrup': 'ਕਾਮਰੂਪ',
    'Karbi Anglong': 'ਕਾਰਬੀ ਅੰਗਲੋਂਗ',
    'Karimganj': 'ਕਰੀਮਗੰਜ',
    'Kokrajhar': 'ਕੋਕਰਾਝਾਰ',
    'Lakhimpur': 'ਲਖੀਮਪੁਰ',
    'Majuli': 'ਮਾਜੁਲੀ',
    'Morigaon': 'ਮੋਰੀਗਾਓਂ',
    'Nagaon': 'ਨਗਾਓਂ',
    'Nalbari': 'ਨਲਬਾੜੀ',
    'Sivasagar': 'ਸ਼ਿਵਸਾਗਰ',
    'Sonitpur': 'ਸੋਨੀਤਪੁਰ',
    'South Salmara-Mankachar': 'ਦੱਖਣੀ ਸਲਮਾਰਾ-ਮਾਨਕਾਚਰ',
    'Tinsukia': 'ਤਿਨਸੁਕੀਆ',
    'Udalguri': 'ਉਦਲਗੁੜੀ',
    'West Karbi Anglong': 'ਪੱਛਮੀ ਕਾਰਬੀ ਅੰਗਲੋਂਗ',
    'Araria': 'ਅਰਾਰੀਆ',
    'Arwal': 'ਅਰਵਲ',
    'Aurangabad': 'ਔਰੰਗਾਬਾਦ',
    'Banka': 'ਬਾਂਕਾ',
    'Begusarai': 'ਬੇਗੂਸਰਾਏ',
    'Bhagalpur': 'ਭਾਗਲਪੁਰ',
    'Bhojpur': 'ਭੋਜਪੁਰ',
    'Buxar': 'ਬਕਸਰ',
    'Darbhanga': 'ਦਰਭੰਗਾ',
    'East Champaran': 'ਪੂਰਬੀ ਚੰਪਾਰਣ',
    'Gaya': 'ਗਯਾ',
    'Gopalganj': 'ਗੋਪਾਲਗੰਜ',
    'Jamui': 'ਜਮੂਈ',
    'Jehanabad': 'ਜਹਾਨਾਬਾਦ',
    'Kaimur': 'ਕੈਮੂਰ',
    'Katihar': 'ਕਟਿਹਾਰ',
    'Khagaria': 'ਖਗੜੀਆ',
    'Kishanganj': 'ਕਿਸ਼ਨਗੰਜ',
    'Lakhisarai': 'ਲਖੀਸਰਾਏ',
    'Madhepura': 'ਮਧੇਪੁਰਾ',
    'Madhubani': 'ਮਧੁਬਨੀ',
    'Munger': 'ਮੁੰਗੇਰ',
    'Muzaffarpur': 'ਮੁਜੱਫਰਪੁਰ',
    'Nalanda': 'ਨਾਲੰਦਾ',
    'Nawada': 'ਨਵਾਦਾ',
    'Patna': 'ਪਟਨਾ',
    'Purnia': 'ਪੂਰਨੀਆ',
    'Rohtas': 'ਰੋਹਤਾਸ',
    'Saharsa': 'ਸਹਰਸਾ',
    'Samastipur': 'ਸਮਸਤੀਪੁਰ',
    'Saran': 'ਸਾਰਣ',
    'Sheikhpura': 'ਸ਼ੇਖਪੁਰਾ',
    'Sheohar': 'ਸ਼ਿਵਹਰ',
    'Sitamarhi': 'ਸੀਤਾਮੜ੍ਹੀ',
    'Siwan': 'ਸਿਵਾਨ',
    'Supaul': 'ਸੁਪੌਲ',
    'Vaishali': 'ਵੈਸ਼ਾਲੀ',
    'West Champaran': 'ਪੱਛਮੀ ਚੰਪਾਰਣ',
    'Chandigarh': 'ਚੰਡੀਗੜ੍ਹ',
    'Balod': 'ਬਾਲੋਦ',
    'Baloda Bazar': 'ਬਲੋਦਾ ਬਾਜ਼ਾਰ',
    'Balrampur': 'ਬਲਰਾਮਪੁਰ',
    'Bastar': 'ਬਸਤਰ',
    'Bemetara': 'ਬੇਮੇਤਰਾ',
    'Bijapur': 'ਬੀਜਾਪੁਰ',
    'Bilaspur': 'ਬਿਲਾਸਪੁਰ',
    'Dantewada': 'ਦੰਤੇਵਾੜਾ',
    'Dhamtari': 'ਧਮਤਰੀ',
    'Durg': 'ਦੁਰਗ',
    'Gariaband': 'ਗੜ੍ਹੀਆਬੰਦ',
    'Janjgir-Champa': 'ਜਾਂਜਗੀਰ-ਚਾਂਪਾ',
    'Jashpur': 'ਜਸ਼ਪੁਰ',
    'Kabirdham': 'ਕਬੀਰਧਾਮ',
    'Kanker': 'ਕਾਂਕੇਰ',
    'Kondagaon': 'ਕੋਂਡਾਗਾਓਂ',
    'Korba': 'ਕੋਰਬਾ',
    'Korea': 'ਕੋਰੀਆ',
    'Mahasamund': 'ਮਹਾਸਮੁੰਦ',
    'Mungeli': 'ਮੁੰਗੇਲੀ',
    'Narayanpur': 'ਨਾਰਾਯਣਪੁਰ',
    'Raigarh': 'ਰਾਏਗੜ੍ਹ',
    'Raipur': 'ਰਾਏਪੁਰ',
    'Rajnandgaon': 'ਰਾਜ ਨਾਂਦਗਾਓਂ',
    'Sukma': 'ਸੁਕਮਾ',
    'Surajpur': 'ਸੂਰਜਪੁਰ',
    'Surguja': 'ਸਰਗੁਜਾ',
    'Dadra and Nagar Haveli': 'ਦਾਦਰਾ ਅਤੇ ਨਗਰ ਹਵੇਲੀ',
    'Daman': 'ਦਮਨ',
    'Diu': 'ਦੀਵ',
    'Central Delhi': 'ਕੇਂਦਰੀ ਦਿੱਲੀ',
    'East Delhi': 'ਪੂਰਬੀ ਦਿੱਲੀ',
    'New Delhi': 'ਨਵੀਂ ਦਿੱਲੀ',
    'North Delhi': 'ਉੱਤਰੀ ਦਿੱਲੀ',
    'North East Delhi': 'ਉੱਤਰ ਪੂਰਬੀ ਦਿੱਲੀ',
    'North West Delhi': 'ਉੱਤਰ ਪੱਛਮੀ ਦਿੱਲੀ',
    'Shahdara': 'ਸ਼ਾਹਦਰਾ',
    'South Delhi': 'ਦੱਖਣੀ ਦਿੱਲੀ',
    'South East Delhi': 'ਦੱਖਣ ਪੂਰਬੀ ਦਿੱਲੀ',
    'South West Delhi': 'ਦੱਖਣ ਪੱਛਮੀ ਦਿੱਲੀ',
    'West Delhi': 'ਪੱਛਮੀ ਦਿੱਲੀ',
    'North Goa': 'ਉੱਤਰੀ ਗੋਆ',
    'South Goa': 'ਦੱਖਣੀ ਗੋਆ',
    'Ahmedabad': 'ਅਹਿਮਦਾਬਾਦ',
    'Amreli': 'ਅਮਰੇਲੀ',
    'Anand': 'ਆਨੰਦ',
    'Aravalli': 'ਅਰਾਵਲੀ',
    'Banaskantha': 'ਬਨਾਸਕਾਂਠਾ',
    'Bharuch': 'ਭਰੂਚ',
    'Bhavnagar': 'ਭਾਵਨਗਰ',
    'Botad': 'ਬੋਟਾਦ',
    'Chhota Udepur': 'ਛੋਟਾ ਉਦੇਪੁਰ',
    'Dahod': 'ਦਾਹੋਦ',
    'Dang': 'ਡਾਂਗ',
    'Devbhoomi Dwarka': 'ਦੇਵਭੂਮੀ ਦਵਾਰਕਾ',
    'Gandhinagar': 'ਗਾਂਧੀਨਗਰ',
    'Gir Somnath': 'ਗਿਰ ਸੋਮਨਾਥ',
    'Jamnagar': 'ਜਾਮਨਗਰ',
    'Junagadh': 'ਜੂਨਾਗੜ੍ਹ',
    'Kheda': 'ਖੇੜਾ',
    'Kutch': 'ਕੱਛ',
    'Mahisagar': 'ਮਹੀਸਾਗਰ',
    'Mehsana': 'ਮਹੇਸਾਣਾ',
    'Morbi': 'ਮੋਰਬੀ',
    'Narmada': 'ਨਰਮਦਾ',
    'Navsari': 'ਨਵਸਾਰੀ',
    'Panchmahal': 'ਪੰਚਮਹਾਲ',
    'Patan': 'ਪਾਟਣ',
    'Porbandar': 'ਪੋਰਬੰਦਰ',
    'Rajkot': 'ਰਾਜਕੋਟ',
    'Sabarkantha': 'ਸਾਬਰਕਾਂਠਾ',
    'Surat': 'ਸੂਰਤ',
    'Surendranagar': 'ਸੁਰੇਂਦਰਨਗਰ',
    'Tapi': 'ਤਾਪੀ',
    'Vadodara': 'ਵਡੋਦਰਾ',
    'Valsad': 'ਵਲਸਾਡ',
    'Ambala': 'ਅੰਬਾਲਾ',
    'Bhiwani': 'ਭਿਵਾਨੀ',
    'Charkhi Dadri': 'ਚਰਖੀ ਦਾਦਰੀ',
    'Faridabad': 'ਫਰੀਦਾਬਾਦ',
    'Fatehabad': 'ਫਤਿਹਾਬਾਦ',
    'Gurugram': 'ਗੁਰੂਗ੍ਰਾਮ',
    'Hisar': 'ਹਿਸਾਰ',
    'Jhajjar': 'ਝੱਜਰ',
    'Jind': 'ਜੀਂਦ',
    'Kaithal': 'ਕੈਥਲ',
    'Karnal': 'ਕਰਨਾਲ',
    'Kurukshetra': 'ਕੁਰੂਕਸ਼ੇਤਰ',
    'Mahendragarh': 'ਮਹਿੰਦਰਗੜ੍ਹ',
    'Nuh': 'ਨੂੰਹ',
    'Palwal': 'ਪਲਵਲ',
    'Panchkula': 'ਪੰਚਕੂਲਾ',
    'Panipat': 'ਪਾਨੀਪਤ',
    'Rewari': 'ਰੇਵਾੜੀ',
    'Rohtak': 'ਰੋਹਤਕ',
    'Sirsa': 'ਸਿਰਸਾ',
    'Sonipat': 'ਸੋਨੀਪਤ',
    'Yamunanagar': 'ਯਮੁਨਾਨਗਰ',
    'Bilaspur (Himachal Pradesh)': 'ਬਿਲਾਸਪੁਰ',
    'Chamba': 'ਚੰਬਾ',
    'Hamirpur': 'ਹਮੀਰਪੁਰ',
    'Kangra': 'ਕਾਂਗੜਾ',
    'Kinnaur': 'ਕਿੰਨੌਰ',
    'Kullu': 'ਕੁੱਲੂ',
    'Lahaul and Spiti': 'ਲਾਹੌਲ ਅਤੇ ਸਪੀਤੀ',
    'Mandi': 'ਮੰਡੀ',
    'Shimla': 'ਸ਼ਿਮਲਾ',
    'Sirmaur': 'ਸਿਰਮੌਰ',
    'Solan': 'ਸੋਲਨ',
    'Una': 'ਊਨਾ',
    'Anantnag': 'ਅਨੰਤਨਾਗ',
    'Bandipora': 'ਬਾਂਦੀਪੋਰਾ',
    'Baramulla': 'ਬਾਰਾਮੂਲਾ',
    'Budgam': 'ਬਡਗਾਮ',
    'Doda': 'ਡੋਡਾ',
    'Ganderbal': 'ਗਾਂਦਰਬਲ',
    'Jammu': 'ਜੰਮੂ',
    'Kathua': 'ਕਠੂਆ',
    'Kishtwar': 'ਕਿਸ਼ਤਵਾੜ',
    'Kulgam': 'ਕੁਲਗਾਮ',
    'Kupwara': 'ਕੁਪਵਾੜਾ',
    'Poonch': 'ਪੂੰਛ',
    'Pulwama': 'ਪੁਲਵਾਮਾ',
    'Rajouri': 'ਰਾਜੌਰੀ',
    'Ramban': 'ਰਾਮਬਨ',
    'Reasi': 'ਰਿਆਸੀ',
    'Samba': 'ਸਾਂਬਾ',
    'Shopian': 'ਸ਼ੋਪੀਆਂ',
    'Srinagar': 'ਸ਼੍ਰੀਨਗਰ',
    'Udhampur': 'ਉਧਮਪੁਰ',
    'Bokaro': 'ਬੋਕਾਰੋ',
    'Chatra': 'ਚਤਰਾ',
    'Deoghar': 'ਦੇਵਘਰ',
    'Dhanbad': 'ਧਨਬਾਦ',
    'Dumka': 'ਦੁਮਕਾ',
    'East Singhbhum': 'ਪੂਰਬੀ ਸਿੰਘਭੂਮ',
    'Garhwa': 'ਗੜ੍ਹਵਾ',
    'Giridih': 'ਗਿਰਿਡੀਹ',
    'Godda': 'ਗੋਡ੍ਡਾ',
    'Gumla': 'ਗੁਮਲਾ',
    'Hazaribagh': 'ਹਜ਼ਾਰੀਬਾਗ',
    'Jamtara': 'ਜਾਮਤਾੜਾ',
    'Khunti': 'ਖੂੰਟੀ',
    'Koderma': 'ਕੋਡਰਮਾ',
    'Latehar': 'ਲਾਤੇਹਾਰ',
    'Lohardaga': 'ਲੋਹਰਦੱਗਾ',
    'Pakur': 'ਪਾਕੁੜ',
    'Palamu': 'ਪਲਾਮੂ',
    'Ramgarh': 'ਰਾਮਗੜ੍ਹ',
    'Ranchi': 'ਰਾਂਚੀ',
    'Sahebganj': 'ਸਾਹਿਬਗੰਜ',
    'Seraikela Kharsawan': 'ਸਰਾਇਕੇਲਾ ਖਰਸਾਵਾਂ',
    'Simdega': 'ਸਿਮਡੇਗਾ',
    'West Singhbhum': 'ਪੱਛਮੀ ਸਿੰਘਭੂਮ',
    'Bagalkot': 'ਬਾਗਲਕੋਟ',
    'Ballari': 'ਬੱਲਾਰੀ',
    'Belagavi': 'ਬੇਲਗਾਮ',
    'Bengaluru Rural': 'ਬੇਂਗਲੁਰੂ ਰੂਰਲ',
    'Bengaluru Urban': 'ਬੇਂਗਲੁਰੂ ਅਰਬਨ',
    'Bidar': 'ਬੀਦਰ',
    'Chamarajanagar': 'ਚਾਮਰਾਜਨਗਰ',
    'Chikballapur': 'ਚਿਕਬੱਲਾਪੁਰ',
    'Chikkamagaluru': 'ਚਿਕਮਗਲੂਰ',
    'Chitradurga': 'ਚਿਤਰਦੁਰਗਾ',
    'Dakshina Kannada': 'ਦੱਖਣੀ ਕੰਨੜ',
    'Davanagere': 'ਦਾਵਣਗੇਰੇ',
    'Dharwad': 'ਧਾਰਵਾੜ',
    'Gadag': 'ਗਦਗ',
    'Hassan': 'ਹਾਸਨ',
    'Haveri': 'ਹਾਵੇਰੀ',
    'Kalaburagi': 'ਕਲਬੁਰਗੀ',
    'Kodagu': 'ਕੋਡਗੂ',
    'Kolar': 'ਕੋਲਾਰ',
    'Koppal': 'ਕੋਪਲ',
    'Mandya': 'ਮੰਡਿਆ',
    'Mysuru': 'ਮੈਸੂਰੂ',
    'Raichur': 'ਰਾਇਚੂਰ',
    'Ramanagara': 'ਰਾਮਨਗਰ',
    'Shivamogga': 'ਸ਼ਿਵਮੋਗਾ',
    'Tumakuru': 'ਤੁਮਾਕੁਰੂ',
    'Udupi': 'ਉਡੁਪੀ',
    'Uttara Kannada': 'ਉੱਤਰਾ ਕਨਾਡਾ',
    'Vijayapura': 'ਵਿਜਯਾਪੁਰਾ',
    'Yadgir': 'ਯਾਦਗੀਰ',
    'Alappuzha': 'ਅਲੱਪੁਜ਼ਾ',
    'Ernakulam': 'ਇਰਨਾਕੁਲਮ',
    'Idukki': 'ਇਡੁੱਕੀ',
    'Kannur': 'ਕੰਨੂਰ',
    'Kasaragod': 'ਕਸਰਗੋਡ',
    'Kollam': 'ਕੋੱਲਮ',
    'Kottayam': 'ਕੋਟਾਯਮ',
    'Kozhikode': 'ਕੋਜ਼ਿਕੋਡ',
    'Malappuram': 'ਮਾਲੱਪੁਰਮ',
    'Palakkad': 'ਪਾਲਕਾੜ',
    'Pathanamthitta': 'ਪਾਥਾਨਾਮਥਿਟਾ',
    'Thiruvananthapuram': 'ਥਿਰੁਵਨੰਥਪੁਰਮ',
    'Thrissur': 'ਥ੍ਰਿਸੂਰ',
    'Wayanad': 'ਵਾਯਨਾਡ',
    'Kargil': 'ਕਾਰਗਿਲ',
    'Leh': 'ਲੇਹ',
    'Lakshadweep': 'ਲੱਖਾਦਵੀਪ',
    'Agar Malwa': 'ਅਗਰ ਮਾਲਵਾ',
    'Alirajpur': 'ਅਲੀਰਾਜਪੁਰ',
    'Anuppur': 'ਅਨੂਪਪੁਰ',
    'Ashoknagar': 'ਅਸ਼ੋਕਨਗਰ',
    'Balaghat': 'ਬਾਲਾਘਾਟ',
    'Barwani': 'ਬੜਵਾਨੀ',
    'Betul': 'ਬੇਤੂਲ',
    'Bhind': 'ਭਿੰਡ',
    'Bhopal': 'ਭੋਪਾਲ',
    'Burhanpur': 'ਬੁਰਹਾਨਪੁਰ',
    'Chhatarpur': 'ਛਤਰਪੁਰ',
    'Chhindwara': 'ਛਿੰਡਵਾੜਾ',
    'Damoh': 'ਦਮੋਹ',
    'Datia': 'ਦਾਤਿਆ',
    'Dewas': 'ਦੇਵਾਸ',
    'Dhar': 'ਧਾਰ',
    'Dindori': 'ਡਿੰਡੋਰੀ',
    'Guna': 'ਗੁਨਾ',
    'Gwalior': 'ਗਵਾਲਿਓਰ',
    'Harda': 'ਹਾਰਦਾ',
    'Hoshangabad': 'ਹੋਸ਼ੰਗਾਬਾਦ',
    'Indore': 'ਇੰਦੋਰ',
    'Jabalpur': 'ਜਬਲਪੁਰ',
    'Jhabua': 'ਝਾਬੂਆ',
    'Katni': 'ਕਟਨੀ',
    'Khandwa': 'ਖੰਡਵਾ',
    'Khargone': 'ਖਰਗੋਨ',
    'Mandla': 'ਮੰਡਲਾ',
    'Mandsaur': 'ਮੰਸੌਰ',
    'Morena': 'ਮੋਰੇਨਾ',
    'Narsinghpur': 'ਨਰਸਿੰਘਪੁਰ',
    'Neemuch': 'ਨੀਮਚ',
    'Panna': 'ਪੰਨਾ',
    'Raisen': 'ਰਾਇਸੇਨ',
    'Rajgarh': 'ਰਾਜਗੜ੍ਹ',
    'Ratlam': 'ਰਤਲਾਮ',
    'Rewa': 'ਰੀਵਾ',
    'Sagar': 'ਸਾਗਰ',
    'Satna': 'ਸਤਨਾ',
    'Sehore': 'ਸਿਹੋਰ',
    'Seoni': 'ਸਿਓਨੀ',
    'Shahdol': 'ਸ਼ਹਡੋਲ',
    'Shajapur': 'ਸ਼ਾਜਾਪੁਰ',
    'Sheopur': 'ਸ਼ੇਓਪੁਰ',
    'Shivpuri': 'ਸ਼ਿਵਪੁਰੀ',
    'Sidhi': 'ਸੀਧੀ',
    'Singrauli': 'ਸਿੰਗਰੌਲੀ',
    'Tikamgarh': 'ਟੀਕਮਗੜ੍ਹ',
    'Ujjain': 'ਉਜਜੈਨ',
    'Umaria': 'ਉਮਾਰਿਆ',
    'Vidisha': 'ਵਿਦੀਸ਼ਾ',
    'Ahmednagar': 'ਅਹਿਮਦਨਗਰ',
    'Akola': 'ਅਕੋਲਾ',
    'Amravati': 'ਅਮਰਾਵਤੀ',
    'Beed': 'ਬੀਡ',
    'Bhandara': 'ਭੰਡਾਰਾ',
    'Buldhana': 'ਬੁਲਧਾਣਾ',
    'Chandrapur': 'ਚੰਦ੍ਰਪੁਰ',
    'Dhule': 'ਧੁਲੇ',
    'Gadchiroli': 'ਗਡਚਿਰੋਲੀ',
    'Gondia': 'ਗੋਂਦਿਆ',
    'Hingoli': 'ਹਿੰਗੋਲੀ',
    'Jalgaon': 'ਜਲਗਾਓਂ',
    'Jalna': 'ਜਲਨਾ',
    'Kolhapur': 'ਕੋਲ੍ਹਾਪੁਰ',
    'Latur': 'ਲਾਤੂਰ',
    'Mumbai City': 'ਮੁੰਬਈ ਸ਼ਹਿਰ',
    'Mumbai Suburban': 'ਮੁੰਬਈ ਉਪਨਗਰ',
    'Nagpur': 'ਨਾਗਪੁਰ',
    'Nanded': 'ਨੰਦੇਡ',
    'Nandurbar': 'ਨੰਦੁਰਬਾਰ',
    'Nashik': 'ਨਾਸਿਕ',
    'Osmanabad': 'ਉਸਮਾਨਾਬਾਦ',
    'Palghar': 'ਪਾਲਘਰ',
    'Parbhani': 'ਪਰਭਾਣੀ',
    'Pune': 'ਪੁਨੇ',
    'Raigad': 'ਰਾਇਗੜ',
    'Ratnagiri': 'ਰਤਨਾਗਿਰੀ',
    'Sangli': 'ਸਾਂਗਲੀ',
    'Satara': 'ਸਾਤਾਰਾ',
    'Sindhudurg': 'ਸਿੰਧੁਦੁਰਗ',
    'Solapur': 'ਸੋਲਾਪੁਰ',
    'Thane': 'ਠਾਣੇ',
    'Wardha': 'ਵਰਧਾ',
    'Washim': 'ਵਾਸ਼ਿਮ',
    'Yavatmal': 'ਯਵਤਮਾਲ',
    'Bishnupur': 'ਬਿਸ਼ਨੂਪੁਰ',
    'Chandel': 'ਚਾਂਦਲ',
    'Churachandpur': 'ਚੁਰਾਚਾਂਦਪੁਰ',
    'Imphal East': 'ਇਮਫਾਲ ਈਸਟ',
    'Imphal West': 'ਇਮਫਾਲ ਵੈਸਟ',
    'Jiribam': 'ਜਿਰਿਬਾਮ',
    'Kakching': 'ਕਾਕਚਿੰਗ',
    'Kamjong': 'ਕਾਮਜੌਂਗ',
    'Kangpokpi': 'ਕਾਂਗਪੋਕਪੀ',
    'Noney': 'ਨੋਨੀ',
    'Pherzawl': 'ਫੇਰਜ਼ੌਲ',
    'Senapati': 'ਸੇਨਾਪਤੀ',
    'Tamenglong': 'ਤਾਮੇਂਗਲੌਂਗ',
    'Tengnoupal': 'ਤੇਂਗਨੌਪਾਲ',
    'Thoubal': 'ਥੋਬਾਲ',
    'Ukhrul': 'ਉਖਰੂਲ',
    'East Garo Hills': 'ਈਸਟ ਗਾਰੋ ਹਿੱਲਸ',
    'East Jaintia Hills': 'ਈਸਟ ਜਾਈਂਟੀਆ ਹਿੱਲਸ',
    'East Khasi Hills': 'ਈਸਟ ਖਾਸੀ ਹਿੱਲਸ',
    'North Garo Hills': 'ਨਾਰਥ ਗਾਰੋ ਹਿੱਲਸ',
    'Ri Bhoi': 'ਰੀ ਭੋਈ',
    'South Garo Hills': 'ਸਾਊਥ ਗਾਰੋ ਹਿੱਲਸ',
    'South West Garo Hills': 'ਸਾਊਥ ਵੈਸਟ ਗਾਰੋ ਹਿੱਲਸ',
    'South West Khasi Hills': 'ਸਾਊਥ ਵੈਸਟ ਖਾਸੀ ਹਿੱਲਸ',
    'West Garo Hills': 'ਵੈਸਟ ਗਾਰੋ ਹਿੱਲਸ',
    'West Jaintia Hills': 'ਵੈਸਟ ਜਾਈਂਟੀਆ ਹਿੱਲਸ',
    'West Khasi Hills': 'ਵੈਸਟ ਖਾਸੀ ਹਿੱਲਸ',
    'Aizawl': 'ਆਈਜ਼ੌਲ',
    'Lunglei': 'ਲੁੰਗਲੇਈ',
    'Champhai': 'ਚੰਫ਼ਾਈ',
    'Serchhip': 'ਸੇਰਚਿਪ',
    'Kolasib': 'ਕੋਲਾਸਿਬ',
    'Lawngtlai': 'ਲਾਂਗਟਲਾਈ',
    'Mamit': 'ਮਾਮਿਤ',
    'Saiha': 'ਸੈਹਾ',
    'Hnahthial': 'ਹਨਾਥਿਆਲ',
    'Saitual': 'ਸੈਤੁਆਲ',
    'Khawzawl': 'ਖਾਵਜ਼ੌਲ',
    'Chumoukedima': 'ਚੁਮੋਕੇਦਿਮਾ',
    'Dimapur': 'ਦੀਮਾਪੁਰ',
    'Kiphire': 'ਕੀਫ਼ੀਰੇ',
    'Kohima': 'ਕੋਹੀਮਾ',
    'Longleng': 'ਲੌਂਗਲੇਂਗ',
    'Mokokchung': 'ਮੋਕੋਕਚੁੰਗ',
    'Mon': 'ਮੋਨ',
    'Noklak': 'ਨੋਕਲਾਕ',
    'Peren': 'ਪੇਰਨ',
    'Phek': 'ਫੇਕ',
    'Tuensang': 'ਤੁਇੰਸਾਂਗ',
    'Wokha': 'ਵੋਖਾ',
    'Zunheboto': 'ਜ਼ੁਨਹੇਬੋਟੋ',
    'Angul': 'ਅੰਗੁਲ',
    'Balangir': 'ਬਾਲਾਂਗੀਰ',
    'Balasore': 'ਬਾਲਾਸੋਰ',
    'Bargarh': 'ਬਰਗੜ',
    'Bhadrak': 'ਭਦਰਕ',
    'Boudh': 'ਬੌਧ',
    'Cuttack': 'ਕਟਕ',
    'Deogarh': 'ਦੇਵਗੜ',
    'Dhenkanal': 'ਧੇਨਕਨਾਲ',
    'Gajapati': 'ਗਜਪਤੀ',
    'Ganjam': 'ਗੰਜਾਮ',
    'Jagatsinghpur': 'ਜਗਤਸਿੰਘਪੁਰ',
    'Jajpur': 'ਜਾਜਪੁਰ',
    'Jharsuguda': 'ਝਾਰਸੁਗੁੜਾ',
    'Kalahandi': 'ਕਲਾਹਾਂਡੀ',
    'Kandhamal': 'ਕੰਧਮਾਲ',
    'Kendrapara': 'ਕੇਂਦ੍ਰਾਪੜਾ',
    'Kendujhar': 'ਕੇਂਦ੍ਰੁਝਰ',
    'Khordha': 'ਖੋਰਧਾ',
    'Koraput': 'ਕੋਰਾਪੁਟ',
    'Malkangiri': 'ਮਲਕਾਂਗੀਰੀ',
    'Mayurbhanj': 'ਮਯੂਰਭੰਜ',
    'Nabarangpur': 'ਨਬਰੰਗਪੁਰ',
    'Nayagarh': 'ਨਯਾਗੜ੍ਹ',
    'Nuapada': 'ਨੂਆਪਾਡਾ',
    'Puri': 'ਪੁਰੀ',
    'Rayagada': 'ਰਾਯਗੜਾ',
    'Sambalpur': 'ਸੰਬਲਪੁਰ',
    'Subarnapur': 'ਸੁਬਰਨਾਪੁਰ',
    'Sundergarh': 'ਸੁੰਦਰਗੜ',
    'Puducherry': 'ਪੁਡੂਚੇਰੀ',
    'Karaikal': 'ਕਾਰਾਇਕਾਲ',
    'Mahe': 'ਮਾਹੇ',
    'Yanam': 'ਯਾਨਮ',
    'Amritsar': 'ਅੰਮ੍ਰਿਤਸਰ',
    'Barnala': 'ਬਰਨਾਲਾ',
    'Bathinda': 'ਬਠਿੰਡਾ',
    'Faridkot': 'ਫ਼ਰੀਦਕੋਟ',
    'Fatehgarh Sahib': 'ਫ਼ਤਿਹਗੜ੍ਹ ਸਾਹਿਬ',
    'Fazilka': 'ਫ਼ਾਜ਼ਿਲਕਾ',
    'Ferozepur': 'ਫ਼ਿਰੋਜ਼ਪੁਰ',
    'Gurdaspur': 'ਗੁਰਦਾਸਪੁਰ',
    'Hoshiarpur': 'ਹੋਸ਼ਿਆਰਪੁਰ',
    'Jalandhar': 'ਜਲੰਧਰ',
    'Kapurthala': 'ਕਪੂਰਥਲਾ',
    'Ludhiana': 'ਲੁਧਿਆਣਾ',
    'Malerkotla': 'ਮਲੇਰਕੋਟਲਾ',
    'Mansa': 'ਮਾਨਸਾ',
    'Moga': 'ਮੋਗਾ',
    'Mohali': 'ਮੋਹਾਲੀ',
    'Muktsar': 'ਮੁਕਤਸਰ',
    'Pathankot': 'ਪਠਾਨਕੋਟ',
    'Patiala': 'ਪਟਿਆਲਾ',
    'Rupnagar': 'ਰੂਪਨਗਰ',
    'Sangrur': 'ਸੰਗਰੂਰ',
    'Shaheed Bhagat Singh Nagar': 'ਸ਼ਹੀਦ ਭਗਤ ਸਿੰਘ ਨਗਰ',
    'Tarn Taran': 'ਤਰਨ ਤਾਰਨ',
    'Ajmer': 'ਅਜਮੇਰ',
    'Alwar': 'ਅਲਵਰ',
    'Banswara': 'ਬਾਂਸਵਾਰਾ',
    'Baran': 'ਬਾਰਾਂ',
    'Barmer': 'ਬਾਰਮਰ',
    'Bharatpur': 'ਭਰਤਪੁਰ',
    'Bhilwara': 'ਭੀਲਵਾਰਾ',
    'Bikaner': 'ਬੀਕਾਨੇਰ',
    'Bundi': 'ਬੂੰਦੀ',
    'Chittorgarh': 'ਚਿੱਤੌਰਗੜ੍ਹ',
    'Churu': 'ਚੂਰੂ',
    'Dausa': 'ਦੌਸਾ',
    'Dholpur': 'ਧੌਲਪੁਰ',
    'Dungarpur': 'ਡੂੰਗਰਪੁਰ',
    'Hanumangarh': 'ਹਨੂਮਾਨਗੜ੍ਹ',
    'Jaipur': 'ਜੈਪੁਰ',
    'Jaisalmer': 'ਜੈਸਲਮੇਰ',
    'Jalore': 'ਜਾਲੋਰ',
    'Jhalawar': 'ਝਾਲਾਵਾੜ',
    'Jhunjhunu': 'ਝੁੰਝਨੂੰ',
    'Jodhpur': 'ਜੋਧਪੁਰ',
    'Karauli': 'ਕਰੌਲੀ',
    'Kota': 'ਕੋਟਾ',
    'Nagaur': 'ਨਾਗੌਰ',
    'Pali': 'ਪਾਲੀ',
    'Pratapgarh': 'ਪ੍ਰਤਾਪਗੜ੍ਹ',
    'Rajsamand': 'ਰਾਜਸਮੰਦ',
    'Sawai Madhopur': 'ਸਵਾਈ ਮਾਧੋਪੁਰ',
    'Sikar': 'ਸੀਕਰ',
    'Sirohi': 'ਸੀਰੋਹੀ',
    'Sri Ganganagar': 'ਸ਼੍ਰੀ ਗੰਗਾਨਗਰ',
    'Tonk': 'ਟੋਂਕ',
    'Udaipur': 'ਉਦੈਪੁਰ',
    'East Sikkim': 'ਪੂਰਬ ਸਿੱਕਿਮ',
    'North Sikkim': 'ਉੱਤਰ ਸਿੱਕਿਮ',
    'South Sikkim': 'ਦੱਖਣ ਸਿੱਕਿਮ',
    'West Sikkim': 'ਪੱਛਮੀ ਸਿੱਕਿਮ',
    'Ariyalur': 'ਅਰਿਆਲੂਰ',
    'Chengalpattu': 'ਚੇਂਗਲਪੱਟੂ',
    'Chennai': 'ਚੇਨਈ',
    'Coimbatore': 'ਕੋਇੰਬਤੂਰ',
    'Cuddalore': 'ਕੁਡਾਲੋਰ',
    'Dharmapuri': 'ਧਰਮਪੁਰੀ',
    'Dindigul': 'ਡਿੰਡੀਗੁਲ',
    'Erode': 'ਈਰੋਡੇ',
    'Kallakurichi': 'ਕੱਲਾਕੁਰੀਚੀ',
    'Kancheepuram': 'ਕਾਂਚੀਪੁਰਮ',
    'Kanyakumari': 'ਕੰਨਿਆਕੁਮਾਰੀ',
    'Karur': 'ਕਰੂਰ',
    'Krishnagiri': 'ਕ੍ਰਿਸ਼ਨਗਿਰੀ',
    'Madurai': 'ਮਦੁਰਾਈ',
    'Mayiladuthurai': 'ਮੈਯਿਲਾਦੁਥੁਰਾਈ',
    'Nagapattinam': 'ਨਾਗਪੱਟਿਨਮ',
    'Namakkal': 'ਨਮੱਕਲ',
    'Nilgiris': 'ਨੀਲਗਿਰੀ',
    'Perambalur': 'ਪੇਰੰਬਲੂਰ',
    'Pudukkottai': 'ਪੁਡੁਕੋਟਾਈ',
    'Ramanathapuram': 'ਰਾਮਨਾਥਪੁਰਮ',
    'Ranipet': 'ਰਾਨੀਪੇਟ',
    'Salem': 'ਸੇਲਮ',
    'Sivaganga': 'ਸਿਵਗੰਗਾ',
    'Tenkasi': 'ਤੇਨਕਾਸੀ',
    'Thanjavur': 'ਤੰਜਾਵੂਰ',
    'Theni': 'ਥੇਨੀ',
    'Thoothukudi': 'ਥੂਥੁਕੁਡੀ',
    'Tiruchirappalli': 'ਤਿਰੁਚਿਰਾਪੱਲੀ',
    'Tirunelveli': 'ਤਿਰੁਨੇਲਵੇਲੀ',
    'Tiruvallur': 'ਤਿਰੁਵੱਲੂਰ',
    'Tiruvannamalai': 'ਤਿਰੁਵੰਨਾਮਲਈ',
    'Tiruvarur': 'ਤਿਰੁਵਾਰੂਰ',
    'Vellore': 'ਵੇਲਲੋਰ',
    'Viluppuram': 'ਵਿਲੁਪੁਰਮ',
    'Virudhunagar': 'ਵਿਰੁਧੁਨਗਰ',
    'Adilabad': 'ਅਦਿਲਾਬਾਦ',
    'Bhadradri Kothagudem': 'ਭਦਰਾਦ੍ਰੀ ਕੋਠਾਗੁਡੇਮ',
    'Hanamkonda': 'ਹਨਮਕੋਂਡਾ',
    'Hyderabad': 'ਹੈਦਰਾਬਾਦ',
    'Jagtial': 'ਜਗਤਿਆਲ',
    'Jangaon': 'ਜੰਗਾਂਵ',
    'Jayashankar Bhupalpally': 'ਜਯਸ਼ੰਕਰ ਭੂਪਾਲਪੱਲੀ',
    'Jogulamba Gadwal': 'ਜੋਗੁਲੰਬਾ ਗਡਵਾਲ',
    'Kamareddy': 'ਕਾਮਾਰੈੱਡੀ',
    'Karimnagar': 'ਕਰੀਮਨਗਰ',
    'Khammam': 'ਖੰਮਮ',
    'Kumuram Bheem Asifabad': 'ਕੋਮਰਾਮ ਵੀਮ ਆਸੀਫਾਬਾਦ',
    'Mahabubabad': 'ਮਹਬੂਬਾਬਾਦ',
    'Mahabubnagar': 'ਮਹਬੂਬਨਗਰ',
    'Mancherial': 'ਮੰਚੇਰੀਆਲ',
    'Medak': 'ਮੇਡਕ',
    'Medchal-Malkajgiri': 'ਮੇਡਚਲ-ਮਲਕਾਜਗਿਰੀ',
    'Mulugu': 'ਮੁਲੁਗੂ',
    'Nagarkurnool': 'ਨਗਰਕੁਰਨੂਲ',
    'Nalgonda': 'ਨਾਲਗੋਂਡਾ',
    'Narayanpet': 'ਨਾਰਾਇਣਪੇਟ',
    'Nirmal': 'ਨਿਰਮਲ',
    'Nizamabad': 'ਨਿਜਾਮਾਬਾਦ',
    'Peddapalli': 'ਪੇਡਾਪੱਲੀ',
    'Rajanna Sircilla': 'ਰਾਜੰਨਾ ਸਿਰਸੀਲਾ',
    'Ranga Reddy': 'ਰੰਗਾ ਰੈੱਡੀ',
    'Sangareddy': 'ਸੰਗਾ ਰੈੱਡੀ',
    'Siddipet': 'ਸਿੱਦੀਪੇਟ',
    'Suryapet': 'ਸੂਰਿਆਪੇਟ',
    'Vikarabad': 'ਵਿਕਾਰਾਬਾਦ',
    'Wanaparthy': 'ਵਨਾਪਾਰਥੀ',
    'Warangal Urban': 'ਵਾਰੰਗਲ ਅਰਬਨ',
    'Warangal Rural': 'ਵਾਰੰਗਲ ਰੂਰਲ',
    'Yadadri Bhuvanagiri': 'ਯਾਦਾਦ੍ਰੀ ਭੁਵਨਗੀਰੀ',
    'Dhalai': 'ਧਲਾਈ',
    'Gomati': 'ਗੋਮਤੀ',
    'Khowai': 'ਖੋਵਾਈ',
    'North Tripura': 'ਉੱਤਰੀ ਤ੍ਰਿਪੁਰਾ',
    'Sepahijala': 'ਸੇਪਾਹਿਜਲਾ',
    'South Tripura': 'ਦੱਖਣੀ ਤ੍ਰਿਪੁਰਾ',
    'Unakoti': 'ਉਨਕੋਟੀ',
    'West Tripura': 'ਪੱਛਮੀ ਤ੍ਰਿਪੁਰਾ',
    'Agra': 'ਆਗਰਾ',
    'Aligarh': 'ਅਲੀਗੜ੍ਹ',
    'Ambedkar Nagar': 'ਅੰਬੇਡਕਰ ਨਗਰ',
    'Amethi': 'ਅਮੇਠੀ',
    'Amroha': 'ਅਮਰੋਹਾ',
    'Auraiya': 'ਉਰਈਆ',
    'Ayodhya': 'ਅਯੋਧਿਆ',
    'Azamgarh': 'ਅਜ਼ਮਗੜ੍ਹ',
    'Badaun': 'ਬਦਾਯੂੰ',
    'Baghpat': 'ਬਾਗਪਤ',
    'Bahraich': 'ਬਹਿਰਾਈਚ',
    'Ballia': 'ਬਲੀਆ',
    'Banda': 'ਬਾਂਦਾ',
    'Barabanki': 'ਬਾਰਾਬੰਕੀ',
    'Bareilly': 'ਬਰੇਲੀ',
    'Basti': 'ਬਸਤੀ',
    'Bhadohi': 'ਭਦੋਹੀ',
    'Bijnor': 'ਬਿਜਨੌਰ',
    'Budaun': 'ਬਦਾਯੂੰ',
    'Bulandshahr': 'ਬੁਲੰਦਸ਼ਹਿਰ',
    'Chandauli': 'ਚੰਦੌਲੀ',
    'Chitrakoot': 'ਚਿੱਤਰਕੂਟ',
    'Deoria': 'ਦੇਵਰਿਆ',
    'Etah': 'ਏਟਾ',
    'Etawah': 'ਇਟਾਵਾ',
    'Farrukhabad': 'ਫਰੁਖਾਬਾਦ',
    'Fatehpur': 'ਫਤਿਹਪੁਰ',
    'Firozabad': 'ਫਿਰੋਜ਼ਾਬਾਦ',
    'Gautam Buddha Nagar': 'ਗੌਤਮ ਬੁੱਧ ਨਗਰ',
    'Ghaziabad': 'ਗਾਜ਼ੀਅਾਬਾਦ',
    'Ghazipur': 'ਗਾਜ਼ੀਪੁਰ',
    'Gonda': 'ਗੋਂਡਾ',
    'Gorakhpur': 'ਗੋਰਖਪੁਰ',
    'Hapur': 'ਹਾਪੁਰ',
    'Hardoi': 'ਹਰਦੋਈ',
    'Hathras': 'ਹਾਥਰਸ',
    'Jalaun': 'ਜਾਲੌਨ',
    'Jaunpur': 'ਜੌਨਪੁਰ',
    'Jhansi': 'ਝਾਂਸੀ',
    'Kannauj': 'ਕੰਨੌਜ',
    'Kanpur Dehat': 'ਕਾਨਪੁਰ ਦੇਹਾਤ',
    'Kanpur Nagar': 'ਕਾਨਪੁਰ ਨਗਰ',
    'Kasganj': 'ਕਾਸਗੰਜ',
    'Kaushambi': 'ਕੌਸ਼ਾਮਬੀ',
    'Kushinagar': 'ਕੁਸ਼ੀਨਗਰ',
    'Kheri': 'ਖੇਰੀ',
    'Lalitpur': 'ਲਲਿਤਪੁਰ',
    'Lucknow': 'ਲਖਨਊ',
    'Maharajganj': 'ਮਹਾਰਾਜਗੰਜ',
    'Mahoba': 'ਮਹੋਬਾ',
    'Mainpuri': 'ਮੈਨਪੁਰੀ',
    'Mathura': 'ਮਥੁਰਾ',
    'Mau': 'ਮਊ',
    'Meerut': 'ਮੇਰਠ',
    'Mirzapur': 'ਮਿਰਜ਼ਾਪੁਰ',
    'Moradabad': 'ਮੁਰਾਦਾਬਾਦ',
    'Muzaffarnagar': 'ਮੁਜ਼ਫ਼ਰਨਗਰ',
    'Pilibhit': 'ਪੀਲੀਭੀਤ',
    'Prayagraj': 'ਪ੍ਰਯਾਗਰਾਜ',
    'Rae Bareli': 'ਰਾਏ ਬਰੇਲੀ',
    'Rampur': 'ਰਾਮਪੁਰ',
    'Saharanpur': 'ਸਹਾਰਨਪੁਰ',
    'Sambhal': 'ਸੰਭਲ',
    'Sant Kabir Nagar': 'ਸੰਤ ਕਬੀਰ ਨਗਰ',
    'Shahjahanpur': 'ਸ਼ਾਹਜਹਾਨਪੁਰ',
    'Shamli': 'ਸ਼ਾਮਲੀ',
    'Shrawasti': 'ਸ਼ਰਾਵਸਤ',
    'Siddharthnagar': 'ਸਿਦਾਰਥਨਗਰ',
    'Sitapur': 'ਸੀਤਾਪੁਰ',
    'Sonbhadra': 'ਸੋਨਭਦਰ',
    'Sultanpur': 'ਸੁਲਤਾਨਪੁਰ',
    'Unnao': 'ਉੰਨਾਓ',
    'Varanasi': 'ਵਾਰਾਣਸੀ',
    'Almora': 'ਅਲਮੋਰਾ',
    'Bageshwar': 'ਬਾਗੇਸ਼ਵਰ',
    'Chamoli': 'ਚਮੋਲੀ',
    'Champawat': 'ਚੰਪਾਵਤ',
    'Dehradun': 'ਦੇਹਰਾਦੂਨ',
    'Haridwar': 'ਹਰਿਦਵਾਰ',
    'Nainital': 'ਨੈਨੀਤਾਲ',
    'Pauri Garhwal': 'ਪੌੜੀ ਗੜਵਾਲ',
    'Pithoragarh': 'ਪਿਥੌਰਾਗੜ੍ਹ',
    'Rudraprayag': 'ਰੁਦ੍ਰਪ੍ਰਯਾਗ',
    'Tehri Garhwal': 'ਟਿਹਰੀ ਗੜਵਾਲ',
    'Udham Singh Nagar': 'ਉਧਮ ਸਿੰਘ ਨਗਰ',
    'Uttarkashi': 'ਉੱਤਰਕਾਸ਼ੀ',
    'Alipurduar': 'ਅਲੀਪੁਰਦੁਆਰ',
    'Bankura': 'ਬਾਂਕੂੜਾ',
    'Birbhum': 'ਬੀਰਭੂਮ',
    'Cooch Behar': 'ਕੂਚਬਿਹਾਰ',
    'Darjeeling': 'ਦਾਰਜੀਲਿੰਗ',
    'East Bardhaman': 'ਪੂਰਬ ਬਰਧਮਾਨ',
    'East Medinipur': 'ਪੂਰਬ ਮੇਦਿਨੀਪੁਰ',
    'Hooghly': 'ਹੂਗਲੀ',
    'Howrah': 'ਹਾਵੜਾ',
    'Jalpaiguri': 'ਜਲਪਾਈਗੁੜੀ',
    'Jhargram': 'ਝਾਰਗ੍ਰਾਮ',
    'Kalimpong': 'ਕਾਲਿੰਪੌਂਗ',
    'Kolkata': 'ਕੋਲਕਾਤਾ',
    'Malda': 'ਮਾਲਦਾ',
    'Murshidabad': 'ਮੁਰਸ਼ਿਦਾਬਾਦ',
    'Nadia': 'ਨਾਦੀਆ',
    'North 24 Parganas': 'ਉੱਤਰੀ 24 ਪਰਗਣਾ',
    'Dakshin Dinajpur': 'ਦੱਖਣ ਦਿਨਾਜਪੁਰ',
    'Purba Bardhaman': 'ਪੂਰਬ ਬਰਧਮਾਨ',
    'Purba Medinipur': 'ਪੂਰਬ ਮੇਦਿਨੀਪੁਰ',
    'Purulia': 'ਪੁਰੁਲੀਆ',
    'South 24 Parganas': 'ਦੱਖਣ 24 ਪਰਗਣਾ',
    'Uttar Dinajpur': 'ਉੱਤਰ ਦਿਨਾਜਪੁਰ',
    'West Bardhaman': 'ਪੱਛਮੀ ਬਰਧਮਾਨ',
  })
  ..addAll({
    'Sorghum': 'ਜੋਵਾਰ',
    "SORGHUM": 'ਜੋਵਾਰ',
    "Seed Rate and Sowing Method": "ਬੀਜ ਦੀ ਦਰ ਅਤੇ ਬੋਨੇ ਦਾ ਤਰੀਕਾ",
    "The crop is sown in rows of 30cm (single cut) to 45 cm (multi cut) apart with a plant to plant spacing of 15 cm. For sorghum 50-60 kg/ha seed is sufficient,sown at a depth of 2-5 cm.":
        "ਫਸਲ ਇੱਕ ਰੋਟ 30 ਸੈਂਟੀਮੀਟਰ (ਇੱਕਲਾ ਕੱਟ) ਤੋਂ 45 ਸੈਂਟੀਮੀਟਰ (ਬਹੁ ਕੱਟ) ਦੀ ਦੂਰੀ ਵਿੱਚ ਅੱਡੀ ਜਾਂਦੀ ਹੈ, ਅਤੇ ਹਰ ਪੌਦੇ ਦੀ ਦੂਰੀ ਇੱਕ ਦੂਜੇ ਤੋਂ 15 ਸੈਂਟੀਮੀਟਰ ਹੈ। ਜੋਵਾਰ ਲਈ 50-60 ਕਿਲੋਗਰਾਮ/ਹੈਕਟੇਅਰ ਪ੍ਰਤੀ ਬੀਜ ਕਾਫ਼ੀ ਹੈ, ਜੋ 2-5 ਸੈਂਟੀਮੀਟਰ ਗਹਿਰਾਈ 'ਤੇ ਬੋਆ ਜਾਂਦਾ ਹੈ। ",
    "Sowing Time": "ਬੋਣ ਦਾ ਸਮਾ",
    "Summer:20 March to 10 April": "ਗਰਮੀ: 20 ਮਾਰਚ ਤੋਂ 10 ਅਪ੍ਰੈਲ",
    "Kharif:25 June to 10 July": "ਖਰੀਫ: 25 ਜੂਨ ਤੋਂ 10 ਜੁਲਾਈ।",
    "Single cut: HC 136, HC171, HC260, HC308":
        "ਇੱਕ ਵਾਰੀ ਕੱਟ: HC 136, HC 171, HC 260, HC 308",
    "Multicut: Sweet sudan grass 59-3; Dual purpose: HJ 513":
        "ਬਹੁਕੱਟ: ਮਿੱਠਾ ਸੂਡਾਨ ਘਾਸ 59-3; ਦੋਵਾਂ ਉਦੇਸ਼: HJ 513",
    "FYM application @ 10 (rainfed) to 25 t/ha (irrigated) before sowing.Crop is fertilized with 80-40-0 (single cut), 120-60-0 (double cut) and 210-60-60 (multi cut)kg/ha of NPK, respectively.":
        "ਬਿਜਾਈ ਤੋਂ ਪਹਿਲਾਂ 10 (ਬਰਸਾਤੀ ਖੇਤਰ) ਤੋਂ 25 ਟਨ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ (ਸਿੰਚਿਤ ਖੇਤਰ) ਤੱਕ ਦੇ ਗੋਬਰ ਦੀ ਖਾਦ ਦੀ ਅਰਜ਼ੀ। ਫ਼ਸਲ ਨੂੰ 80-40-0 (ਇੱਕ ਕੱਟ), 120-60-0 (ਦੋਹਰਾ ਕੱਟ) ਅਤੇ 210-60-60 (ਕਈ ਕੱਟ) ਕਿਲੋਗ੍ਰਾਮ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ NPK ਦੇ ਨਾਲ ਖਾਦ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ।",
    "One hand weeding 15-20 DAS is necessary. For chemical weed control apply atrazine @ 500g/ha between 7-15 days after sowing using 625 L of water.":
        "ਬੋਵਾਈ ਦੇ 15-20 ਦਿਨ ਬਾਅਦ ਇੱਕ ਵਾਰੀ ਹੱਥ ਨਾਲ ਨਦੀਨ ਸਾਫ ਕਰਨਾ ਜਰੂਰੀ ਹੈ। ਰਸਾਇਣਕ ਜੰਗਲੀ ਘਾਸ ਨਿਯੰਤਰਣ ਲਈ, ਬੋਵਾਈ ਤੋਂ 7-15 ਦਿਨ ਬਾਅਦ 625 ਲੀਟਰ ਪਾਣੀ ਨਾਲ 500 ਗ੍ਰਾਮ/ਹੇਕਟੇਅਰ ਐਟਰੇਜ਼ਿਨ ਪਾਓ।",
    "Downy mildew: seed treatment with Agrosan GN or Ceresan @ 4 g/ kg seed and spray of Dithane Z 78 (0.2%) to reduce secondary infection;":
        "ਡਾਊਨੀ ਫ਼ਫ਼ੂੰਦੀ: ਦੂਸਰੀ ਲਾਗ ਨੂੰ ਘਟਾਉਣ ਲਈ ਐਗਰੋਸਾਨ ਜੀਐਨ ਜਾਂ ਸੇਰੇਸਨ @ 4 ਗ੍ਰਾਮ/ਕਿਲੋ ਬੀਜ ਨਾਲ ਬੀਜ ਦਾ ਇਲਾਜ ਅਤੇ ਡਾਇਥੇਨ ਜ਼ੈਡ 78 (0.2%) ਦੀ ਸਪਰੇਅ",
    "Anthracnose: Seed treatment with Agrosan GN @ 3 g/kg seed followed by spray of Zineb (0.2%) at 10 days interval starting from 35 DAS.":
        "ਐਂਥ੍ਰੈਕਨੋਸ: ਐਗਰੋਸਨ ਜੀਐਨ @ 3 ਗ੍ਰਾਮ/ਕਿਲੋ ਬੀਜ ਨਾਲ ਬੀਜ ਦਾ ਇਲਾਜ 35 ਡੀਏਐਸ ਤੋਂ ਸ਼ੁਰੂ ਕਰਦੇ ਹੋਏ 10 ਦਿਨਾਂ ਦੇ ਅੰਤਰਾਲ 'ਤੇ ਜ਼ੀਨਬ (0.2%) ਦੀ ਸਪਰੇਅ ਕਰੋ।",
    "Sorghum shoot fly - Application of Carbaryl 10 G or Phorate 10 G @ 5.0 kg/ha is effective in borer management. Early sowing (1st week of June) may avoid shoot fly attack.":
        "ਸੋਰਘਮ ਸ਼ੂਟ ਫਲਾਈ- ਕਾਰਬਰਿਲ 10 ਜੀ ਜਾਂ ਫੋਰੇਟ 10 ਜੀ @ 5.0 ਕਿਲੋਗ੍ਰਾਮ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਦੀ ਵਰਤੋਂ ਬੋਰਰ ਪ੍ਰਬੰਧਨ ਵਿੱਚ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ। ਅਗੇਤੀ ਬਿਜਾਈ (ਜੂਨ ਦੇ ਪਹਿਲੇ ਹਫ਼ਤੇ) ਸ਼ੂਟ ਫਲਾਈ ਦੇ ਹਮਲੇ ਤੋਂ ਬਚਾਉਂਦੀ ਹੈ। ",
    "Stem borer- Foliar spray of Carbaryl 50 WP in 500 litre water per hectare after 20 days of sowing and repeat spray 10 days after spray is effective in borer management.":
        "ਸਟੇਮ ਬੋਰਰ- ਬਿਜਾਈ ਤੋਂ 20 ਦਿਨਾਂ ਬਾਅਦ ਕਾਰਬਰਿਲ 50 ਡਬਲਯੂਪੀ 500 ਲੀਟਰ ਪਾਣੀ ਵਿੱਚ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਵਿੱਚ ਘੋਲ ਕੇ ਸਪਰੇਅ ਕਰੋ ਅਤੇ 10 ਦਿਨਾਂ ਬਾਅਦ ਦੁਹਰਾਓ ਸਪਰੇਅ ਬੋਰਰ ਪ੍ਰਬੰਧਨ ਵਿੱਚ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ।",
    "Harvesting": "ਕਟਾਈ",
    "Single cut varieties are harvested at 50-100% flowering stage. In multi cut varieties,the first cut is taken 55 DAS and the subsequent at 40 days interval. In multi cut varieties, first cut should be taken 8-10 cm above ground level so as to facilitate profuse tillering.":
        "ਸਿੰਗਲ ਕੱਟ ਵਾਲੀਆਂ ਕਿਸਮਾਂ ਦੀ ਕਟਾਈ 50-100% ਫੁੱਲਾਂ ਦੇ ਪੜਾਅ 'ਤੇ ਕੀਤੀ ਜਾਂਦੀ ਹੈ। ਮਲਟੀ ਕੱਟ ਵਰਾਇਟੀਆਂ ਵਿੱਚ, ਪਹਿਲਾ ਕੱਟ 55 ਦਿਨ ਬਾਅਦ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਅਤੇ ਅਗਲੇ ਕੱਟ 40 ਦਿਨ ਦੇ ਅੰਤਰਾਲ 'ਤੇ ਕੀਤੇ ਜਾਂਦੇ ਹਨ। ਮਲਟੀ ਕੱਟ ਵਰਾਇਟੀਆਂ ਵਿੱਚ, ਪਹਿਲਾ ਕੱਟ ਜਮੀਨ ਦੀ ਸਤਹ ਤੋਂ 8-10 ਸੈਂਟੀਮੀਟਰ ਉੱਪਰ ਲੈਣਾ ਚਾਹੀਦਾ ਹੈ ਤਾਂ ਜੋ ਵਧੀਆ ਟਿੱਲੇਰਿੰਗ ਨੂੰ ਸੁਹਾਲਾ ਕੀਤਾ ਜਾ ਸਕੇ। ",
    "Hydrocyanic acid (HCN) or Dhurin": "ਹਾਈਡ੍ਰੋਕਾਇਨਿਕ ਐਸਿਡ (HCN) ਜਾਂ ਧੂਰਿਨ",
    "The crop at early stages contains HCN. Harvesting should not be done prior to 45 days from sowing. Silage or hay making removes the toxin. In summer, an irrigation before harvest may be effective. For hay making, pre-flowering is ideal stage for harvest. Do not turn hungry livestock out on lush regrowth of sorghum; do not graze until the regrowth is 18 to 24 inches tall.":
        "ਪਹਿਲੇ ਪੜਾਅ ਵਿੱਚ ਫਸਲ ਵਿੱਚ HCN ਹੁੰਦਾ ਹੈ। ਬਿਜਾਈ ਤੋਂ 45 ਦਿਨ ਪਹਿਲਾਂ ਕਟਾਈ ਨਹੀਂ ਕਰਨੀ ਚਾਹੀਦੀ। ਸਿਲੇਜ ਜਾਂ ਪਰਾਗ ਬਣਾਉਣਾ ਜ਼ਹਿਰੀਲੇ ਤੱਤਾਂ ਨੂੰ ਦੂਰ ਕਰਦਾ ਹੈ। ਗਰਮੀ ਦੇ ਮੌਸਮ ਵਿੱਚ, ਕੱਟਾਈ ਤੋਂ ਪਹਿਲਾਂ ਸਿੰਚਾਈ ਲਾਭਦਾਇਕ ਹੋ ਸਕਦੀ ਹੈ। ਹੈ ਬਣਾਉਣ ਲਈ, ਬੋਵਾਈ ਤੋਂ ਪਹਿਲਾਂ ਫੁੱਲਣ ਦਾ ਸਟੇਜ ਸਭ ਤੋਂ ਉੱਤਮ ਹੈ। ਭੁੱਖੇ ਪਸ਼ੂਆਂ ਨੂੰ ਸ਼ੋਰਘਮ ਦੇ ਹਰੀ-ਭਰੀ ਮੁੜ ਵਾਧੇ 'ਤੇ ਨਾ ਛੱਡੋ; ਜਦੋਂ ਤੱਕ ਦੁਬਾਰਾ ਵਾਧਾ 18 ਤੋਂ 24 ਇੰਚ ਲੰਬਾ ਨਹੀਂ ਹੁੰਦਾ ਉਦੋਂ ਤੱਕ ਚਰ ਨਾ ਕਰੋ।",
    "Maize": "ਮੱਕੀ",
    "MAIZE": 'ਮੱਕੀ',
    "Seed Rate and Sowing Time": "बीज दर और बुवाई का समय",
    "40-50 kg seed/ha at 5 cm depth with 60 cm row to row spacing and 10 cm spacing between crops":
        "40-50 ਕਿਲੋ ਬੀਜ/ਹੈਕਟੇਅਰ 5 ਸੈਂਟੀਮੀਟਰ ਡੂੰਘਾਈ 'ਤੇ 60 ਸੈਂਟੀਮੀਟਰ ਕਤਾਰ ਤੋਂ ਕਤਾਰ ਦੀ ਦੂਰੀ ਅਤੇ ਫਸਲਾਂ ਵਿਚਕਾਰ 10 ਸੈਂਟੀਮੀਟਰ ਦੀ ਦੂਰੀ।",
    "Varieties": "ਕਿਸਮਾਂ",
    "African Tall, APFM-8, Pratap Makka, Chari 6,Ganga-4, J-1006.":
        "ਅਫਰੀਕਨ ਟਾਲ, ਏਪੀਐਫਐਮ-8, ਪ੍ਰਤਾਪ ਮੱਕਾ, ਚਾਰੀ 6, ਗੰਗਾ-4, ਜੇ-1006।",
    "Manures and Fertilizers": "ਖਾਦਾਂ ਅਤੇ ਖੇਤੀਬਾੜੀ ਉਰਵਰਕ",
    "15-30 kg Nitrogen (N), 40-60 kg Phosphorus (P), 40 kg Potassium (K) and 20 kg Zinc sulphate before planting and 60-90 kg N when the crop is 50-60 cm tall. 15 tons of FYM/hac applied a month before planting.":
        "ਬੋਵਾਈ ਤੋਂ ਪਹਿਲਾਂ 15-30 ਕਿਲੋਗ੍ਰਾਮ ਨਾਈਟ੍ਰੋਜਨ (N), 40-60 ਕਿਲੋਗ੍ਰਾਮ ਫਾਸਫੋਰਸ (P), 40 ਕਿਲੋਗ੍ਰਾਮ ਪੋਟਾਸਿਯਮ (K) ਅਤੇ 20 ਕਿਲੋਗ੍ਰਾਮ ਜ਼ਿੰਕ ਸਲਫੇਟ ਵਰਤੋ ਅਤੇ ਜਦੋਂ ਫਸਲ 50-60 ਸੈਂਟੀਮੀਟਰ ਲੰਬੀ ਹੋਵੇ, ਤਾਂ 60-90 ਕਿਲੋਗ੍ਰਾਮ N ਦਿਓ। ਬੋਵਾਈ ਤੋਂ ਇੱਕ ਮਹੀਨਾ ਪਹਿਲਾਂ 15 ਟਨ FYM/ਹੇਕਟੇਅਰ ਪਾਓ।",
    "Irrigation": "ਸਿੰਚਾਈ",
    "1 or 2 irrigations at critical stages. Flowering and grain-filling stages are most critical; Irrigation every 15-20 days in the rainy season and every 10-12 days in the summer":
        "ਨਾਜ਼ੁਕ ਪੜਾਵਾਂ 'ਤੇ 1 ਜਾਂ 2 ਸਿੰਚਾਈਆਂ। ਫੁੱਲ ਅਤੇ ਅਨਾਜ ਭਰਨ ਦੇ ਪੜਾਅ ਸਭ ਤੋਂ ਨਾਜ਼ੁਕ ਹੁੰਦੇ ਹਨ; ਬਰਸਾਤ ਦੇ ਮੌਸਮ ਵਿੱਚ ਹਰ 15-20 ਦਿਨਾਂ ਬਾਅਦ ਅਤੇ ਗਰਮੀਆਂ ਵਿੱਚ ਹਰ 10-12 ਦਿਨਾਂ ਬਾਅਦ ਸਿੰਚਾਈ ਕਰੋ।",
    "For fodder purpose, the milk to early dough stage is preferred for higher yield and protein content. For silage, late dough stage is preferred.":
        "ਚਾਰੇ ਲਈ, ਵਧੇਰੇ ਉਪਜ ਅਤੇ ਪ੍ਰੋਟੀਨ ਸਮੱਗਰੀ ਲਈ ਦੂਧ ਤੋਂ ਸ਼ੁਰੂਆਤੀ ਗੂੰਦ ਦੇ ਪੜਾਅ ਨੂੰ ਤਰਜੀਹ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ। ਸਾਇਲੇਜ ਲਈ, ਦੇਰੀ ਦੇ ਗੂੰਦ ਦੇ ਪੜਾਅ ਨੂੰ ਤਰਜੀਹ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ।",
    "Oats": "ਜਵੀ",
    'OATS': 'ਜਵੀ',
    "75 kg/ha seed for small seeded varieties, while for bold seeded varieties 100 kg/ha. It can be planted with kera or pora method depending upon the moisture availability. It is always better to sow the crop with seed cum fertilizer drill by maintaining row to row distance of 25 cm. The optimum sowing time is mid-October to mid-November.":
        "ਛੋਟੇ ਬੀਜ ਵਾਲੀਆਂ ਕਿਸਮਾਂ ਲਈ 75 ਕਿਲੋ/ਹੈਕਟੇਅਰ ਬੀਜ, ਜਦਕਿ ਵੱਡੇ ਬੀਜ ਵਾਲੀਆਂ ਕਿਸਮਾਂ ਲਈ 100 ਕਿਲੋ/ਹੈਕਟੇਅਰ। ਇਸਨੂੰ ਨਮੀ ਦੀ ਉਪਲਬਧਤਾ ਦੇ ਅਨੁਸਾਰ ਕੈਰਾ ਜਾਂ ਪੋਰਾ ਤਰੀਕੇ ਨਾਲ ਲਗਾਇਆ ਜਾ ਸਕਦਾ ਹੈ। ਕਤਾਰ ਤੋਂ ਕਤਾਰ ਦੀ ਦੂਰੀ 25 ਸੈਂਟੀਮੀਟਰ ਬਣਾ ਕੇ ਬੀਜ-ਕਮ ਖਾਦ ਡਰਿੱਲ ਨਾਲ ਬੀਜਣਾ ਹਮੇਸ਼ਾ ਬਿਹਤਰ ਹੁੰਦਾ ਹੈ। ਬੋਵਾਈ ਦਾ ਸਭ ਤੋਂ ਵਧੀਆ ਸਮਾਂ ਅੱਧ ਅਕਤੂਬਰ ਤੋਂ ਅੱਧ ਨਵੰਬਰ ਤੱਕ ਹੈ।",
    "Varieties Recommended for Haryana": "ਹਰਿਆਣਾ ਲਈ ਸਿਫਾਰਸ਼ੀ ਕਿਸਮਾਂ",
    "Haryana Javi (HFO-114), OS-6, OS-7,Haryana Javi 8":
        "ਹਰਿਆਣਾ ਜਵੀ (HFO-114), OS-6, OS-7, ਹਰਿਆਣਾ ਜਵੀ 8",
    "Fertilizer Requirement": "ਖਾਦ ਦੀ ਲੋੜ",
    "40 kg N/ha at sowing and 40 kg N/ha at first irrigation. For multicut varieties 40 kg N/ha should also be applied after each cut.":
        "ਬੋਵਾਈ ਦੇ ਸਮੇਂ 40 ਕਿਲੋ ਨਾਈਟ੍ਰੋਜਨ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਅਤੇ ਪਹਿਲੀ ਸਿੰਚਾਈ 'ਤੇ 40 ਕਿਲੋ ਨਾਈਟ੍ਰੋਜਨ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ। ਮਲਟੀ-ਕੱਟ ਕਿਸਮਾਂ ਲਈ 40 ਕਿਲੋ ਨਾਈਟ੍ਰੋਜਨ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਵੀ ਹਰੇਕ ਕੱਟ ਤੋਂ ਬਾਅਦ ਪਾਉਣੀ ਚਾਹੀਦੀ ਹੈ।",
    "Irrigation should be applied at one month interval. Irrigation is essential after each cutting in order to promote the regeneration of the plants.":
        "ਸਿੰਚਾਈ ਇੱਕ ਮਹੀਨੇ ਦੇ ਅੰਤਰਾਲ 'ਤੇ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ। ਪੌਦਿਆਂ ਦੇ ਪੁਨਰਜਨਮ ਨੂੰ ਉਤਸ਼ਾਹਿਤ ਕਰਨ ਲਈ ਹਰ ਕਟਾਈ ਤੋਂ ਬਾਅਦ ਸਿੰਚਾਈ ਜ਼ਰੂਰੀ ਹੈ।",
    "Weed Management": "ਨਦੀਨ ਪ੍ਰਬੰਧਨ",
    "Weed management": "ਨਦੀਨ ਪ੍ਰਬੰਧਨ",
    "application of a broadleaf herbicide, such as 2,4-D sodium salt @ 1 kg/ha spray in 500 liter water at 35 DAS.":
        "35 ਦਿਨਾਂ ਬਾਅਦ (DAS) 'ਤੇ 500 ਲੀਟਰ ਪਾਣੀ ਵਿੱਚ 2,4-ਡੀ ਸੋਡੀਅਮ ਲੂਣ @ 1 ਕਿਲੋਗ੍ਰਾਮ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਸਪਰੇਅ ਵਰਗੀ ਇੱਕ ਚੌੜੀ ਪੱਤੀ ਵਾਲੀ ਜੜੀ-ਬੂਟੀਆਂ ਨਾਸ਼ਕ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "Disease and pest management": "ਰੋਗ ਅਤੇ ਕੀੜੇ ਪ੍ਰਬੰਧਨ",
    "Covered smut: Seed treatment with Emissan @ 2.5g/kg seed":
        "ਕਵਰਡ ਸਮੱਟ: ਐਮੀਸਨ @ 2.5 ਗ੍ਰਾਮ/ਕਿਲੋ ਬੀਜ ਨਾਲ ਬੀਜ ਦਾ ਇਲਾਜ ਕਰੋ",
    "Loose smut: Seed treatment with Vitavex or bavistin @ 2g/kg seed.":
        "ਢੀਲਾ ਸਮੱਟ: ਵਿਟਾਵੇਕਸ ਜਾਂ ਬਾਵਿਸਟਿਨ @ 2 ਗ੍ਰਾਮ/ਕਿਲੋ ਬੀਜ ਨਾਲ ਬੀਜ ਦਾ ਇਲਾਜ; ",
    "Aphid: Spray of plain water @ 400 l/ha, Application of malathion or endosulfan @ 0.05% in the patches of aphid colony.":
        "ਐਫੀਡ: ਐਫੀਡ ਕਲੋਨੀ ਦੇ ਪੈਚਾਂ ਵਿੱਚ ਸਾਦੇ ਪਾਣੀ ਦੀ @ 400 ਲੀਟਰ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ, ਮੈਲਾਥੀਓਨ ਜਾਂ ਐਂਡੋਸਲਫਾਨ @ 0.05% ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "Berseem": "ਬਰਸੀਮ",
    "BARSEEM": "ਬਰਸੀਮ",
    "End of September to end of October by broadcasting. Seed rate of 20 - 25 kg/ha is recommended. Mix 1 kg of Japani sarson/Chinese cabbage or 25 kg of oat seed for harvesting higher quantity of fodder at first cut.":
        "ਪ੍ਰਸਾਰਣ ਦੁਆਰਾ ਸਤੰਬਰ ਦੇ ਅੰਤ ਤੋਂ ਅਕਤੂਬਰ ਦੇ ਅੰਤ ਤੱਕ। ਬੀਜ ਦੀ ਦਰ 20-25 ਕਿਲੋ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ ਦੀ ਸਿਫਾਰਸ਼ ਕੀਤੀ ਜਾਂਦੀ ਹੈ। 1 ਕਿਲੋ ਜਾਪਾਨੀ ਸਰਸਨ/ਚੀਨੀ ਗੋਭੀ ਜਾਂ 25 ਕਿਲੋ ਜਵੀ ਦਾ ਬੀਜ ਪਹਿਲੀ ਕਟਾਈ 'ਤੇ ਚਾਰੇ ਦੀ ਵੱਧ ਮਾਤਰਾ ਲੈਣ ਲਈ ਮਿਲਾਓ।",
    "Mescavi, Hisar Berseem 1 and Hisar Berseem 2":
        "ਮੇਸਕਵੀ, ਹਿਸਾਰ ਬਰਸੀਮ 1 ਅਤੇ ਹਿਸਾਰ ਬਰਸੀਮ 2",
    "Fertilizer Management": "ਖਾਦ ਪ੍ਰਬੰਧਨ",
    "20 kg N + 70 kg P2O5 /ha before sowing of crop.":
        "ਫਸਲ ਦੀ ਬੋਵਾਈ ਤੋਂ ਪਹਿਲਾਂ 20 ਕਿਲੋ ਨਾਈਟ੍ਰੋਜਨ + 70 ਕਿਲੋ ਪੋਟਾਸਿਯਮ ਓਕਸਾਈਡ ਪ੍ਰਤੀ ਹੈਕਟੇਅਰ। ",
    "Irrigation management": "ਸਿੰਚਾਈ ਪ੍ਰਬੰਧਨ",
    "The first irrigation applied after 3-5 DAS in light soils (heavy soils, 8-10 days). Later on irrigate at 15-20 days interval.":
        "ਹਲਕੇ ਮਿੱਟੀ ਵਿੱਚ ਪਹਿਲੀ ਸਿੰਚਾਈ 3-5 ਦਿਨਾਂ ਬਾਅਦ (ਭਾਰੀ ਮਿੱਟੀ ਵਿੱਚ, 8-10 ਦਿਨਾਂ ਬਾਅਦ) ਲਾਗੂ ਕੀਤੀ ਜਾਂਦੀ ਹੈ। ਬਾਅਦ ਵਿੱਚ 15-20 ਦਿਨਾਂ ਦੇ ਅੰਤਰਾਲ 'ਤੇ ਸਿੰਚਾਈ ਕਰੋ। ",
    "Disease management": "ਬਿਮਾਰੀ ਪ੍ਰਬੰਧਨ",
    "Stem rot: Avoid excessive irrigation. Spray 0.1% solution of Bavistine twice during January and February at 15-20 days interval. Select disease resistant variety HB 1.Root rot: Seed treatment with Thiram, Bavistine and Carbofuran @ 2.5g/kg.":
        "ਜੜ੍ਹ ਸੜਨ:ਜ਼ਿਆਦਾ ਸਿੰਚਾਈ ਤੋਂ ਬਚੋ। ਜਨਵਰੀ ਅਤੇ ਫਰਵਰੀ ਦੇ ਦੌਰਾਨ 15-20 ਦਿਨਾਂ ਦੇ ਅੰਤਰਾਲ 'ਤੇ 0.1% ਬਾਵਿਸਟਿਨ ਦਾ ਛਿੜਕਾਅ ਦੋ ਵਾਰ ਕਰੋ। ਬਿਮਾਰੀ-ਰੋਧਕ ਕਿਸਮ HB 1 ਚੁਣੋ। ਜੜ੍ਹ ਸੜਨ: ਬੀਜ ਦਾ ਇਲਾਜ ਥੀਰਮ, ਬਾਵਿਸਟਾਈਨ ਅਤੇ ਕਾਰਬੋਫੁਰਾਨ @ 2.5 ਗ੍ਰਾਮ/ਕਿਲੋ ਨਾਲ ਕਰੋ।",
    "Insect Management": "ਕੀੜੇ ਪ੍ਰਬੰਧਨ",
    "Black ants: Apply Methyl Parathian 2% dust; White grass hopper: Spray malathion @1 lt/ha in 750 lts of water.":
        ": ਕਾਲੀਆਂ ਕੀੜੀਆਂ: ਮਿਥਾਇਲ ਪੈਰਾਥੀਅਨ 2% ਧੂੜ ਨੂੰ ਲਾਗੂ ਕਰੋ; ਵ੍ਹਾਈਟ ਗ੍ਰਾਸ ਹੌਪਰ: 750 ਲੀਟਰ ਪਾਣੀ ਵਿੱਚ ਮੈਲਾਥੀਓਨ @1 ਲੀਟਰ/ਹੈਕਟੇਅਰ ਦਾ ਛਿੜਕਾਅ ਕਰੋ।",
    "Cutting Management": "ਕਟਾਈ ਪ੍ਰਬੰਧਨ",
    "Harvested in 55-60 DAS and subsequent cuts after every 30 – 40 days.":
        "55-60 ਦਿਨਾਂ ਬਾਅਦ ਕਟਾਈ ਕੀਤੀ ਜਾਂਦੀ ਹੈ ਅਤੇ ਬਾਅਦ ਦੇ ਕੱਟ 30-40 ਦਿਨਾਂ ਦੇ ਅੰਤਰਾਲ ਕਰੋ।",
    "Toxicity": "ਜ਼ਹਰੀਲਾਪਣ",
    "A substance known as ‘astrogenons‘ is present in berseem, the excess of which makes the animal sick and causes bloat disease. Fodder should be sprayed with linseed or mustard oil. Mixing of dry fodder which contains more fiber like wheat straw also reduces the problem of bloating.":
        "ਬਰਸੀਮ ਵਿੱਚ 'ਐਸਟ੍ਰੋਜਨ ਨਾਮਕ ਇੱਕ ਪਦਾਰਥ ਮੌਜੂਦ ਹੁੰਦਾ ਹੈ, ਜਿਸ ਦੀ ਜ਼ਿਆਦਾ ਮਾਤਰਾ ਪਸ਼ੂ ਨੂੰ ਬਿਮਾਰ ਕਰ ਦਿੰਦੀ ਹੈ ਅਤੇ ਬਲੋਟ ਦੀ ਬਿਮਾਰੀ ਦਾ ਕਾਰਨ ਬਣਦੀ ਹੈ। ਚਾਰੇ 'ਤੇ ਅਲਸੀ ਜਾਂ ਸਰ੍ਹੋਂ ਦੇ ਤੇਲ ਦਾ ਛਿੜਕਾਅ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ। ਸੁੱਕੇ ਚਾਰੇ ਜਿਸ ਵਿਚ ਜ਼ਿਆਦਾ ਫਾਈਬਰ ਹੁੰਦਾ ਹੈ ਜਿਵੇਂ ਕਿ ਕਣਕ ਦੀ ਪਰਾਲੀ ਨੂੰ ਮਿਲਾ ਕੇ ਖਾਣ ਨਾਲ ਵੀ ਬਲੋਟਿੰਗ ਦੀ ਸਮੱਸਿਆ ਘੱਟ ਹੋ ਜਾਂਦੀ ਹੈ।",
    "Foot and Mouth disease in Buffalo":
        "ਮੱਝ ਅਤੇ ਗਾਂ ਵਿੱਚ ਪੈਰ ਅਤੇ ਮੂੰਹ ਦੀ ਬਿਮਾਰੀ",
    "Foot and Mouth disease": "ਪੈਰ ਅਤੇ ਮੂੰਹ ਦੀ ਬਿਮਾਰੀ",
    "Dripping saliva from the mouth": "ਮੂੰਹ ਵਿੱਚੋਂ ਥੁੱਕ ਦਾ ਟਪਕਣਾ",
    "Fever": "ਬੁਖਾਰ",
    "Blisters on mouth, tongue, gums, between hooves, udder and levee":
        "ਮੂੰਹ, ਜੀਭ, ਮਸੂੜਿਆਂ, ਖੁਰ, ਲੇਵੇ ਅਤੇ ਲੇਵੀ ਦੇ ਵਿਚਕਾਰ ਛਾਲੇ",
    "Reduces or stops animal feeding and chewing":
        "ਪਸ਼ੂ ਦੇ ਖਾਣੇ ਅਤੇ ਚਬਾਉਣ ਨੂੰ ਘਟਾ ਦਿੰਦਾ ਹੈ ਜਾਂ ਰੋਕ ਦਿੰਦਾ ਹੈ",
    "Animal walks with a limp especially when there are insects in the hooves":
        "ਪਸ਼ੂ ਲੰਗੜਾ ਕੇ ਚਲਦਾ ਹੈ, ਖਾਸ ਕਰਕੇ ਜਦੋਂ ਖੁਰਾਂ ਵਿੱਚ ਕੀੜੇ ਹੁੰਦੇ ਹਨ",
    "There is a sharp drop in milk production":
        "ਦੁਧ ਉਤਪਾਦਨ ਵਿੱਚ ਤੀਬਰ ਘਾਟ ਆ ਜਾਂਦੀ ਹੈ",
    "Control and Prevention": "ਨਿਯੰਤਰਣ ਅਤੇ ਰੋਕਥਾਮ",
    "The area or building where the outbreak of mouth and mouth epidemic has occurred should be disinfected by mild acid, alkali or fumigation":
        "ਜਿੱਥੇ ਮੂੰਹ ਅਤੇ ਪੈਰ ਦੀ ਬੀਮਾਰੀ ਦਾ ਪ੍ਰਸਾਰ ਹੋਇਆ ਹੈ, ਉਸ ਖੇਤਰ ਜਾਂ ਇਮਾਰਤ ਨੂੰ ਹਲਕੇ ਐਸਿਡ, ਆਲਕਲੀ, ਜਾਂ ਧੁਆਂਦਾਰ ਸੈਨੀਟਾਈਜ਼ਰ ਨਾਲ ਰੋਗਾਣੂ ਮੁਕਤ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Movement of vehicles and animals should be banned in the affected areas":
        "ਪ੍ਰਭਾਵਿਤ ਖੇਤਰਾਂ ਵਿੱਚ ਵਾਹਨਾਂ ਅਤੇ ਪਸ਼ੂਆਂ ਦੀ ਚਲਾਣ ਬੰਦ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ।",
    "Affected animals should be kept separate from healthy animals":
        "ਪ੍ਰਭਾਵਿਤ ਪਸ਼ੂਆਂ ਨੂੰ ਸਿਹਤਮੰਦ ਪਸ਼ੂਆਂ ਤੋਂ ਅਲੱਗ ਰੱਖਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Control is possible by vaccinating all susceptible animals to this disease and not allowing the virus to spread from infected animals":
        "ਨਿਯੰਤਰਣ ਸੰਭਵ ਹੈ ਜੇਕਰ ਇਸ ਬੀਮਾਰੀ ਲਈ ਸਾਰੇ ਸੰਵੇਦਨਸ਼ੀਲ ਪਸ਼ੂਆਂ ਨੂੰ ਟੀਕਾਕਰਣ ਕਰਵਾ ਦਿੱਤਾ ਜਾਵੇ ਅਤੇ ਇਨਫੈਕਟਡ ਪਸ਼ੂਆਂ ਤੋਂ ਵਾਇਰਸ ਫੈਲਣ ਨੂੰ ਰੋਕਿਆ ਜਾਵੇ।",
    "Twice a year (May-June and October-November) vaccination is the only effective method of prevention":
        "ਸਾਲ ਵਿੱਚ ਦੋ ਵਾਰ (ਮਈ-ਜੂਨ ਅਤੇ ਅਕਤੂਬਰ-ਨਵੰਬਰ) ਟੀਕਾਕਰਣ ਹੀ ਰੋਕਥਾਮ ਦਾ ਇੱਕਲੌਤਾ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਤਰੀਕਾ ਹੈ।",
    "The first vaccine and after 15 to 30 days must be given to the cutlets and cuttings older than four months and vaccination must be done after every 6 months":
        "ਪਹਿਲੀ ਟੀਕਾ ਅਤੇ 15 ਤੋਂ 30 ਦਿਨਾਂ ਬਾਅਦ ਚਾਰ ਮਹੀਨੇ ਤੋਂ ਵੱਡੇ ਬੱਚਿਆਂ ਅਤੇ ਕੱਟਾਂ ਨੂੰ ਦਿੱਤੀ ਜਾਨੀ ਚਾਹੀਦੀ ਹੈ, ਅਤੇ ਹਰ ਛੇ ਮਹੀਨਿਆਂ ਵਿੱਚ ਟੀਕਾਕਰਣ ਕਰਵਾਉਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Hemorrhagic Septicemia in Buffalo":
        "ਮੱਝ ਅਤੇ ਗਾਂ ਵਿੱਚ ਗੱਲ ਘੋਟੂ ਬਿਮਾਰੀ (ਹੇਮੋਰਹੇਜਿਕ ਸੈਪਟੀਸੀਮੀਆ)",
    "Hemorrhagic Septicemia": "ਗੱਲ ਘੋਟੂ ਬਿਮਾਰੀ",
    "Symptoms": "ਲੱਛਣ",
    "Having a very high fever (up to 107⁰ F) and the animal dying within an hour to 24 hours or the animal being found dead without showing any symptoms to the farmer":
        "ਬਹੁਤਾ ਬੁਖਾਰ (107⁰ F ਤੱਕ) ਹੋਣਾ ਅਤੇ ਪਸ਼ੂ ਦੀ 1 ਘੰਟੇ ਤੋਂ 24 ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ ਮੌਤ ਹੋ ਜਾਣਾ ਜਾਂ ਪਸ਼ੂ ਦੇ ਕਿਸੇ ਵੀ ਲੱਛਣ ਤੋਂ ਬਿਨਾਂ ਮਰੇ ਹੋਏ ਮਿਲਣਾ।",
    "Profuse salivation": "ਭਰਪੂਰ ਲਾਰ।",
    "Runny nose and difficulty in breathing":
        "ਵਗਦਾ ਨੱਕ ਅਤੇ ਸਾਹ ਲੈਣ ਵਿੱਚ ਮੁਸ਼ਕਲ।",
    "Reddened eyes": "ਲਾਲ ਅੱਖਾਂ।",
    "Stop grazing and become depressed":
        "ਘਾਸ ਚਰਨਾ ਬੰਦ ਕਰ ਦੇਣਾ ਅਤੇ ਉਦਾਸ ਹੋ ਜਾਨਾ।",
    "It has been seen in a very acute condition that the animals mouth becomes stagnant with food or water":
        "ਇੱਕ ਬਹੁਤ ਹੀ ਤੀਬਰ ਹਾਲਤ ਵਿੱਚ ਦੇਖਿਆ ਗਿਆ ਹੈ ਕਿ ਪਸ਼ੂ ਦਾ ਮੂੰਹ ਖਾਣੇ ਜਾਂ ਪਾਣੀ ਨਾਲ ਜਮ ਜਾਂਦਾ ਹੈ।",
    "Cognition with pain in the throat, neck and chest":
        "ਗਲੇ, ਗਰਦਨ, ਅਤੇ ਛਾਤੀ ਵਿੱਚ ਦਰਦ ਨਾਲ ਅਸਵੱਸਣਾ",
    "Control": 'ਨਿਯੰਤਰਣ',
    "Immediately separate sick buffalo from healthy animals and sterilize the place and do not take it to public places such as pastures and other places where animals congregate as this disease spreads through inhalation, drinking water and feeding":
        "ਤੁਰੰਤ ਬੀਮਾਰ ਪਸ਼ੂਆਂ ਨੂੰ ਸਿਹਤਮੰਦ ਪਸ਼ੂਆਂ ਤੋਂ ਅਲੱਗ ਰੱਖੋ ਅਤੇ ਜਗ੍ਹਾ ਨੂੰ ਸੈਨੀਟਾਈਜ਼ ਕਰੋ। ਇਸਨੂੰ ਆਮ ਜਗ੍ਹਾਂ ਜਿਵੇਂ ਚਰਾਗਾਹਾਂ ਅਤੇ ਹੋਰ ਥਾਵਾਂ ਤੇ ਨਾ ਲਿਜਾਓ ਜਿੱਥੇ ਪਸ਼ੂ ਇਕੱਠੇ ਹੁੰਦੇ ਹਨ, ਕਿਉਂਕਿ ਇਹ ਬੀਮਾਰੀ ਸਾਂਸ ਨਾਲ, ਪਾਣੀ ਪੀਣ ਅਤੇ ਖਾਣ-ਪੀਣ ਦੁਆਰਾ ਫੈਲਦੀ ਹੈ।",
    "Dig a pit at least 5 feet deep to the dead animal and press it well by sprinkling salt":
        "ਮਰੇ ਹੋਏ ਜਾਨਵਰ ਲਈ ਘੱਟੋ-ਘੱਟ 5 ਫੁੱਟ ਡੂੰਘਾ ਟੋਆ ਪੁੱਟੋ ਅਤੇ ਲੂਣ ਛਿੜਕ ਕੇ ਚੰਗੀ ਤਰ੍ਹਾਂ ਦਬਾਓ।",
    "Twice a year must be vaccinated against galghotu disease, first before the start of the rainy season (in the month of May-June) and the second before the onset of winter (in the month of October - November). By doing this, there can be a significant reductionin the animal mortality rate due to gallstone disease":
        "ਸਾਲ ਵਿੱਚ ਦੋ ਵਾਰ ਗਲਘੋਟੂ ਬੀਮਾਰੀ ਖਿਲਾਫ ਟੀਕਾਕਰਣ ਕਰਵਾਇਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ, ਪਹਿਲੀ ਵਾਰ ਬਰਸਾਤ ਦੇ ਸੀਜ਼ਨ ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ (ਮਈ-ਜੂਨ ਮਹੀਨੇ ਵਿੱਚ) ਅਤੇ ਦੂਜੀ ਵਾਰ ਅਕਤੂਬਰ-ਨਵੰਬਰ ਮਹੀਨਿਆਂ ਵਿੱਚ ਸਰਦੀ ਦੇ ਆਗਮਨ ਤੋਂ ਪਹਿਲਾਂ। ਇਸ ਤਰ੍ਹਾਂ, ਗਲਘੋਟੂ ਬੀਮਾਰੀ ਕਾਰਨ ਪਸ਼ੂਆਂ ਦੀ ਮੌਤ ਦੀ ਦਰ ਵਿੱਚ ਕਾਫੀ ਘਾਟ ਹੋ ਸਕਦੀ ਹੈ।",
    "Mastitis in Buffalo": 'ਮੱਝ ਅਤੇ ਗਾਂ ਵਿੱਚ ਮਾਸਟਾਈਟਿਸ',
    "Mastitis": "ਮਾਸਟਾਈਟਿਸ",
    "Swollen and reddening of teats": "ਦੁੱਧ ਦੇ ਨੱਕ ਦਾ ਸੁੱਜਣਾ ਅਤੇ ਲਾਲ ਹੋਣਾ।",
    "Milk mixed with blood": "ਦੁੱਧ ਵਿੱਚ ਖੂਨ ਮਿਲਿਆ ਹੋਇਆ।",
    "Milk mixed with yellow or brown fluid with flakes or clots with foul smelling":
        "ਦੁੱਧ ਵਿੱਚ ਪੀਲੇ ਜਾਂ ਭੂਰੇ ਰੰਗ ਦੇ ਰੱਸੀਲੇ ਪਦਾਰਥ, ਚਿੱਟੇ ਜਾਂ ਗੁੱਥੇ ਅਤੇ ਬਦਬੂਦਾਰ ਹੁੰਦੇ ਹਨ।",
    "Swollen udder with hot and pain while touching it":
        "ਫੁੱਲਿਆ ਹੋਇਆ ਉੱਤਰ ਜੋ ਗਰਮ ਹੁੰਦਾ ਹੈ ਅਤੇ ਛੂਹਣ ਤੇ ਦਰਦ ਹੁੰਦਾ ਹੈ।",
    "Swelling of udder as a hard mass":
        "ਉੱਤਰ ਦੀ ਫੁੱਲਨ ਨਾਲ ਸਖ਼ਤ ਗਠੇ ਦੇ ਰੂਪ ਵਿੱਚ।",
    "Animal will not allow touching the udder and will kick while touching it":
        "ਪਸ਼ੂ ਉੱਤਰ ਨੂੰ ਛੂਹਣ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਦੇਵੇਗਾ ਅਤੇ ਛੂਹਣ ਤੇ ਲੱਤ ਮਾਰੇਗਾ।",
    "Animal sheds should be clean and floor should be washed with running water":
        "ਪਸ਼ੂਆਂ ਦੇ ਥਾਂ ਸਾਫ਼ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ ਅਤੇ ਫਰਸ਼ ਨੂੰ ਚੱਲਦੇ ਪਾਣੀ ਨਾਲ ਧੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Milker should washed their hand with soap before milking of each animal":
        "ਦੁੱਧ ਦੂਧਣ ਵਾਲਿਆਂ ਨੂੰ ਹਰ ਪਸ਼ੂ ਨੂੰ ਦੁਧ ਦਿਨ ਤੋਂ ਪਹਿਲਾਂ ਆਪਣੇ ਹੱਥ ਸਾਬਣ ਨਾਲ ਧੋਣੇ ਚਾਹੀਦੇ ਹਨ।",
    "Teats/udder of the buffalo should be washed and dried up soft cloth before milking":
        "ਦੁੱਧ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਪਸ਼ੂਆਂ ਦੇ ਲੇਵੇ ਨੂੰ ਧੋ ਕੇ ਨਰਮ ਕੱਪੜੇ ਨਾਲ ਸੁਕਾ ਲੈਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Buffalo should not be allowed to sit just after the milking and may be engaged with either fodder/concentrate mixture":
        "ਪਸ਼ੂਆਂ ਨੂੰ ਦੁਧ ਦਿੰਦੇ ਬਾਅਦ ਤੁਰੰਤ ਬੈਠਣ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਦੇਣੀ ਚਾਹੀਦੀ ਅਤੇ ਉਸਨੂੰ ਚਾਰਾ ਜਾਂ ਕੇਂਦਰਿਤ ਮਿਸ਼ਰਣ ਨਾਲ ਵਿਅਸਤ ਰੱਖਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Milking should be done completely every time. Ensure that there is no left over milk in the udder":
        "ਹਰ ਵਾਰੀ ਦੁਧ ਪੂਰੀ ਤਰ੍ਹਾਂ ਨਿਕਾਲਿਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਇਹ ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਉੱਤਰ ਵਿੱਚ ਕੋਈ ਬਚਾ ਹੋਇਆ ਦੁਧ ਨਾ ਰਹੇ।",
    "Infected buffalo should be kept isolated from the herd":
        "ਸੰਕਰਮਿਤ ਪਸ਼ੂਆਂ ਨੂੰ ਝੁੰਡ ਤੋਂ ਅਲੱਗ ਰੱਖਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Always maintain the proper hygienic condition in the herd and shed":
        "ਝੁੰਡ ਅਤੇ ਸ਼ੈੱਡ ਵਿੱਚ ਹਮੇਸ਼ਾ ਸਹੀ ਸਫਾਈ ਬਣਾਈ ਰੱਖੋ।",
    "Immediately after detecting clinical signs, it should be consulted with qualified veterinarian for further treatment":
        "ਕਲਿਨਿਕਲ ਲੱਛਣਾਂ ਦੀ ਪਛਾਣ ਕਰਨ ਦੇ ਤੁਰੰਤ ਬਾਅਦ, ਇਸਦੀ ਵੱਧ ਦੇ ਇਲਾਜ ਲਈ ਯੋਗ ਪ੍ਰਮਾਣਿਤ ਵੈਟਰਨਰੀਅਨ ਨਾਲ ਸਲਾਹ ਕਰਨੇ ਦੀ ਲੋੜ ਹੈ।",
    "Deworming Schedule for Buffalo": "ਵਰਮਨਾਸ਼ਕ ਅਤੇ ਟੀਕਾਕਰਣ ਅਨੁਸੂਚੀ",
    "Deworming and vaccination schedule": "ਵਰਮਨਾਸ਼ਕ ਅਤੇ ਟੀਕਾਕਰਣ ਅਨੁਸੂਚੀ",
    "Age of Buffalo": "ਮੱਝ ਅਤੇ ਗਾਂ ਦੀ ਉਮਰ",
    "Anthelmintic": "ਵਰਮਨਾਸ਼ਕ",
    "Dose": "ਖੁਰਾਕ",
    "Schedule": "ਸਮਾ ਸੂਚੀ",
    "3-7 days": "3-7 ਦਿਨ",
    "Piparazine": "ਪਾਈਪਰਾਜ਼ਿਨ",
    "5-10 ml per 10 kg of body weight": "ਹਰ 10 ਕਿਲੋਗ੍ਰਾਮ ਭਾਰ ਦੇ ਲਈ 5-10 ਮਿ.ਲੀ.",
    "Repeat in every 21 days upto 2 months":
        "ਹਰ 21 ਦਿਨ ਬਾਅਦ ਦੁਹਰਾਓ ਅਤੇ 2 ਮਹੀਨੇ ਤੱਕ ਜਾਰੀ ਰੱਖੋ",
    "3-6 months": "3-6 ਮਹੀਨੇ",
    "Albendazole": "ਐਲਬੈਂਡਾਜੋਲ",
    "5 ml per kg of body weight": "ਹਰ ਕਿਲੋਗ੍ਰਾਮ ਭਾਰ ਲਈ 5 ਮਿ.ਲੀ.",
    "Every month": "ਹਰ ਮਹੀਨੇ",
    "6-18 months": "6-18 ਮਹੀਨੇ",
    "Albendazole or Ivermetic injection": "ਐਲਬੈਂਡਾਜੋਲ ਜਾਂ ਆਇਵਰਮੈਕਟਿਨ ਇੰਜੈਕਸ਼ਨ",
    "Every 3 months": "ਹਰ 3 ਮਹੀਨਿਆਂ ਵਿੱਚ",
    "Adult buffalo": "ਬਾਲਗ ਮੱਝ ਅਤੇ ਗਾਂ",
    "Albendazole , Fendendazole or Ivermetic injection":
        "ਐਲਬੈਂਡਾਜੋਲ, ਫੈਨਬੈਂਡਾਜੋਲ, ਜਾਂ ਆਇਵਰਮੈਕਟਿਨ ਇੰਜੈਕਸ਼ਨ",
    "Twice in year preferably before rainy and winter season":
        "ਸਾਲ ਵਿੱਚ ਦੋ ਵਾਰ, ਬਰਸਾਤ ਅਤੇ ਸਰਦੀ ਦੇ ਸੀਜ਼ਨਾਂ ਤੋਂ ਪਹਿਲਾਂ ਤਰਜੀਹੀ ਤੌਰ 'ਤੇ",
    "Vaccination Schedule": "ਟੀਕਾਕਰਨ ਅਨੁਸੂਚੀ",
    "Disease": "ਰੋਗ",
    "Age and time of vaccination": "ਟੀਕਾਕਰਨ ਦੀ ਉਮਰ ਅਤੇ ਸਮਾਂ",
    "FMD": "ਪੈਰ ਅਤੇ ਮੂੰਹ ਦੀ ਬੀਮਾਰੀ",
    "First dose at 4 months of age and booster dose at 6 months of age.Repeat every six months interval preferably during March-April and September-October":
        "ਪਹਿਲੀ ਖੁਰਾਕ 4 ਮਹੀਨਿਆਂ ਦੀ ਉਮਰ ਵਿੱਚ ਅਤੇ ਬੂਸਟਰ ਖੁਰਾਕ 6 ਮਹੀਨਿਆਂ ਦੀ ਉਮਰ ਵਿੱਚ। ਹਰ ਛੇ ਮਹੀਨਿਆਂ ਦੇ ਅੰਤਰਾਲ ਨੂੰ ਤਰਜੀਹੀ ਤੌਰ 'ਤੇ ਮਾਰਚ-ਅਪ੍ਰੈਲ ਅਤੇ ਸਤੰਬਰ-ਅਕਤੂਬਰ ਦੌਰਾਨ ਦੁਹਰਾਓ।",
    "Haemorrhagic septicemia": "ਗੱਲ ਘੋਟੂ (ਹੇਮੋਰਹੇਜਿਕ ਸੈਪਟੀਸੀਮੀਆ)",
    "First dose at 4-6 months of age and booster dose should be repeated every year preferably before rainy season in the months of May-June":
        "4-6 ਮਹੀਨਿਆਂ ਦੀ ਉਮਰ ਵਿੱਚ ਪਹਿਲੀ ਖੁਰਾਕ ਅਤੇ ਬੂਸਟਰ ਖੁਰਾਕ ਨੂੰ ਹਰ ਸਾਲ ਤਰਜੀਹੀ ਤੌਰ 'ਤੇ ਮਈ-ਜੂਨ ਦੇ ਮਹੀਨਿਆਂ ਵਿੱਚ ਬਰਸਾਤ ਦੇ ਮੌਸਮ ਤੋਂ ਪਹਿਲਾਂ ਦੁਹਰਾਉਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Black quarter": "ਕਾਲਾ ਪੈਰ",
    "First dose at 6 months of age and booster dose should be repeated every year preferably before rainy season in the months of May-June":
        "6 ਮਹੀਨੇ ਦੀ ਉਮਰ ਵਿੱਚ ਪਹਿਲੀ ਖੁਰਾਕ ਅਤੇ ਬੂਸਟਰ ਖੁਰਾਕ ਨੂੰ ਹਰ ਸਾਲ ਤਰਜੀਹੀ ਤੌਰ 'ਤੇ ਮਈ-ਜੂਨ ਦੇ ਮਹੀਨਿਆਂ ਵਿੱਚ ਬਰਸਾਤ ਦੇ ਮੌਸਮ ਤੋਂ ਪਹਿਲਾਂ ਦੁਹਰਾਉਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Brucellosis": "ਬ੍ਰੂਸੇਲੋਸਿਸ",
    "Single dose for female calf at the age of 4-8 months":
        "4-8 ਮਹੀਨਿਆਂ ਦੀ ਉਮਰ ਵਿੱਚ ਮਾਦਾ ਵੱਛੇ ਲਈ ਸਿੰਗਲ ਖੁਰਾਕ।",
  })
  ..addAll({
    "Calf Management": "ਵੱਛੇ ਦੀ ਪ੍ਰਬੰਧਕੀ",
    "Shed should be provided to the claves with clean, dry and bedded area for rest. In calf shed maximum ventilation for hot weather should provide for at least one air change/minute. Provide fan and cooling facility during hotter part of the day.":
        "ਵੱਛੇ ਲਈ ਸਾਫ਼, ਸੁੱਕੀ ਅਤੇ ਬਿਸਤਰ ਵਾਲੀ ਖੇਤਰ ਵਾਲਾ ਸਹੂਲਤ ਵਾਲਾ ਸਹਾਇਕ ਸਥਾਨ ਪ੍ਰਦਾਨ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਬੱਚੇ ਦੇ ਥਾਂ ਵਿੱਚ ਗਰਮ ਮੌਸਮ ਲਈ ਵੱਧ ਤੋਂ ਵੱਧ ਹਵਾ ਦੇ ਬਦਲਾਅ ਲਈ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਹਵਾ ਬਦਲਾਅ ਪ੍ਰਤੀ ਮਿੰਟ ਦਿੱਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਗਰਮ ਸਮੇਂ ਦੌਰਾਨ ਫ਼ੈਨ ਅਤੇ ਠੰਢਕ ਸਹੂਲਤ ਪ੍ਰਦਾਨ ਕਰੋ।",
    "Provide good quality calf starter (must contain 75% TDN and 14-16 per cent digestible crude protein). Increase the frequency of feeding to fulfill the dietary requirement of the calf for proper growth of the calf under heat stress condition. Offer feed during cool hours of the day.":
        "ਉਤਮ ਮਿਆਰੀ ਵੱਛੇ ਦੀ ਸ਼ੁਰੂਆਤ (ਜਿਸ ਵਿੱਚ 75% ਟੀਡੀਐਨ ਅਤੇ 14-16 ਫੀਸਦੀ ਪਚਣਯੋਗ ਕੁੜੀ ਪ੍ਰੋਟੀਨ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ) ਮੁਹੱਈਆ ਕਰੋ। ਵੱਛੇ ਦੀ ਸਹੀ ਵਧੋਤਰੀ ਲਈ ਪੋਸ਼ਣ ਦੀ ਲੋੜ ਪੂਰੀ ਕਰਨ ਲਈ ਖਾਣ ਦੀ ਤੀਵ੍ਰਤਾ ਵਧਾਓ, ਖਾਸ ਕਰਕੇ ਗਰਮੀ ਦੇ ਦੌਰਾਨ। ਖਾਣਾ ਸਾਰਾ ਦਿਨ ਦੇ ਠੰਢੇ ਘੰਟਿਆਂ ਦੌਰਾਨ ਦੇਵੋ।",
    "Calves should be kept re-hydrated. Plenty fresh and cool water should be made available for calves. Calves should be taught for water drinking from first week of life.":
        "ਵੱਛੇਆਂ ਨੂੰ ਪੁਨਰ-ਹਾਈਡ੍ਰੇਟੇਡ ਰੱਖਣਾ ਚਾਹੀਦਾ ਹੈ। ਵੱਛੇਆਂ ਲਈ ਵੱਧ ਤੋਂ ਵੱਧ ਤਾਜ਼ਾ ਅਤੇ ਠੰਢਾ ਪਾਣੀ ਉਪਲਬਧ ਕਰਵਾਇਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਵੱਛਿਆਂ ਨੂੰ ਜੀਵਨ ਦੇ ਪਹਿਲੇ ਹਫ਼ਤੇ ਤੋਂ ਪਾਣੀ ਪੀਣ ਲਈ ਸਿਖਾਇਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Vaccination, tagging and disbudding activities should be carried out in cool hours of the day.":
        "ਟੀਕਾਕਰਣ, ਟੈਗਿੰਗ ਅਤੇ ਡਿਸਬੱਡਿੰਗ ਦੀਆਂ ਗਤਿਵਿਧੀਆਂ ਦਿਨ ਦੇ ਠੰਢੇ ਘੰਟਿਆਂ ਦੌਰਾਨ ਕੀਤੀਆਂ ਜਾਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ।",
    "Colostrum quality should be checked during summer months so that calf should get optimum immunity through colostrum.":
        "ਗਰਮੀਆਂ ਦੇ ਮਹੀਨਿਆਂ ਦੌਰਾਨ ਕੋਲੋਸਟ੍ਰਮ ਦੀ ਗੁਣਵੱਤਾ ਦੀ ਜਾਂਚ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ ਤਾਂ ਜੋ ਵੱਛੇ ਨੂੰ ਕੋਲੋਸਟ੍ਰਮ ਦੁਆਰਾ ਸਰਵੋਤਮ ਪ੍ਰਤੀਰੋਧਕ ਸ਼ਕਤੀ ਪ੍ਰਾਪਤ ਹੋਵੇ।",
    "The feeding equipments use for calf feeding should properly disinfected during summer months to avoid chance of infection.":
        "ਵੱਛੇ ਦੇ ਖੁਆਉਣ ਲਈ ਵਰਤੇ ਜਾਣ ਵਾਲੇ ਫੀਡਿੰਗ ਉਪਕਰਨਾਂ ਨੂੰ ਗਰਮੀਆਂ ਦੇ ਮਹੀਨਿਆਂ ਦੌਰਾਨ ਇਨਫੈਕਸ਼ਨ ਦੀ ਸੰਭਾਵਨਾ ਤੋਂ ਬਚਣ ਲਈ ਸਹੀ ਤਰ੍ਹਾਂ ਰੋਗਾਣੂ ਮੁਕਤ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ।",
    "Housing": "ਰਿਹਾਇਸ਼",
    "Adequate space should be provided during the heat stress period to the dairy animals for effective heat dissipation, especially in tie stalls, which are commonly observed at farmers doorsteps and present-day small commercial dairy farms.":
        "ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੇ ਸਮੇਂ ਦੌਰਾਨ ਡੇਰੀ ਜਾਨਵਰਾਂ ਨੂੰ ਪ੍ਰਭਾਵੀ ਗਰਮੀ ਦੇ ਨਿਕਾਸ ਲਈ ਢੁਕਵੀਂ ਥਾਂ ਪ੍ਰਦਾਨ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ, ਖਾਸ ਤੌਰ 'ਤੇ ਟਾਈ ਸਟਾਲਾਂ ਵਿੱਚ, ਜੋ ਆਮ ਤੌਰ 'ਤੇ ਕਿਸਾਨਾਂ ਦੇ ਦਰਵਾਜ਼ੇ ਅਤੇ ਅਜੋਕੇ ਛੋਟੇ ਵਪਾਰਕ ਡੇਰੀ ਫਾਰਮਾਂ ਵਿੱਚ ਵੇਖੇ ਜਾਂਦੇ ਹਨ।",
    "Sheds must be provided, especially during the summer months, to reduce the heat load from radiation. The roof should be reflective. Roof painted with white paint and insulated with puff or straw and covered with seasonal vegetable plants like bottle gourd, pumpkin and ridge gourd grown from earth is quite effective in reducing the inside temperature of the shed.":
        "ਗਰਮੀ ਦੇ ਮਹੀਨਿਆਂ ਵਿੱਚ ਗਰਮੀ ਦੇ ਬੋਝ ਨੂੰ ਘਟਾਉਣ ਲਈ ਖਾਸ ਤੌਰ 'ਤੇ ਛਾਂ ਪੇਸ਼ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ। ਛੱਤ ਪ੍ਰਤੀਬਿੰਬਤ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ। ਛੱਤ ਨੂੰ ਸਫੈਦ ਰੰਗ ਨਾਲ ਪੇਂਟ ਕੀਤਾ ਜਾਵੇ ਅਤੇ ਇਸਨੂੰ ਪਫ਼ ਜਾਂ ਹੇਠਾਂ ਸੁੱਕੇ ਹੋਏ ਫੁੱਲਾਂ ਨਾਲ ਇਨਸੂਲੇਟ ਕੀਤਾ ਜਾਵੇ ਅਤੇ ਮੌਸਮੀ ਸਬਜ਼ੀਆਂ ਜਿਵੇਂ ਕਿ ਕਦੂ ਅਤੇ ਲੌਕੀ ਨਾਲ ਢਕਿਆ ਜਾਵੇ, ਜੋ ਕਿ ਅੰਦਰੂਨੀ ਤਾਪਮਾਨ ਨੂੰ ਘਟਾਉਣ ਵਿੱਚ ਕਾਫੀ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ।",
    "The fresh and cool drinking water facility under shaded areas should be ensured for effective heat stress management.":
        "ਛਾਂ ਵਾਲੇ ਖੇਤਰਾਂ ਹੇਠਾਂ ਤਾਜ਼ਾ ਅਤੇ ਠੰਢੇ ਪਾਣੀ ਦੀ ਸੁਵਿਧਾ ਯਕੀਨੀ ਬਣਾਈ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ ਤਾਂ ਜੋ ਗਰਮੀ ਦੇ ਤਣਾਅ ਨੂੰ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਤਰੀਕੇ ਨਾਲ ਸੰਭਾਲਿਆ ਜਾ ਸਕੇ।",
    "Holding and milking areas must have adequate ventilation, air circulation, and cooling facilities as less attention has been given under Indian conditions.":
        "ਫੜਨ ਅਤੇ ਦੁੱਧ ਦੇਣ ਵਾਲੇ ਖੇਤਰਾਂ ਵਿੱਚ ਲੋੜੀਂਦੀ ਹਵਾਦਾਰੀ, ਹਵਾ ਦਾ ਸੰਚਾਰ, ਅਤੇ ਠੰਢਾ ਕਰਨ ਦੀਆਂ ਸਹੂਲਤਾਂ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ ਕਿਉਂਕਿ ਭਾਰਤੀ ਹਾਲਤਾਂ ਵਿੱਚ ਘੱਟ ਧਿਆਨ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
    "In hot-dry weather, misting is quite effective in cooling the environment, which further helps to cool the animals. Fogging is very effective but under closed conditions and when the temperature is high and humidity is low. In fogging, desalinated water is generally recommended; otherwise, nozzle blocking is a common problem.":
        "ਗਰਮ-ਸੁੱਕੇ ਮੌਸਮ ਵਿੱਚ, ਮਿਸਟਿੰਗ ਵਾਤਾਵਰਣ ਨੂੰ ਠੰਢਾ ਕਰਨ ਵਿੱਚ ਬਹੁਤ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੁੰਦੀ ਹੈ, ਜਿਸ ਨਾਲ ਪਸ਼ੂਆਂ ਨੂੰ ਠੰਢਾ ਕਰਨ ਵਿੱਚ ਵੀ ਸਹਾਇਤਾ ਮਿਲਦੀ ਹੈ। ਫਾਗਿੰਗ ਬਹੁਤ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੁੰਦੀ ਹੈ ਪਰ ਬੰਦ ਹਾਲਾਤਾਂ ਵਿੱਚ ਅਤੇ ਜਦੋਂ ਤਾਪਮਾਨ ਉੱਚਾ ਅਤੇ ਨਮੀ ਘੱਟ ਹੋਵੇ। ਫਾਗਿੰਗ ਵਿੱਚ, ਆਮ ਤੌਰ 'ਤੇ ਨਮਕੀਨ ਪਾਣੀ ਨਾ ਹੋਣ ਦੀ ਸਿਫਾਰਸ਼ ਕੀਤੀ ਜਾਂਦੀ ਹੈ; ਨਹੀਂ ਤਾਂ ਨੋਜ਼ਲ ਬਲਾਕਿੰਗ ਇੱਕ ਆਮ ਸਮੱਸਿਆ ਬਣ ਜਾਂਦੀ ਹੈ।",
    "In hot-humid conditions, sprinkling for a limited period along with fanning is quite effective. In closed housing for such a cooling system, proper ventilation must be ensured to reduce the humidity buildup.":
        "ਗਰਮ-ਨਮੀ ਵਾਲੇ ਹਾਲਾਤਾਂ ਵਿੱਚ, ਸੀਮਤ ਸਮੇਂ ਲਈ ਛਿੜਕਾਅ ਅਤੇ ਪੱਖੇ ਦੀ ਵਰਤੋਂ ਬਹੁਤ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੁੰਦੀ ਹੈ। ਬੰਦ ਘਰਾਂ ਵਿੱਚ ਇਸ ਤਰ੍ਹਾਂ ਦੇ ਠੰਢਕ ਸਿਸਟਮ ਲਈ, ਨਮੀ ਦੇ ਵੱਧਣ ਨੂੰ ਘਟਾਉਣ ਲਈ ਸਹੀ ਤਰ੍ਹਾਂ ਦੇ ਹਵਾ ਦੇ ਆਵਾਹਨ ਦੀ ਯਕੀਨਨ ਵਿਵਸਥਾ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ।",
    "Straw bedding (2 inch) or mattress or sand bedding are effective to improve the resting time of dairy animals.":
        "ਡੇਰੀ ਜਾਨਵਰਾਂ ਦੇ ਆਰਾਮ ਕਰਨ ਦੇ ਸਮੇਂ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਤੂੜੀ ਦੇ ਬਿਸਤਰੇ (2 ਇੰਚ) ਜਾਂ ਚਟਾਈ ਜਾਂ ਰੇਤ ਦੇ ਬਿਸਤਰੇ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੁੰਦੇ ਹਨ।",
    "Animal Shed should be constructed east-west direction. Height of the shed at centre should be 14-15 ft and height at eve 12-13 feet commonly used. Researchers even used 16-18 ft height at centre and 14-15 ft at eve to maintain better micro environment inside the shed. Natural tree shed in the open paddock area and farm premises is quite effective to reduce the heat load.":
        "ਪਸ਼ੂਆਂ ਦੇ ਸ਼ੈਡ ਨੂੰ ਪੂਰਬ-ਪੱਛਮ ਦੀ ਦਿਸ਼ਾ ਵਿੱਚ ਬਣਾਇਆ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਸ਼ੈਡ ਦੀ ਮੱਧੀ ਉਚਾਈ 14-15 ਫੁੱਟ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ ਅਤੇ ਈਵ ਦੀ ਉਚਾਈ ਆਮ ਤੌਰ 'ਤੇ 12-13 ਫੁੱਟ ਹੁੰਦੀ ਹੈ। ਖੋਜਕਾਰਾਂ ਨੇ ਵੀ ਸ਼ੈਡ ਵਿੱਚ ਚੰਗੇ ਮਾਈਕ੍ਰੋ ਵਾਤਾਵਰਣ ਨੂੰ ਬਰਕਰਾਰ ਰੱਖਣ ਲਈ ਮੱਧੀ ਉਚਾਈ 16-18 ਫੁੱਟ ਅਤੇ ਈਵ 14-15 ਫੁੱਟ ਵਰਤੀ ਹੈ। ਖੁਲੇ ਪੈੱਡੌਕ ਖੇਤਰ ਅਤੇ ਫਾਰਮ ਦੇ ਪ੍ਰੰਗਣ ਵਿੱਚ ਕੁਦਰਤੀ ਦਰਖ਼ਤ ਦੀ ਛਾਂ ਗਰਮੀ ਦੇ ਬੋਝ ਨੂੰ ਘਟਾਉਣ ਵਿੱਚ ਕਾਫੀ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ।",
    "Reproductive Management": "ਪ੍ਰਜਨਨ ਪ੍ਰਬੰਧਕੀ",
    "The incidence of anoestrus in buffalo ranges from 20 to 80% depending on season.Most buffalo cease ovarian cyclicity during hot summers probably due to the combined effects of nutrition, environment and management. In the heat stress period, four to five days of adequate cooling, especially around breeding, can enhance the fertility of dairy animals.":
        "ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਵਿੱਚ ਐਨੋਸਟ੍ਰਸ ਦੀਆਂ ਘਟਨਾਵਾਂ ਮੌਸਮ ਦੇ ਅਧਾਰ ਤੇ 20 ਤੋਂ 80% ਤੱਕ ਹੁੰਦੀਆਂ ਹਨ। ਜ਼ਿਆਦਾਤਰ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਗਰਮ ਗਰਮੀਆਂ ਦੌਰਾਨ ਅੰਡਕੋਸ਼ ਦੇ ਚੱਕਰ ਨੂੰ ਬੰਦ ਕਰ ਦਿੰਦੀਆਂ ਹਨ, ਸ਼ਾਇਦ ਪੋਸ਼ਣ, ਵਾਤਾਵਰਣ ਅਤੇ ਪ੍ਰਬੰਧਨ ਦੇ ਸੰਯੁਕਤ ਪ੍ਰਭਾਵਾਂ ਕਾਰਨ। ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੀ ਮਿਆਦ ਵਿੱਚ, ਚਾਰ ਤੋਂ ਪੰਜ ਦਿਨਾਂ ਦੀ ਢੁਕਵੀਂ ਠੰਢ, ਖਾਸ ਕਰਕੇ ਪ੍ਰਜਨਨ ਦੇ ਆਲੇ-ਦੁਆਲੇ, ਡੇਰੀ ਜਾਨਵਰਾਂ ਦੀ ਉਪਜਾਊ ਸ਼ਕਤੀ ਨੂੰ ਵਧਾ ਸਕਦੀ ਹੈ।",
    "Keeping buffalo cool by wallowing, water sprinklers or shade improves fertility.":
        "ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਨੂੰ ਵਹਾਉਣ, ਪਾਣੀ ਦੇ ਛਿੜਕਾਅ ਜਾਂ ਛਾਂ ਦੁਆਰਾ ਠੰਡਾ ਰੱਖਣ ਨਾਲ ਉਪਜਾਊ ਸ਼ਕਤੀ ਵਿੱਚ ਸੁਧਾਰ ਹੁੰਦਾ ਹੈ",
    "Buffalo supplemented with UMMBs for 60 days before calving will have betterpostpartum reproductive performance.":
        "ਵੱਛੇ ਬਣਨ ਤੋਂ ਪਹਿਲਾਂ 60 ਦਿਨਾਂ ਲਈ ਯੂਐਮਐਮਬੀਜ਼ ਨਾਲ ਪੂਰਕ ਕੀਤੀ ਗਈ ਮੱਝ ਦਾ ਜਣੇਪੇ ਤੋਂ ਬਾਅਦ ਬਿਹਤਰ ਪ੍ਰਜਨਨ ਕਾਰਜਕੁਸ਼ਲਤਾ ਹੋਵੇਗੀ।",
    "Regular supplementation of UMMBs early after calving also enhances production (8% more milk) and oestrus expression within 50 days. UMMBs also induce fertile oestrus in non-pregnant anoestrous buffalo.":
        "ਮੈਡਾਂ ਦੇ ਜਨਮ ਦੇ ਤੁਰੰਤ ਬਾਅਦ ਯੂਐਮਐਮਬੀਜ਼ ਦੀ ਨਿਯਮਤ ਪੂਰਤੀ ਉਤਪਾਦਨ (8% ਵੱਧ ਦੁਧ) ਅਤੇ 50 ਦਿਨਾਂ ਵਿੱਚ ਓਸਟਰਸ ਦੇ ਪ੍ਰਗਟਾਵੇ ਨੂੰ ਵੀ ਵਧਾਉਂਦੀ ਹੈ। ਯੂਐਮਐਮਬੀਜ਼ ਅਵ੍ਰਿਥੀ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਵਿੱਚ ਪ੍ਰਸਵਸ਼ੀਲ ਓਸਟਰਸ ਵੀ ਉਤਪੰਨ ਕਰਦੇ ਹਨ।",
    "Ameliorative strategies in the form of environmental enrichment and cooling mechanism depending on the weather condition, nutritional manipulation, stress-relieving supplements i.e., antioxidants, yeast, buffer, vitamins (Niacin, Vitamin C and Vitamin E) and minerals, electrolytes and hormonal treatment for reproductive management is quite effective.":
        "ਮੌਸਮ ਦੇ ਹਾਲਾਤਾਂ ਦੇ ਆਧਾਰ 'ਤੇ ਵਾਤਾਵਰਣੀ ਸੰਵਰਧਨ ਅਤੇ ਠੰਢਕ ਦੇ ਤਰੀਕਿਆਂ, ਪੋਸ਼ਣ ਸੰਸ਼ੋਧਨ, ਤਣਾਅ ਘਟਾਉਣ ਵਾਲੇ ਪੂਰਕਾਂ ਜਿਵੇਂ ਕਿ ਐਂਟੀਓਕਸਿਡੈਂਟਸ, ਖਮੀਰ, ਬਫਰ, ਵਿੱਟਾਮਿਨ (ਨਾਈਸਿਨ, ਵਿੱਟਾਮਿਨ ਸੀ ਅਤੇ ਵਿੱਟਾਮਿਨ ਈ) ਅਤੇ ਖਣਿਜਾਂ, ਇਲੈਕਟ੍ਰੋਲਾਈਟਸ ਅਤੇ ਪ੍ਰਜਨਨ ਪ੍ਰਬੰਧਨ ਲਈ ਹਾਰਮੋਨਲ ਇਲਾਜ ਦੀ ਵਰਤੋਂ ਬਹੁਤ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ।",
    "Nutrient-enriched feed in the form of good quality green fodder, concentrate, bypass fat, and protein should be supplemented to improve dairy animals reproduction performance during hot weather conditions.":
        "ਗਰਮ ਮੌਸਮ ਦੇ ਦੌਰਾਨ ਡੇਰੀ ਜਾਨਵਰਾਂ ਦੇ ਪ੍ਰਜਨਨ ਕਾਰਜਕੁਸ਼ਲਤਾ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਚੰਗੀ ਗੁਣਵੱਤਾ ਵਾਲੇ ਹਰੇ ਚਾਰੇ, ਦਾਨਾ, ਬਾਈਪਾਸ ਫੈਟ ਅਤੇ ਪ੍ਰੋਟੀਨ ਦੇ ਰੂਪ ਵਿੱਚ ਪੌਸ਼ਟਿਕ ਤੱਤਾਂ ਨਾਲ ਭਰਪੂਰ ਫੀਡ ਨੂੰ ਪੂਰਕ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Useful Tips": "ਲਾਭਕਾਰੀ ਸੁਝਾਵ",
    "Farmers can quickly identify the animal is in heat stress or not by simply monitoring respiration rate. If the respiration rate is more than 80 breaths per minute, heat stress is a clear indication.":
        "ਕਿਸਾਨ ਜਲਦੀ ਨਾਲ ਪਛਾਣ ਸਕਦੇ ਹਨ ਕਿ ਪਸ਼ੂ ਗਰਮੀ ਦੇ ਤਣਾਅ ਵਿੱਚ ਹੈ ਜਾਂ ਨਹੀਂ, ਸਿਰਫ਼ ਸਾਹ ਲੈਣ ਦੀ ਦਰ ਨੂੰ ਨਿਗਰਾਨੀ ਕਰਕੇ। ਜੇ ਸਾਹ ਲੈਣ ਦੀ ਦਰ 80 ਸਾਸਾਂ ਪ੍ਰਤੀ ਮਿੰਟ ਤੋਂ ਵੱਧ ਹੈ, ਤਾਂ ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੀ ਸਪਸ਼ਟ ਸੰਕੇਤ ਹੁੰਦੀ ਹੈ।",
    "The more straightforward way to understand when heat stress started is that if humanbeing starts feeling the stress as for animals, it already started.":
        "ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੀ ਸ਼ੁਰੂਆਤ ਨੂੰ ਸਮਝਣ ਦਾ ਸਧਾਰਨ ਤਰੀਕਾ ਇਹ ਹੈ ਕਿ ਜੇ ਮਨੁੱਖ ਨੂੰ ਗਰਮੀ ਦਾ ਤਣਾਅ ਮਹਿਸੂਸ ਹੋਣ ਲੱਗੇ, ਤਾਂ ਪਸ਼ੂਆਂ ਲਈ ਇਹ ਤਣਾਅ ਪਹਿਲਾਂ ਹੀ ਸ਼ੁਰੂ ਹੋ ਚੁੱਕਾ ਹੁੰਦਾ ਹੈ।",
    "Wallowing is very effective for buffaloes due to their black skin colour and fewer sweat glands. Natural ponds are very common in the village area and quite effective amelioration of heat through wallowing. Artificially build 50 ft. wide X 100 ft. long and 4 to 6 ft. depth wallowing pond is suitable for 100 animals.":
        "ਮੱਝਾਂ ਦੀ ਚਮੜੀ ਦਾ ਰੰਗ ਕਾਲਾ ਹੋਣ ਅਤੇ ਪਸੀਨੇ ਦੀਆਂ ਗ੍ਰੰਥੀਆਂ ਘੱਟ ਹੋਣ ਕਾਰਨ ਉਨ੍ਹਾਂ ਲਈ ਵੌਲੋਇੰਗ ਬਹੁਤ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ। ਪਿੰਡ ਦੇ ਖੇਤਰ ਵਿੱਚ ਕੁਦਰਤੀ ਤਾਲਾਬ ਬਹੁਤ ਆਮ ਹਨ ਅਤੇ ਕੰਧਾਂ ਰਾਹੀਂ ਗਰਮੀ ਨੂੰ ਕਾਫ਼ੀ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਢੰਗ ਨਾਲ ਸੁਧਾਰਦੇ ਹਨ। ਨਕਲੀ ਤੌਰ 'ਤੇ 50 ਫੁੱਟ ਚੌੜਾ X 100 ਫੁੱਟ ਲੰਬਾ ਅਤੇ 4 ਤੋਂ 6 ਫੁੱਟ ਡੂੰਘਾਈ ਵਾਲਾ ਤਾਲਾਬ 100 ਜਾਨਵਰਾਂ ਲਈ ਢੁਕਵਾਂ ਹੈ।",
    "Optimum body condition score maintenance in different stages of physiological state and especially the animals are going to calve in heat stress period can be an effective strategy.":
        "ਵੱਖ-ਵੱਖ ਫਿਜ਼ੀਓਲੋਜੀਕਲ ਅਵਸਥਾਵਾਂ ਵਿੱਚ ਅਤੇ ਖਾਸ ਕਰਕੇ ਜੇ ਪਸ਼ੂ ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੇ ਸਮੇਂ ਵਿੱਚ ਵੱਛੇ ਨੂੰ ਜਨਮ ਦੇਣ ਵਾਲੇ ਹੁੰਦੇ ਹਨ, ਉੱਚਤ ਸ਼ਰੀਰਕ ਹਾਲਤ ਸਕੋਰ ਨੂੰ ਬਣਾਈ ਰੱਖਣਾ ਇੱਕ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਤਰਕੀਬ ਹੋ ਸਕਦੀ ਹੈ।",
    "Identification of genotype adapted to climatic stress and formulation of region-specific climate-resilient breeding strategies of livestock to select heat-tolerant livestock.":
        "ਮੌਸਮ ਦੇ ਤਣਾਅ ਦੇ ਲਾਭਕਾਰੀ ਜੈਨੋਟਾਈਪ ਦੀ ਪਛਾਣ ਅਤੇ ਖੇਤਰ-ਖਾਸ ਮੌਸਮ-ਜੀਵੰਤ ਪ੍ਰਜਨਨ ਤਕਨੀਕਾਂ ਦੀ ਬਣਤਰ, ਤਾਕਿ ਗਰਮੀ ਨੂੰ ਝੇਲ ਸਕਣ ਵਾਲੇ ਪਸ਼ੂਆਂ ਦੀ ਚੋਣ ਕੀਤੀ ਜਾ ਸਕੇ।",
    "Fly control measures should be taken effectively as during summer months the problems of fly increases.":
        "ਮੱਛਰਾਂ ਦੇ ਨਿਯੰਤਰਣ ਦੇ ਉਪਾਅ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਤਰੀਕੇ ਨਾਲ ਕੀਤੇ ਜਾਣੇ ਚਾਹੀਦੇ ਹਨ, ਕਿਉਂਕਿ ਗਰਮੀ ਦੇ ਮਹੀਨਿਆਂ ਦੌਰਾਨ ਮੱਛਰਾਂ ਦੀ ਸਮੱਸਿਆ ਵੱਧ ਜਾਂਦੀ ਹੈ।",
    "Custom Drawer": "ਕਸਟਮ ਡਰਾਅਰ",
    "Open Climate Advisory": "ਮੌਸਮ ਪਾਰਮਰਸ਼ ਖੋਲ੍ਹੋ",
    "Today": "ਅੱਜ",
    "Next Days": "ਅਗਲੇ ਦਿਨ",
    'MON': 'ਸੋਮ',
    'TUE': 'ਮੰਗਲ',
    'WED': 'ਬੁੱਧ',
    'THURS': 'ਗੁਰੂ',
    'FRI': 'ਸ਼ੁਕਰ',
    'SAT': 'ਸ਼ਨੀ',
    'SUN': 'ਰਵਿ',
    'kmps': 'ਕਿਮੀ.',
    'mm': 'ਮਿਮੀ',
    '(octa)': '(ਓਕਟਾ)'
  })
  ..addAll({
    "Management During Thermal Stress": "ਤਾਪਮਾਨ ਤਣਾਅ ਦੌਰਾਨ ਪ੍ਰਬੰਧਨ",
    "Symptoms of Heat Stress": "ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੇ ਲੱਛਣ",
    "Thermal stress occurs when the ambient temperature lies above or below thermoneutral zone.Dairy animals have been found to be negatively impacted with increased temperature and humidity":
        "ਤਾਪਮਾਨ ਤਣਾਅ ਤਦ ਹੁੰਦਾ ਹੈ ਜਦੋਂ ਵਾਤਾਵਰਣ ਤਾਪਮਾਨ ਤਾਪਮਾਨ-ਨਿਊਟ੍ਰਲ ਜ਼ੋਨ ਤੋਂ ਉਪਰ ਜਾਂ ਹੇਠਾਂ ਹੁੰਦਾ ਹੈ। ਵਧੇ ਹੋਏ ਤਾਪਮਾਨ ਅਤੇ ਨਮੀ ਨਾਲ ਡੇਰੀ ਜਾਨਵਰਾਂ 'ਤੇ ਮਾੜਾ ਅਸਰ ਪਾਇਆ ਗਿਆ ਹੈ।",
    "Rapid and weak pulse and Rapid but shallow breathing":
        "ਤੇਜ਼ ਅਤੇ ਕਮਜ਼ੋਰ ਨਬਜ਼ ਅਤੇ ਤੇਜ਼ ਪਰ ਘੱਟ ਸਾਹ ਲੈਣਾ।",
    "Abnormal vital parameters: Elevated heart rate, respiration rate, rectal temperature etc":
        "ਅਸਧਾਰਨ ਮਹੱਤਵਪੂਰਣ ਮਾਪਦੰਡ: ਉੱਚੀ ਹੋਈ ਦਿਲ ਦੀ ਧੜਕਣ, ਸਾਹ ਦੀ ਦਰ, ਗੁਦੇ ਦਾ ਤਾਪਮਾਨ ਆਦਿ।",
    "Unusual salivation and Dizziness / unconsciousness":
        "ਅਸਧਾਰਨ ਲਾਰ ਅਤੇ ਚੱਕਰ ਆਉਣੇ / ਬੇਹੋਸ਼ੀ।",
    "Skin becomes dull and may be cold":
        "ਚਮੜੀ ਨੀਰਸ ਹੋ ਜਾਂਦੀ ਹੈ ਅਤੇ ਠੰਡੀ ਹੋ ਸਕਦੀ ਹੈ।",
    "In case of heat stroke, body temperature is very high sometimes as high as 106 - 108°F":
        "ਹੀਟ ਸਟ੍ਰੋਕ ਦੇ ਮਾਮਲੇ ਵਿੱਚ, ਸ਼ਰੀਰ ਦਾ ਤਾਪਮਾਨ ਬਹੁਤ ਉੱਚਾ ਹੁੰਦਾ ਹੈ—ਕਦੇ-ਕਦੇ 106-108°F ਤੱਕ।",
    "Use of Water to Mitigate Heat Stress":
        "ਗਰਮੀ ਦੇ ਤਣਾਅ ਨੂੰ ਘਟਾਉਣ ਲਈ ਪਾਣੀ ਦੀ ਵਰਤੋਂ",
    "Use of water": "ਪਾਣੀ ਦੀ ਵਰਤੋਂ",
    "The most effective way of combating heat stress in buffalo is wallowing in the water pond":
        "ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਵਿੱਚ ਗਰਮੀ ਦੇ ਤਣਾਅ ਦਾ ਮੁਕਾਬਲਾ ਕਰਨ ਦਾ ਸਭ ਤੋਂ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਤਰੀਕਾ ਪਾਣੀ ਦੇ ਛੱਪੜ ਵਿੱਚ ਨ੍ਹਾਣਾ ਹੈ।",
    "Various cooling systems have been developed for evaporative cooling such as holding-pen cooling,exit-lane cooling, and free-stall cooling. These systems are applicable for the animals maintained in covered pucca sheds. An evaporative system which uses water mist with fan is more effective and economises water use in comparison to repeatedly bathing the animals":
        "ਵਿਵਿਨ ਕੂਲਿੰਗ ਸਿਸਟਮਾਂ ਦੀ ਵਿਕਾਸ ਕੀਤੀ ਗਈ ਹੈ ਜਿਵੇਂ ਕਿ ਹੋਲਡਿੰਗ-ਪੈਨ ਕੂਲਿੰਗ, ਐਗਜ਼ਿਟ-ਲੇਨ ਕੂਲਿੰਗ ਅਤੇ ਫ੍ਰੀ-ਸਟਾਲ ਕੂਲਿੰਗ। ਇਹ ਸਿਸਟਮ ਉਹਨਾਂ ਪਸ਼ੂਆਂ ਲਈ ਲਾਗੂ ਹੁੰਦੇ ਹਨ ਜੋ ਢਕਿਆ ਹੋਇਆ ਪੱਕਾ ਛਾਂਵੇ ਵਿੱਚ ਰੱਖੇ ਜਾਂਦੇ ਹਨ। ਇੱਕ ਐਵੇਪੋਰੇਟਿਵ ਸਿਸਟਮ ਜੋ ਪੱਖੇ ਨਾਲ ਪਾਣੀ ਦੀ ਮਿਸਟ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ, ਬੰਦੀ ਜਾਨਵਰਾਂ ਨੂੰ ਵਾਰੀ-ਵਾਰੀ ਨ੍ਹਾਣਾ ਕਰਨ ਦੇ ਮੁਕਾਬਲੇ ਜ਼ਿਆਦਾ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੈ ਅਤੇ ਪਾਣੀ ਦੀ ਵਰਤੋਂ ਨੂੰ ਘੱਟ ਕਰਦਾ ਹੈ।",
    "The buffalo needs at least twice a day bath in the summer. Misting/Fogging of water in the microenvironment of the animal at least thrice in an hour along with provision of fan is useful in hot dry weather. Auto Mister/ Fugger with mini pumps and cyclic timers are preferable":
        "ਗਰਮੀ ਦੇ ਮੌਸਮ ਵਿੱਚ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਨੂੰ ਦਿਨ ਵਿੱਚ ਘੱਟੋ-ਘੱਟ ਦੋ ਵਾਰੀ ਨ੍ਹਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਗਰਮ ਸੁੱਕੇ ਮੌਸਮ ਵਿੱਚ ਪਸ਼ੂ ਦੇ ਸੂਖਮ ਵਾਤਾਵਰਣ ਵਿੱਚ ਪਾਣੀ ਦੀ ਮਿਸਟਿੰਗ/ਫੋਗਿੰਗ ਅਤੇ ਪੱਖੇ ਦੀ ਸਹਾਇਤਾ ਨਾਲ ਤਿੰਨ ਵਾਰੀ ਇੱਕ ਘੰਟੇ ਵਿੱਚ ਪਾਣੀ ਛਿੜਕਣਾ ਲਾਭਕਾਰੀ ਹੈ। ਆਟੋ ਮਿਸਟਰ/ਫੋਗਰ ਦੇ ਨਾਲ ਛੋਟੇ ਪੰਪ ਅਤੇ ਸਾਇਕਲਿਕ ਟਾਈਮਰ ਚੰਗੇ ਰਹਿੰਦੇ ਹਨ।",
    "Heat stress can also be managed by spraying/ sprinkling water directly on the body of animals for a period of 1 to 5 minutes at an interval of 10- 30 minutes. Fans/blowers should be used to induce evaporation from the skin of animals":
        "10-30 ਮਿੰਟਾਂ ਦੇ ਅੰਤਰਾਲ 'ਤੇ 1 ਤੋਂ 5 ਮਿੰਟ ਲਈ ਜਾਨਵਰਾਂ ਦੇ ਸਰੀਰ 'ਤੇ ਸਿੱਧੇ ਪਾਣੀ ਦਾ ਛਿੜਕਾਅ / ਛਿੜਕਾਅ ਕਰਕੇ ਵੀ ਗਰਮੀ ਦੇ ਤਣਾਅ ਦਾ ਪ੍ਰਬੰਧਨ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ। ਜਾਨਵਰਾਂ ਦੀ ਚਮੜੀ ਤੋਂ ਵਾਸ਼ਪੀਕਰਨ ਪੈਦਾ ਕਰਨ ਲਈ ਪੱਖੇ/ਬਲੋਅਰ ਦੀ ਵਰਤੋਂ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ",
    "Ensure adequate round the clock drinking water to animals, which should be provided under shade":
        "ਪਸ਼ੂਆਂ ਨੂੰ 24 ਘੰਟੇ ਪੀਣ ਵਾਲਾ ਪਾਣੀ ਪ੍ਰਾਪਤ ਹੋਣਾ ਯਕੀਨੀ ਬਣਾਓ, ਜੋ ਛਾਂਵ ਵਿੱਚ ਦਿਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "Other Heat Stress Management Strategies":
        "ਹੋਰ ਤਾਪਮਾਨ ਤਣਾਅ ਪ੍ਰਬੰਧਨ ਰਣਨੀਤੀਆਂ",
    "During heat stress conditions buffaloes should not be allowed to move freely during day hours because they need protection against warm air storms, direct sun exposure and they should be provided with shelter in cool and shady places":
        "ਤਾਪਮਾਨ ਤਣਾਅ ਦੀਆਂ ਹਾਲਤਾਂ ਵਿੱਚ ਦਿਨ ਦੇ ਸਮੇਂ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਨੂੰ ਖੁੱਲ੍ਹਾ ਨਹੀਂ ਜਾਣਾ ਚਾਹੀਦਾ ਕਿਉਂਕਿ ਉਨ੍ਹਾਂ ਨੂੰ ਗਰਮ ਹਵਾ ਦੇ ਤੂਫ਼ਾਨਾਂ, ਸਿੱਧੀ ਧੁੱਪ ਤੋਂ ਬਚਾਅ ਦੀ ਲੋੜ ਹੁੰਦੀ ਹੈ ਅਤੇ ਉਨ੍ਹਾਂ ਨੂੰ ਠੰਢੇ ਅਤੇ ਛਾਂਵੇ ਵਾਲੇ ਸਥਾਨਾਂ ਵਿੱਚ ਆਸਰਾ ਦਿੱਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ।",
    "The most effective source of shade is trees. They provide not only protection from sunlight, but also create a cooling effect through the evaporation of moisture from their leaves":
        "ਸਬ ਤੋਂ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਛਾਂ ਦਾ ਸਰੋਤ ਦਰੱਖਤ ਹਨ। ਇਹ ਸਿਰਫ਼ ਧੁੱਪ ਤੋਂ ਹੀ ਸੁਰੱਖਿਆ ਨਹੀਂ ਪ੍ਰਦਾਨ ਕਰਦੇ, ਬਲਕਿ ਆਪਣੀਆਂ ਪੱਤਿਆਂ ਤੋਂ ਨਮੀ ਦੇ ਬਾਫ਼ ਬਣਨ ਨਾਲ ਠੰਢ ਦਾ ਅਸਰ ਵੀ ਪੈਦਾ ਕਰਦੇ ਹਨ।",
    "If shade trees are not available, thatched roof of a minimum height of 9 feet should be provided. Agri-nets with 20% perforation are also useful. If facilities are not available with the individual farmers, facilities available at the village shall be used by the community. Materials like paddy straw etc,painting the roof with white paint or,providing a false ceiling insulation will help provide a cooler environment. Create barriers against hot wind using thatched wall or wet gunny cloth/ gunny bags":
        "ਜੇਕਰ ਛਾਂ ਦੇ ਦਰੱਖਤ ਉਪਲਬਧ ਨਹੀਂ ਹਨ, ਤਾਂ ਘੱਟੋ-ਘੱਟ 9 ਫੁੱਟ ਦੀ ਉਚਾਈ ਵਾਲੀ ਝੋਪੜੀ ਦੀ ਛੱਤ ਪ੍ਰਦਾਨ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ। 20% ਛੇਦ ਨਾਲ ਐਗਰੀ-ਨੈਟ ਵੀ ਲਾਭਕਾਰੀ ਹੁੰਦੇ ਹਨ। ਜੇਕਰ ਵਿਅਕਤੀਗਤ ਕਿਸਾਨਾਂ ਕੋਲ ਸਹੂਲਤਾਂ ਉਪਲਬਧ ਨਹੀਂ ਹਨ, ਤਾਂ ਪਿੰਡ ਵਿੱਚ ਉਪਲਬਧ ਸਹੂਲਤਾਂ ਦਾ ਵਰਤੋਂ ਸੰਗਠਨ ਦੁਆਰਾ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ। ਧਾਨ ਦੀ ਨਾਲ਼ੀ ਆਦਿ ਜਿਵੇਂ ਸਮਾਨ, ਛੱਤ ਨੂੰ ਸਫੈਦ ਰੰਗ ਨਾਲ ਪੇੰਟ ਕਰਨ ਜਾਂ, ਝੂਠੇ ਛੱਤ ਦੇ ਇਨਸੂਲੇਸ਼ਨ ਪ੍ਰਦਾਨ ਕਰਨ ਨਾਲ ਠੰਢਾ ਮਾਹੌਲ ਪ੍ਰਦਾਨ ਕਰਨ ਵਿੱਚ ਮਦਦ ਮਿਲੇਗੀ। ਠੰਢੀ ਹਵਾ ਦੇ ਹੱਲ ਬਣਾਉਣ ਲਈ ਝੋਪੜੀ ਦੀ ਦਿਵਾਰ ਜਾਂ ਭਿੱਜੇ ਜੂਟ ਦੇ ਕੱਪੜੇ/ ਜੂਟ ਦੇ ਬੈਗਾਂ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "The buffalo shed should be well ventilated that the polluted air can directly diffused outside and clean and fresh air can enter into it. Ensure one ventilator of 3 x 1 feet per cow in covered shed. In these sheds heavy duty fan is best option to facilitate ventilation":
        "ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਦੀ ਝੋਪੜੀ ਵਧੀਆ ਹਵਾ ਦਾਰ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ ਤਾਂ ਜੋ ਪ੍ਰਦੂਸ਼ਿਤ ਹਵਾ ਸਿੱਧੇ ਬਾਹਰ ਨਿਕਲੀ ਜਾ ਸਕੇ ਅਤੇ ਸਾਫ਼ ਅਤੇ ਤਾਜ਼ੀ ਹਵਾ ਉਸ ਵਿੱਚ ਪ੍ਰਵੇਸ਼ ਕਰ ਸਕੇ। ਢਕੀ ਹੋਈ ਝੋਪੜੀ ਵਿੱਚ ਹਰ ਮੱਝਾਂ ਅਤੇ ਗਾਵਾਂ ਲਈ 3 x 1 ਫੁੱਟ ਦਾ ਇੱਕ ਹਵਾਦਾਨ ਯਕੀਨੀ ਬਣਾਓ। ਇਨ੍ਹਾਂ ਝੋਪੜੀਆਂ ਵਿੱਚ ਹਵਾ ਪ੍ਰਵਾਹ ਨੂੰ ਸੁਚਾਰੂ ਬਣਾਉਣ ਲਈ ਹੈਵੀ ਡਿਊਟੀ ਪੱਖਾ ਸਭ ਤੋਂ ਵਧੀਆ ਵਿਕਲਪ ਹੈ।",
    "The proper plantation should be managed in surroundings so that the environment may be cool and fresh and warm air storm could not enter directly in the shed":
        "ਆਸਪਾਸ ਵਿਚ ਸਹੀ ਤਰ੍ਹਾਂ ਪੌਧੇ ਲਗਾਏ ਜਾਣ ਚਾਹੀਦੇ ਹਨ ਤਾਂ ਜੋ ਵਾਤਾਵਰਣ ਠੰਢਾ ਅਤੇ ਤਾਜ਼ਾ ਰਹੇ ਅਤੇ ਗਰਮ ਹਵਾ ਦਾ ਤੂਫਾਨ ਸਿੱਧਾ ਝੋਪੜੀ ਵਿੱਚ ਨਾ ਦਾਖਲ ਹੋ ਸਕੇ।",
    "Air movement: Air movement is more important during hot-humid climate for providing cooling and comfort to the animal. Air movement increases the rate of heat loss from animals body surface, only as long as the air temperature is lower than the animals skin temperature":
        "ਹਵਾ ਦੀ ਗਤੀ: ਗਰਮ-ਨਮੀ ਵਾਲੇ ਮੌਸਮ ਵਿੱਚ ਪਸ਼ੂ ਨੂੰ ਠੰਡਕ ਅਤੇ ਆਰਾਮ ਪ੍ਰਦਾਨ ਕਰਨ ਲਈ ਹਵਾ ਦੀ ਗਤੀ ਬਹੁਤ ਮਹੱਤਵਪੂਰਣ ਹੈ। ਹਵਾ ਦੀ ਗਤੀ ਪਸ਼ੂ ਦੇ ਸਰੀਰ ਦੀ ਸਤਹ ਤੋਂ ਗਰਮੀ ਦੇ ਨੁਕਸਾਨ ਦੀ ਦਰ ਨੂੰ ਵਧਾਉਂਦੀ ਹੈ, ਕੇਵਲ ਇਸ ਸਮੇਂ ਤੱਕ ਜਦੋਂ ਤੱਕ ਹਵਾ ਦਾ ਤਾਪਮਾਨ ਪਸ਼ੂ ਦੀ ਚਮੜੀ ਦੇ ਤਾਪਮਾਨ ਨਾਲੋਂ ਘੱਟ ਹੈ। ",
    "Feeding should be practiced during early morning, evening and at night":
        "ਖੁਰਾਕ ਸਵੇਰੇ ਸਵੇਰੇ, ਸ਼ਾਮ ਨੂੰ ਅਤੇ ਰਾਤ ਨੂੰ ਦਿੱਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ।",
    "Prefer grazing during early morning and late evening hours to avoid the heat stress":
        "ਗਰਮੀ ਦੇ ਤਣਾਅ ਤੋਂ ਬਚਣ ਲਈ ਸਵੇਰੇ ਸਵੇਰੇ ਅਤੇ ਦੇਰ ਸ਼ਾਮ ਨੂੰ ਚਰਾਈ ਨੂੰ ਤਰਜੀਹ ਦਿਓ।",
    "Ration density may be increased so as to provide same nutrients at reduced dry matter intake. Diets with low-fibre and high fermentable carbohydrate have lower dietary heat increment compared to high fibre diets":
        "ਰੇਸ਼ਨ ਦੀ ਘਣਤਾ ਵਧਾਈ ਜਾ ਸਕਦੀ ਹੈ ਤਾਂ ਜੋ ਘੱਟ ਸੁੱਕੇ ਪਦਾਰਥ ਖਪਤ ਦੇ ਨਾਲ ਉਹੀ ਪੋਸ਼ਕ ਤੱਤ ਪ੍ਰਦਾਨ ਕੀਤੇ ਜਾ ਸਕਣ। ਘੱਟ ਫਾਈਬਰ ਅਤੇ ਉੱਚ ਫਰਮੇਨਟੇਬਲ ਕਾਰਬੋਹਾਈਡ੍ਰੇਟ ਵਾਲੀਆਂ ਖੁਰਾਕਾਂ ਵਿੱਚ ਉੱਚ ਫਾਈਬਰ ਵਾਲੀਆਂ ਖੁਰਾਕਾਂ ਦੇ ਮੁਕਾਬਲੇ ਘੱਟ ਗਰਮੀ ਵਧਦੀ ਹੈ।",
    "Ensure increased mineral supplementation during hot weather to meet the increased demand of minerals. Potassium rich mineral mixture should be preferred":
        "ਗਰਮ ਮੌਸਮ ਦੌਰਾਨ ਮਿਨਰਲ ਸਪਲੀਮੈਂਟੇਸ਼ਨ ਵਿੱਚ ਵਾਧਾ ਯਕੀਨੀ ਬਣਾਓ ਤਾਂ ਜੋ ਮਿਨਰਲ ਦੀ ਵਧੀਕ ਮੰਗ ਨੂੰ ਪੂਰਾ ਕੀਤਾ ਜਾ ਸਕੇ। ਪੋਟਾਸੀਅਮ ਨਾਲ ਭਰਪੂਰ ਮਿਨਰਲ ਮਿਸ਼ਰਨ ਨੂੰ ਤਰਜੀਹ ਦਿੱਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ।",
    "Managing Cold Stress": "ਠੰਢੇ ਤਣਾਅ ਦਾ ਪ੍ਰਬੰਧਨ",
    "Monitor weather conditions and act accordingly. Monitor temperature changes and provide more feed to animals in colder weather conditions":
        "ਮੌਸਮ ਦੀਆਂ ਹਾਲਤਾਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ ਅਤੇ ਉਸ ਅਨੁਸਾਰ ਕਾਰਵਾਈ ਕਰੋ। ਤਾਪਮਾਨ ਵਿੱਚ ਹੋਣ ਵਾਲੇ ਬਦਲਾਵਾਂ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ ਅਤੇ ਠੰਢੇ ਮੌਸਮ ਵਿੱਚ ਪਸ਼ੂਆਂ ਨੂੰ ਵਧੇਰੇ ਖੁਰਾਕ ਦਿਓ।",
    "Ensure there is enough shelter from the wind. Effects of cold stress increase when wind speed increases. Any kind of available protection, whether it is natural (bush, valley bottoms or hillsides) or man-made (such as simple windbreak fences or shelters) can be highly valuable in helping animals cope with extreme temperatures and wind-chill effects":
        "ਹਵਾ ਤੋਂ ਪ੍ਰਣਾਲੀ ਸੁਰੱਖਿਆ ਯਕੀਨੀ ਬਣਾਓ। ਜਦੋਂ ਹਵਾ ਦੀ ਗਤੀ ਵਧਦੀ ਹੈ, ਤਾਂ ਠੰਢੇ ਤਣਾਅ ਦੇ ਪ੍ਰਭਾਵ ਵਧ ਜਾਂਦੇ ਹਨ। ਕਿਸੇ ਵੀ ਕਿਸਮ ਦੀ ਉਪਲਬਧ ਸੁਰੱਖਿਆ, ਚਾਹੇ ਉਹ ਕੁਦਰਤੀ (ਬੂਸ਼, ਘਾਟਾਂ ਜਾਂ ਪਹਾੜੀਆਂ) ਹੋਵੇ ਜਾਂ ਮਨੁੱਖ ਦੁਆਰਾ ਬਣਾਈ ਗਈ (ਜਿਵੇਂ ਕਿ ਸਧਾਰਣ ਹਵਾ ਰੁਕਾਵਟ ਵਾਲੇ ਵਾੜ ਜਾਂ ਝੋਪੜੀਆਂ), ਇਹ ਪਸ਼ੂਆਂ ਨੂੰ ਤਾਪਮਾਨ ਅਤੇ ਹਵਾ ਦੀ ਠੰਢ ਨੂੰ ਬਰਦਾਸ਼ਤ ਕਰਨ ਵਿੱਚ ਬਹੁਤ ਲਾਭਦਾਇਕ ਹੋ ਸਕਦੀ ਹੈ।",
    "Provide bedding to help keep animal clean and dry. Bedding, such as barley straw, helps to withstand cold stress":
        "ਜਾਨਵਰਾਂ ਨੂੰ ਸਾਫ਼ ਅਤੇ ਸੁੱਕਾ ਰੱਖਣ ਵਿੱਚ ਮਦਦ ਲਈ ਬਿਸਤਰਾ ਪ੍ਰਦਾਨ ਕਰੋ। ਬੈੱਡਿੰਗ, ਜਿਵੇਂ ਕਿ ਜੌਂ ਦੀ ਤੂੜੀ, ਠੰਡੇ ਤਣਾਅ ਨੂੰ ਸਹਿਣ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ।",
    "Provide additional feed. Increase grain and hay for when temperatures drop below the lower critical threshold level":
        "ਵਧੀਕ ਖੁਰਾਕ ਪ੍ਰਦਾਨ ਕਰੋ। ਜਦੋਂ ਤਾਪਮਾਨ ਘੱਟੋ-ਘੱਟ ਸੰਵੇਦਨਸ਼ੀਲ ਤਾਪਮਾਨ ਤੋਂ ਹੇਠਾਂ ਗਿਰਦਾ ਹੈ, ਤਾਂ ਅਨਾਜ ਅਤੇ ਘਾਸ ਵਿੱਚ ਵਾਧਾ ਕਰੋ।",
    "Provide water. Make sure animals have ample water available at all times. A limit in water available will limit feed intake and make it more difficult for animal to meet their energy requirements. Excessively cold water can severely limit water intake":
        "ਪਾਣੀ ਪ੍ਰਦਾਨ ਕਰੋ। ਇਹ ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਪਸ਼ੂਆਂ ਕੋਲ ਹਰ ਸਮੇਂ ਕਾਫ਼ੀ ਪਾਣੀ ਉਪਲਬਧ ਹੋਵੇ। ਪਾਣੀ ਦੀ ਸੀਮਤ ਉਪਲਬਧਤਾ ਖੁਰਾਕ ਦੀ ਖਪਤ ਨੂੰ ਸੀਮਤ ਕਰੇਗੀ ਅਤੇ ਪਸ਼ੂਆਂ ਲਈ ਆਪਣੀਆਂ ਉਰਜਾ ਦੀ ਜ਼ਰੂਰਤਾਂ ਨੂੰ ਪੂਰਾ ਕਰਨਾ ਜ਼ਿਆਦਾ ਮੁਸ਼ਕਲ ਬਣਾ ਦੇਵੇਗੀ। ਬਹੁਤ ਠੰਢਾ ਪਾਣੀ ਪਾਣੀ ਦੀ ਖਪਤ ਨੂੰ ਬਹੁਤ ਵਧੇਰੇ ਸੀਮਤ ਕਰ ਸਕਦਾ ਹੈ।"
  })
  ..addAll({
    'Climate Change and Dairy Farming': 'ਜਲਵਾਇੂ ਪਰੀਵਰਤਨ ਅਤੇ ਡੇਰੀ ਫਾਰਮਿੰਗ',
    'Heat Stress': 'ਗਰਮੀ ਦਾ ਤਣਾਅ',
    'Increased temperatures in India can cause severe heat stress in dairy animals. Studies show that heat stress can reduce milk production by 10-25% in cows and buffaloes during peak summer months.':
        'ਭਾਰਤ ਵਿੱਚ ਵਧਦੇ ਤਾਪਮਾਨ ਦੇ ਕਾਰਨ ਡੇਰੀ ਪਸ਼ੂਆਂ ਵਿੱਚ ਗਰਮੀ ਦਾ ਗੰਭੀਰ ਤਣਾਅ ਹੋ ਸਕਦਾ ਹੈ। ਅਧਿਐਨ ਦਿਖਾਉਂਦੇ ਹਨ ਕਿ ਗਰਮੀ ਦੇ ਚਰਮ ਮਹੀਨਿਆਂ ਵਿੱਚ ਗਾਂਵਾਂ ਅਤੇ ਮੱਝਾਂ ਵਿੱਚ ਦੁੱਧ ਦੀ ਉਤਪਾਦਨ 10-25% ਤੱਕ ਘਟ ਸਕਦੀ ਹੈ।',
    'Reproductive Health': 'ਪ੍ਰਜਨਨ ਸਿਹਤ',
    'Heat stress impacts reproductive efficiency. Research indicates that conception rates in dairy cows can drop by up to 30% during heat waves. In buffaloes, silent heat and low conception rates during summer are serious problems in northern India. In males, the semen quality and libido also get affected by heat stress.':
        'ਗਰਮੀ ਦਾ ਤਣਾਅ ਪ੍ਰਜਨਨ ਕੁਸ਼ਲਤਾ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ। ਅਨੁਸੰਧਾਨ ਦਰਸਾਉਂਦਾ ਹੈ ਕਿ ਗਰਮੀ ਦੀ ਲਹਿਰਾਂ ਦੌਰਾਨ ਡੇਰੀ ਗਾਂਵਾਂ ਵਿੱਚ ਗਰਭਧਾਰਣ ਦੀ ਦਰ 30% ਤੱਕ ਘਟ ਸਕਦੀ ਹੈ। ਉੱਤਰੀ ਭਾਰਤ ਵਿੱਚ ਮੱਝਾਂ ਵਿੱਚ ਗਰਮੀ ਅਤੇ ਘੱਟ ਗਰਭਧਾਰਣ ਦੀ ਦਰ ਗੰਭੀਰ ਸਮੱਸਿਆਵਾਂ ਹਨ। ਨਰ ਪਸ਼ੂਆਂ ਵਿੱਚ ਵੀਰਜ ਦੀ ਗੁਣਵੱਤਾ ਅਤੇ ਯੋਨ ਇੱਛਾ ਵੀ ਪ੍ਰਭਾਵਿਤ ਹੁੰਦੀ ਹੈ।',
    'Milk Composition': 'ਦੁੱਧ ਦੀ ਰਚਨਾ',
    'Heat stress can reduce the fat and protein content in milk. Studies have shown that in heat-stressed cows, the fat content of milk can drop by 0.2-0.5 percentage points.':
        'ਗਰਮੀ ਦਾ ਤਣਾਅ ਦੁੱਧ ਦੇ ਚਰਬੀ ਅਤੇ ਪ੍ਰੋਟੀਨ ਨੂੰ ਘਟਾ ਸਕਦਾ ਹੈ। ਅਧਿਐਨ ਦਿਖਾਉਂਦੇ ਹਨ ਗਰਮੀ-ਤਣਾਅ ਵਾਲੀਆਂ ਗਾਂਵਾਂ ਵਿੱਚ ਦੁੱਧ ਦੀ ਚਰਬੀ ਦੀ ਮਾਤਰਾ 0.2-0.5 ਪ੍ਰਤੀਸ਼ਤ ਅੰਕ ਤੱਕ ਘਟ ਸਕਦੀ ਹੈ।',
    'Feed Quality and Quantity': 'ਚਾਰੇ ਦੀ ਗੁਣਵੱਤਾ ਅਤੇ ਮਾਤਰਾ',
    'Climate change can lead to altered rainfall patterns and more frequent droughts, affecting the availability and quality of fodder. Poor fodder quality can lead to lower milk production and increased costs for dairy farmers.':
        'ਜਲਵਾਇੂ ਪਰੀਵਰਤਨ ਦੇ ਕਾਰਨ ਵਰਖਾ ਦੇ ਪੈਟਰਨ ਵਿੱਚ ਬਦਲਾਅ ਅਤੇ ਵੱਧ ਸੂਕੇ ਪੈਣ ਕਰਕੇ ਚਾਰੇ ਦੀ ਉਪਲਬਧਤਾ ਅਤੇ ਗੁਣਵੱਤਾ ਪ੍ਰਭਾਵਿਤ ਹੁੰਦੀ ਹੈ। ਖਰਾਬ ਚਾਰੇ ਦੀ ਗੁਣਵੱਤਾ ਦੇ ਕਾਰਨ ਦੁੱਧ ਦੀ ਉਤਪਾਦਨ ਘਟ ਸਕਦੀ ਹੈ ਅਤੇ ਕਿਸਾਨਾਂ ਲਈ ਲਾਗਤ ਵਧ ਸਕਦੀ ਹੈ।',
    'Disease and Parasites': 'ਬਿਮਾਰੀਆਂ ਅਤੇ ਪਰਜੀਵੀ',
    'Higher temperatures and humidity levels can lead to an increase in vector-borne diseases such as tick-borne diseases. The incidence of diseases like mastitis, Foot and Mouth Disease (FMD) can rise, affecting productivity.':
        'ਵੱਧ ਤਾਪਮਾਨ ਅਤੇ ਨਮੀ ਦੇ ਕਾਰਨ ਵੈਕਟਰ-ਜਨਿਤ ਬਿਮਾਰੀਆਂ ਜਿਵੇਂ ਕਿ ਟਿਕ-ਜਨਿਤ ਬਿਮਾਰੀਆਂ ਦੀ ਵਾਧਾ ਹੋ ਸਕਦੀ ਹੈ। ਮਾਸਟਾਈਟਿਸ ਅਤੇ ਖੁਰ ਅਤੇ ਮੂੰਹ ਦੀ ਬਿਮਾਰੀ (ਐਫਐਮਡੀ) ਦੇ ਮਾਮਲਿਆਂ ਵਿੱਚ ਵਾਧਾ ਹੋ ਸਕਦਾ ਹੈ, ਜਿਸ ਨਾਲ ਉਤਪਾਦਕਤਾ ਪ੍ਰਭਾਵਿਤ ਹੁੰਦੀ ਹੈ।',
        'Animal Welfare':'ਪਸ਼ੂਆਂ ਦੀ ਭਲਾਈ',
    'Increased temperatures and humidity negatively affect animal welfare, causing stress and discomfort. This can lead to increased mortality rates during extreme heat events.':
        'ਵੱਧ ਤਾਪਮਾਨ ਅਤੇ ਨਮੀ ਪਸ਼ੂਆਂ ਦੀ ਭਲਾਈ ਨੂੰ ਨਕਾਰਾਤਮਕ ਤੌਰ `ਤੇ ਪ੍ਰਭਾਵਿਤ ਕਰਦੇ ਹਨ, ਜਿਸ ਨਾਲ ਤਣਾਅ ਅਤੇ ਅਸੁਵਿਧਾ ਹੁੰਦੀ ਹੈ। ਚਰਮ ਗਰਮੀ ਦੀਆਂ ਘਟਨਾਵਾਂ ਦੌਰਾਨ ਮੌਤ ਦੀ ਦਰ ਵਧ ਸਕਦੀ ਹੈ।',
    'Adaptation Costs': 'ਅਨੁਕੂਲਤਾ ਦੀ ਲਾਗਤ',
    'Farmers may need to invest in cooling systems, improved housing, and changes in management practices. The cost of installing fans, sprinklers, and cooling pads can be substantial, often ranging from INR 20,000 to 50,000 per animal shed.':
        'ਕਿਸਾਨਾਂ ਨੂੰ ਸ਼ੀਤਲਨ ਪ੍ਰਣਾਲੀਆਂ, ਬਿਹਤਰ ਰਿਹਾਇਸ਼ ਅਤੇ ਪ੍ਰਬੰਧਨ ਦੇ ਅਭਿਆਸ ਵਿੱਚ ਨਿਵੇਸ਼ ਕਰਨ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ। ਪੱਖੇ, ਸਪ੍ਰਿੰਕਲਰ ਅਤੇ ਠੰਢਾ ਪੈਡ ਲਗਾਉਣ ਦੀ ਲਾਗਤ ਪ੍ਰਤੀ ਪਸ਼ੂ ਸ਼ੈਡ INR 20,000 ਤੋਂ 50,000 ਦੇ ਵਿਚਕਾਰ ਹੋ ਸਕਦੀ ਹੈ।',
    'Biodiversity Loss': 'ਜੈਵ ਵਿਭਿੰਨਤਾ ਦਾ ਘਾਟਾ',
    'Climate change impacts the biodiversity of pasturelands. Loss of plant species reduces the variety of feed available, impacting the nutritional intake of dairy animals.':
        'ਜਲਵਾਇੂ ਪਰੀਵਰਤਨ ਚਰਾਗਾਹਾਂ ਦੀ ਜੈਵ ਵਿਭਿੰਨਤਾ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ। ਪੌਧਿਆਂ ਦੀਆਂ ਕਿਸਮਾਂ ਦੇ ਘਾਟੇ ਕਾਰਨ ਉਪਲਬਧ ਚਾਰੇ ਦੀ ਵਿਭਿੰਨਤਾ ਘਟ ਜਾਂਦੀ ਹੈ, ਜਿਸ ਨਾਲ ਡੇਰੀ ਪਸ਼ੂਆਂ ਦੇ ਪੋਸ਼ਣ `ਤੇ ਅਸਰ ਪੈਂਦਾ ਹੈ।',
    'Economic Impact on Farmers': 'ਕਿਸਾਨਾਂ `ਤੇ ਆਰਥਿਕ ਪ੍ਰਭਾਵ',
    'The cumulative effect of reduced milk production, increased costs for feed, water, and veterinary care, and potential loss of livestock due to extreme weather events can significantly affect the livelihood of dairy farmers.':
        'ਕਲਾਈਮੈਟ ਚੇਂਜ ਦਾ ਕੁੱਲ ਪ੍ਰਭਾਵ, ਦੁੱਧ ਦੀ ਉਤਪਾਦਨ ਵਿੱਚ ਕਮੀ, ਚਾਰੇ, ਪਾਣੀ ਅਤੇ ਪਸ਼ੂ ਚਿਕਿਤਸਾ ਦੇਖਭਾਲ ਦੀ ਵੱਧਦੀ ਲਾਗਤ, ਅਤੇ ਚਰਮ ਮੌਸਮੀ ਘਟਨਾਵਾਂ ਦੇ ਕਾਰਨ ਸੰਭਾਵਿਤ ਪਸ਼ੂਆਂ ਦੇ ਘਾਟੇ ਦੇ ਕਾਰਨ ਕਿਸਾਨਾਂ ਦੀ ਆਜੀਵਿਕਾ ਨੂੰ ਗੰਭੀਰ ਤੌਰ `ਤੇ ਪ੍ਰਭਾਵਿਤ ਕਰ ਸਕਦੀ ਹੈ।',
  })..addAll({
    'January': 'ਜਨਵਰੀ',
    'February': 'ਫਰਵਰੀ',
    'March': 'ਮਾਰਚ',
    'April': 'ਅਪ੍ਰੈਲ',
    'May': 'ਮਈ',
    'June': 'ਜੂਨ',
    'July': 'ਜੁਲਾਈ',
    'August': 'ਅਗਸਤ',
    'September': 'ਸਤੰਬਰ',
    'October': 'ਅਕਤੂਬਰ',
    'November': 'ਨਵੰਬਰ',
    'December': 'ਦਸੰਬਰ'
})..addAll({
    'Full Name': 'ਪੂਰਾ ਨਾਮ',
    'Enter your Full Name': 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    'Email ID': 'ਈਮੇਲ ਆਈਡੀ',
    'Mobile Number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
    'Register': 'ਰਜਿਸਟਰ ਕਰੋ',
    'Already Have Account - ': 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ - ',
    'Login': 'ਲੌਗਇਨ ਕਰੋ',
    'Send OTP': 'OTP ਭੇਜੋ',
    'Skip': 'ਛੱਡੋ',
    'Enter OTP': 'OTP ਦਰਜ ਕਰੋ',
    'Please Enter Something': 'ਕਿਰਪਾ ਕਰਕੇ ਕੁਝ ਦਰਜ ਕਰੋ'
})..addAll({
    'Ration Formulation for a lactating buffalo with body weight 450-500 Kg) during heat stress season': 'ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੇ ਮੌਸਮ ਦੌਰਾਨ ਦੁੱਧ ਦੇਣ ਵਾਲੀ ਮੱਝ (ਸਰੀਰ ਦਾ ਭਾਰ 450-500 ਕਿਲੋਗ੍ਰਾਮ) ਲਈ ਰਾਸ਼ਨ ਫਾਰਮੂਲੇਸ਼ਨ',
    'Ration ingredient': 'ਰਾਸ਼ਨ ਸਮੱਗਰੀ',
    'Milk Yield': 'ਦੁੱਧ ਉਤਪਾਦਨ',
    'Kg': 'ਕਿਲੋਗ੍ਰਾਮ',
    'Green Fodder (Maize/Jowar)': 'ਹਰਾ ਚਾਰਾ (ਮੱਕੀ/ਜੁਆਰ)',
    'Dry fodder (straw/Maize Stover)': 'ਸੁੱਕਾ ਚਾਰਾ (ਤੂੜੀ/ਮੱਕੀ ਦਾ ਡੰਠਲ)',
    'Grain (Maize/Jowar)': 'ਅਨਾਜ (ਮੱਕੀ/ਜੁਆਰ)',
    'Concentrate mixture*': 'ਸੰਘਣਾ ਮਿਸ਼ਰਣ*',
    '*Concentrate mixture formulation': '*ਸੰਘਣਾ ਮਿਸ਼ਰਣ ਫਾਰਮੂਲੇਸ਼ਨ',
    'Ingredients': 'ਸਮੱਗਰੀ',
    'Formulation': 'ਫਾਰਮੂਲੇਸ਼ਨ ',
    'Maize/Jowar/ wheat/ rice/oats admixture': 'ਮੱਕੀ/ਜੁਆਰ/ਕਣਕ/ਚਾਵਲ/ਜਵੀ ਮਿਸ਼ਰਣ',
    'Jowar': 'ਜੁਆਰ',
    'Rice bran (deoiled)': 'ਚਾਵਲ ਦੀ ਭੂਸੀ (ਤੇਲ ਰਹਿਤ)',
    'Wheat bran (deoiled)': 'ਕਣਕ ਦੀ ਚੋਕਰ (ਤੇਲ ਰਹਿਤ)',
    'Groundnut cake': 'ਮੂੰਗਫਲੀ ਦੀ ਖੱਲ',
    'Soyabean cake': 'ਸੋਇਆਬੀਨ ਦੀ ਖੱਲ',
    'Mustard cake': 'ਸਰ੍ਹੋਂ ਦੀ ਖੱਲ',
    'Cotton seed cake (decorticated)': 'ਕਪਾਹ ਦੀ ਖੱਲ (ਛਿੱਲ ਰਹਿਤ)',
    'Cotton seed cake (undecorticated)': 'ਕਪਾਹ ਦੀ ਖੱਲ (ਛਿੱਲ ਸਹਿਤ)',
    'Mineral mixture': 'ਖਣਿਜ ਮਿਸ਼ਰਣ',
    'Salt': 'ਲੂਣ',
    'Total': 'ਕੁੱਲ',
    'Note': 'ਨੋਟ',
    'Provide additional 1.5 – 2 kg concentrate mixture during heat stress season': 'ਗਰਮੀ ਦੇ ਤਣਾਅ ਦੇ ਮੌਸਮ ਦੌਰਾਨ ਵਾਧੂ 1.5 - 2 ਕਿਲੋਗ੍ਰਾਮ ਸੰਘਣਾ ਮਿਸ਼ਰਣ ਪ੍ਰਦਾਨ ਕਰੋ',
    'Provide additional 1 kg of concentrate mixture per 2.5 litre of milk production beyond 10/15 kg of milk production': '10/15 ਕਿਲੋਗ੍ਰਾਮ ਦੁੱਧ ਉਤਪਾਦਨ ਤੋਂ ਵੱਧ ਲਈ ਪ੍ਰਤੀ 2.5 ਲੀਟਰ ਦੁੱਧ ਉਤਪਾਦਨ `ਤੇ ਵਾਧੂ 1 ਕਿਲੋਗ੍ਰਾਮ ਸੰਘਣਾ ਮਿਸ਼ਰਣ ਪ੍ਰਦਾਨ ਕਰੋ',
    'Provide 500 gm of grain or 2.5 Kg cereal fodder for every 50 Kg increase in body weight beyond 500 Kg': '500 ਕਿਲੋਗ੍ਰਾਮ ਤੋਂ ਵੱਧ ਸਰੀਰ ਦੇ ਭਾਰ ਵਿੱਚ ਪ੍ਰਤੀ 50 ਕਿਲੋਗ੍ਰਾਮ ਵਾਧੇ ਲਈ 500 ਗ੍ਰਾਮ ਅਨਾਜ ਜਾਂ 2.5 ਕਿਲੋਗ੍ਰਾਮ ਅਨਾਜ ਦਾ ਚਾਰਾ ਪ੍ਰਦਾਨ ਕਰੋ',
    'Due to the dry weather, farmers can irrigate the moong crop as per the crop requirement. Weeds are a big problem during the first 4-5 weeks of sowing. Therefore, weeding should be done within 15-20 days of sowing.':
    'ਖੁਸ਼ਕ ਮੌਸਮ ਦੀ ਸੰਭਾਵਨਾ ਦੇ ਕਾਰਨ, ਕਿਸਾਨ ਫਸਲ ਦੀ ਲੋੜ ਅਨੁਸਾਰ ਮੂੰਗੀ ਦੀ ਫਸਲ ਨੂੰ ਸਿੰਚਾਈ ਕਰ ਸਕਦੇ ਹਨ। ਬਿਜਾਈ ਤੋਂ ਬਾਅਦ ਪਹਿਲੇ 4-5 ਹਫ਼ਤਿਆਂ ਦੌਰਾਨ ਨਦੀਨਾਂ ਦੀ ਸਮੱਸਿਆ ਵਧੇਰੇ ਹੁੰਦੀ ਹੈ। ਇਸ ਲਈ, ਬਿਜਾਈ ਤੋਂ 15-20 ਦਿਨਾਂ ਦੇ ਅੰਦਰ-ਅੰਦਰ ਗੋਡੀ ਕਰ ਲੈਣੀ ਚਾਹੀਦੀ ਹੈ।',
})..addAll({
  'The National Dairy Research Institute, Karnal, India is a Deemed University under the Indian Council of Agricultural Research of the Ministry of Agriculture and Farmers Welfare, Government of India. The premier ‘Research Institute’ of India in the field of dairy, the National Dairy Research Institute has developed considerable expertise over the last five decades in different areas of Dairy Production, Processing, Management and Human Resource Development.':'"ਰਾਸ਼ਟਰੀ ਡੇਰੀ ਅਨੁਸੰਧਾਨ ਸੰਸਥਾਨ, ਕਰਨਾਲ, ਭਾਰਤ, ਭਾਰਤੀ ਕ੍ਰਿਸ਼ੀ ਅਨੁਸੰਧਾਨ ਪਰਿਸ਼ਦ ਦੇ ਹੇਠ ਇੱਕ ਮਾਨਤ ਯੂਨੀਵਰਸਿਟੀ ਹੈ ਜੋ ਕਿ ਭਾਰਤ ਸਰਕਾਰ ਦੇ ਕ੍ਰਿਸ਼ੀ ਅਤੇ ਕਿਸਾਨ ਕਲਿਆਣ ਮੰਤਰਾਲੇ ਦੇ ਅਧੀਨ ਹੈ।  ਡੇਰੀ ਦੇ ਖੇਤਰ ਵਿੱਚ ਭਾਰਤ ਦਾ ਪ੍ਰਮੁੱਖ `ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ`, ਰਾਸ਼ਟਰੀ ਡੇਰੀ ਰਿਸਰਚ ਇੰਸਟੀਚਿਊਟ ਨੇ ਪਿਛਲੇ ਪੰਜ ਦਹਾਕਿਆਂ ਦੌਰਾਨ ਡੇਰੀ ਉਤਪਾਦਨ, ਪ੍ਰਕਿਰਿਆਕਰਨ, ਪ੍ਰਬੰਧਨ ਅਤੇ ਮਾਨਵ ਸਰੋਤ ਵਿਕਾਸ ਦੇ ਵੱਖ-ਵੱਖ ਖੇਤਰਾਂ ਵਿੱਚ ਵਧੀਆ ਪ੍ਰਗਤੀ ਕੀਤੀ ਹੈ।',
  'Being the National Institute, it conducts basic and applied research with the objective to enhance animal productivity and also to develop cost-effective technologies for the benefit of the millions of the farming community. The Institute has had been continuously working to develop its research and developed as well as human resource development programmes to better serve the nation in terms of food security, employment generation, poverty alleviation and economic prosperity.':'ਨੈਸ਼ਨਲ ਇੰਸਟੀਚਿਊਟ ਹੋਣ ਦੇ ਨਾਤੇ, ਇਹ ਪਸ਼ੂ ਉਤਪਾਦਕਤਾ ਨੂੰ ਵਧਾਉਣ ਅਤੇ ਲੱਖਾਂ ਕਿਸਾਨ ਭਾਈਚਾਰੇ ਦੇ ਲਾਭ ਲਈ ਲਾਗਤ-ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਤਕਨਾਲੋਜੀਆਂ ਨੂੰ ਵਿਕਸਤ ਕਰਨ ਦੇ ਉਦੇਸ਼ ਨਾਲ ਬੁਨਿਆਦੀ ਅਤੇ ਲਾਗੂ ਖੋਜ ਕਰਦਾ ਹੈ। ਇੰਸਟੀਚਿਊਟ ਲਗਾਤਾਰ ਆਪਣੇ ਅਨੁਸੰਧਾਨ ਅਤੇ ਮਨੁੱਖੀ ਸਰੋਤ ਵਿਕਾਸ ਪ੍ਰੋਗਰਾਮਾਂ ਨੂੰ ਵਿਕਸਿਤ ਕਰਨ ਵਿੱਚ ਲੱਗਾ ਰਹੀ ਹੈ ਤਾਂ ਕਿ ਖੁਰਾਕ ਸੁਰੱਖਿਆ, ਰੋਜ਼ਗਾਰ ਸਿਰਜਣ, ਗਰੀਬੀ ਘਟਾਉਣ ਅਤੇ ਆਰਥਿਕ ਖੁਸ਼ਹਾਲੀ ਦੇ ਮਾਮਲੇ ਵਿੱਚ ਰਾਸ਼ਟਰ ਨੂੰ ਬਿਹਤਰ ਸੇਵਾ ਦਿੱਤੀ ਜਾ ਸਕੇ।'
}
  
);
